// Package ciconfig generates the .gitlab-ci.yml of the oh-runner project. The
// file is owned by oh: `oh remote setup` rewrites it, and the target projects'
// own CI is never touched.
package ciconfig

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/datichb/openhub/cli/internal/remote"
	"github.com/datichb/openhub/cli/internal/runtime/container"
)

// Builders of the project image on the runner.
const (
	BuilderKaniko = "kaniko" // no privileged mode needed (default)
	BuilderDinD   = "dind"   // Docker-in-Docker: privileged runner
)

// Default images (pinned; overridable per target).
const (
	DefaultKanikoImage = "gcr.io/kaniko-project/executor:v1.23.2-debug"
	DefaultDockerImage = "docker:27"
	DefaultDinDImage   = "docker:27-dind"
	DefaultFetchImage  = "alpine:3.20"
	DefaultTimeout     = "3h"
	DefaultTag         = "oh"
	DefaultArch        = "amd64"
)

// Marker is the first line of every generated file.
const Marker = "# Generated by oh (oh remote setup)"

// Options configure the pipeline.
type Options struct {
	Tag         string // runner tag (default "oh")
	Builder     string // kaniko (default) | dind
	Arch        string // runner architecture: amd64 (default) | arm64
	Timeout     string // run job timeout (default 3h)
	KanikoImage string
	DockerImage string
	DinDImage   string
	FetchImage  string
}

func (o Options) withDefaults() Options {
	def := func(s *string, v string) {
		if *s == "" {
			*s = v
		}
	}
	def(&o.Tag, DefaultTag)
	def(&o.Builder, BuilderKaniko)
	def(&o.Arch, DefaultArch)
	def(&o.Timeout, DefaultTimeout)
	def(&o.KanikoImage, DefaultKanikoImage)
	def(&o.DockerImage, DefaultDockerImage)
	def(&o.DinDImage, DefaultDinDImage)
	def(&o.FetchImage, DefaultFetchImage)
	return o
}

// Validate reports invalid options.
func (o Options) Validate() error {
	o = o.withDefaults()
	if o.Builder != BuilderKaniko && o.Builder != BuilderDinD {
		return fmt.Errorf("unknown image builder %q (kaniko | dind)", o.Builder)
	}
	if o.Arch != "amd64" && o.Arch != "arm64" {
		return fmt.Errorf("unknown runner architecture %q (amd64 | arm64)", o.Arch)
	}
	for _, v := range []string{o.Tag, o.Timeout} {
		if strings.ContainsAny(v, "\"'\n\t :#[]{},") {
			return fmt.Errorf("invalid value %q", v)
		}
	}
	for _, v := range []string{o.KanikoImage, o.DockerImage, o.DinDImage, o.FetchImage} {
		if strings.ContainsAny(v, "\"'\n\t #[]{},") {
			return fmt.Errorf("invalid image %q", v)
		}
	}
	return nil
}

// layerDockerfile is the thin oh layer added on top of the project base image:
// the oh binary installs the tool, the fake bd and the oh directories itself
// (oh runner install), in the image's libc.
const layerDockerfile = `ARG OH_IMAGE_BASE
FROM ${OH_IMAGE_BASE}
ARG ` + remote.VarToolVersion + `
USER root
COPY oh /usr/local/bin/oh
COPY ca-certificates.crt /opt/oh/ca-certificates.crt
ENV SSL_CERT_FILE=/opt/oh/ca-certificates.crt
RUN ["/usr/local/bin/oh", "runner", "install"]
`

// Generate returns the .gitlab-ci.yml content.
func Generate(o Options) ([]byte, error) {
	if err := o.Validate(); err != nil {
		return nil, err
	}
	o = o.withDefaults()
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("%s — pipeline schema %d.\n", Marker, remote.PipelineSchema)
	w("# Do not edit: the file is rewritten by `oh remote setup`. Runs only when\n")
	w("# triggered by oh with a session (never on push). Secrets are masked CI\n")
	w("# variables of this project: %s, %s, %s<project id>.\n", remote.VarLLMKey, remote.VarTeamStateToken, strings.TrimSuffix(remote.ProjectTokenVar(0), "0"))
	w("\nworkflow:\n  rules:\n")
	w("    - if: '$CI_PIPELINE_SOURCE == \"trigger\" && $%s'\n", remote.VarSessionID)
	w("    - when: never\n")
	w("\nstages: [prepare, image, run]\n")
	w("\ndefault:\n  tags: [%s]\n", o.Tag)
	w("\nvariables:\n  GIT_STRATEGY: none\n  %s: \"%d\"\n", remote.VarPipelineSchema, remote.PipelineSchema)

	// prepare: the oh binary (release or development package) + layer context.
	w("\noh-cli:\n  stage: prepare\n  image: %s\n", o.FetchImage)
	w("  rules:\n    - if: '$%s == \"true\"'\n", remote.VarImageBuild)
	w("  script:\n    - |\n")
	script(&b, 6, fetchScript(o.Arch))
	w("  artifacts:\n    expire_in: 1 hour\n    paths: [oh-layer/]\n")

	// image: base (dev Dockerfile of the project) then the thin oh layer.
	w("\noh-image:\n  stage: image\n  needs: [oh-cli]\n")
	w("  rules:\n    - if: '$%s == \"true\"'\n", remote.VarImageBuild)
	switch o.Builder {
	case BuilderKaniko:
		w("  image:\n    name: %s\n    entrypoint: [\"\"]\n", o.KanikoImage)
		w("  script:\n    - |\n")
		script(&b, 6, kanikoScript())
	case BuilderDinD:
		w("  image: %s\n  services: [%s]\n", o.DockerImage, o.DinDImage)
		w("  variables:\n    DOCKER_TLS_CERTDIR: /certs\n")
		w("  script:\n    - |\n")
		script(&b, 6, dindScript())
	}

	// run: oh runner in the project image.
	w("\noh-run:\n  stage: run\n")
	w("  image:\n    name: $%s\n    entrypoint: [\"\"]\n", remote.VarImage)
	w("  needs:\n    - job: oh-image\n      optional: true\n")
	w("  timeout: %s\n", o.Timeout)
	w("  variables:\n    OH_HOME: /tmp/oh\n")
	w("  script:\n    - oh runner run --out \"$CI_PROJECT_DIR/%s\"\n", remote.OutDir)
	w("  artifacts:\n    when: always\n    expire_in: 7 days\n    paths: [%s/]\n", remote.OutDir)
	return b.Bytes(), nil
}

// script writes lines indented by n spaces.
func script(b *bytes.Buffer, n int, s string) {
	pad := strings.Repeat(" ", n)
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(pad + line + "\n")
	}
}

// heredoc writes content to path in a shell script.
func heredoc(path, content string) string {
	return "cat > " + path + " <<'OH_EOF'\n" + strings.TrimRight(content, "\n") + "\nOH_EOF\n"
}

func fetchScript(arch string) string {
	v := func(name string) string { return "${" + name + ":-}" }
	return `set -eu
mkdir -p oh-layer
if [ -n "` + v(remote.VarCLIURL) + `" ]; then
  wget -q --header "JOB-TOKEN: $CI_JOB_TOKEN" -O oh-layer/oh "$` + remote.VarCLIURL + `"
  if [ -n "` + v(remote.VarCLISHA256) + `" ]; then echo "$` + remote.VarCLISHA256 + `  oh-layer/oh" | sha256sum -c -; fi
else
  base="https://github.com/datichb/openhub/releases/download/v$` + remote.VarCLIVersion + `"
  wget -q -O /tmp/openhub_linux_` + arch + `.tar.gz "$base/openhub_linux_` + arch + `.tar.gz"
  wget -q -O /tmp/checksums.txt "$base/checksums.txt"
  (cd /tmp && grep " openhub_linux_` + arch + `.tar.gz\$" checksums.txt | sha256sum -c -)
  tar -xzf /tmp/openhub_linux_` + arch + `.tar.gz -C /tmp oh
  mv /tmp/oh oh-layer/oh
fi
chmod 0755 oh-layer/oh
cp /etc/ssl/certs/ca-certificates.crt oh-layer/ca-certificates.crt
` + heredoc("oh-layer/Dockerfile", layerDockerfile) + heredoc("oh-layer/Dockerfile.base", container.DefaultBaseDockerfile)
}

// projectToken exports GIT_PASSWORD from OH_PROJECT_TOKEN_<OH_PROJECT_ID>.
func projectToken() string {
	return `token_var="` + strings.TrimSuffix(remote.ProjectTokenVar(0), "0") + `${` + remote.VarProjectID + `}"
eval "GIT_PASSWORD=\"\${$token_var:-}\""
if [ -z "$GIT_PASSWORD" ]; then echo "oh: CI variable $token_var is missing (oh remote setup --project)"; exit 1; fi
export GIT_USERNAME=oauth2 GIT_PASSWORD
host="${CI_SERVER_FQDN:-$CI_SERVER_HOST}"
`
}

func kanikoScript() string {
	return `set -eu
` + projectToken() + `mkdir -p /kaniko/.docker
auth=$(printf '%s:%s' "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 | tr -d '\n')
printf '{"auths":{"%s":{"auth":"%s"}}}' "$CI_REGISTRY" "$auth" > /kaniko/.docker/config.json
if [ -n "${` + remote.VarDockerfile + `:-}" ]; then
  ctx="git://$host/$` + remote.VarProjectPath + `.git#refs/heads/$` + remote.VarRef + `"
  if [ -n "${` + remote.VarCommit + `:-}" ]; then ctx="$ctx#$` + remote.VarCommit + `"; fi
  /kaniko/executor --context "$ctx" --dockerfile "$` + remote.VarDockerfile + `" --destination "$` + remote.VarImageBase + `"
else
  /kaniko/executor --context "dir://$CI_PROJECT_DIR/oh-layer" --dockerfile "$CI_PROJECT_DIR/oh-layer/Dockerfile.base" --destination "$` + remote.VarImageBase + `"
fi
/kaniko/executor --context "dir://$CI_PROJECT_DIR/oh-layer" --dockerfile "$CI_PROJECT_DIR/oh-layer/Dockerfile" --build-arg "OH_IMAGE_BASE=$` + remote.VarImageBase + `" --build-arg "` + remote.VarToolVersion + `=$` + remote.VarToolVersion + `" --destination "$` + remote.VarImage + `"
`
}

func dindScript() string {
	return `set -eu
` + projectToken() + `echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
if [ -n "${` + remote.VarDockerfile + `:-}" ]; then
  apk add --no-cache git >/dev/null
  git clone --quiet --depth 50 --branch "$` + remote.VarRef + `" "https://oauth2:$GIT_PASSWORD@$host/$` + remote.VarProjectPath + `.git" /tmp/project
  if [ -n "${` + remote.VarCommit + `:-}" ]; then git -C /tmp/project checkout --quiet "$` + remote.VarCommit + `"; fi
  docker build -f "/tmp/project/$` + remote.VarDockerfile + `" -t "$` + remote.VarImageBase + `" /tmp/project
else
  docker build -f oh-layer/Dockerfile.base -t "$` + remote.VarImageBase + `" oh-layer
fi
docker push "$` + remote.VarImageBase + `"
docker build --build-arg "OH_IMAGE_BASE=$` + remote.VarImageBase + `" --build-arg "` + remote.VarToolVersion + `=$` + remote.VarToolVersion + `" -t "$` + remote.VarImage + `" oh-layer
docker push "$` + remote.VarImage + `"
`
}
