#!/usr/bin/env bats
# Tests d'intégration pour la phase de découverte au deploy (_cmd_deploy_discover)
# Stratégie : OC_NON_INTERACTIVE=1 pour éviter les prompts stdin dans tous les tests sauf
# les tests de comportement non-interactif explicites.

setup() {
  HUB_ROOT="$BATS_TEST_DIRNAME/.."
  FAKE_HUB="$(mktemp -d)"
  FAKE_PROJECT="$(mktemp -d)"

  # Structure du hub factice
  mkdir -p "$FAKE_HUB/agents/planning"
  mkdir -p "$FAKE_HUB/config"
  mkdir -p "$FAKE_HUB/projects"
  mkdir -p "$FAKE_HUB/scripts"

  # Symlinks vers les scripts et skills réels
  ln -s "$HUB_ROOT/scripts" "$FAKE_HUB/scripts"
  ln -s "$HUB_ROOT/skills"  "$FAKE_HUB/skills"

  # Agent hub minimal (planner)
  cat > "$FAKE_HUB/agents/planning/planner.md" <<'AGENTEOF'
---
id: planner
label: ProjectPlanner
description: Planificateur de projet de test
mode: primary
targets: [opencode]
skills: []
---

# ProjectPlanner

Corps du planificateur de test.
AGENTEOF

  # hub.json minimal
  cat > "$FAKE_HUB/config/hub.json" <<'HUBEOF'
{
  "version": "1.0.0",
  "default_provider": {"name": "", "api_key": "", "base_url": "", "model": ""},
  "opencode": {"model": "claude-sonnet-4-5", "disabled_native_agents": []},
  "cli": {"language": "fr"}
}
HUBEOF
  cp "$FAKE_HUB/config/hub.json" "$FAKE_HUB/config/hub.json.example"
  echo '{"mappings": {}}' > "$FAKE_HUB/config/stack-skills.json"

  # projects.md avec le projet fake
  cat > "$FAKE_HUB/projects/projects.md" <<EOF
# Registre de test

## FAKE-PROJ
- Nom : Fake Project
- Stack : TypeScript
- Agents : all
EOF

  # paths.local.md pointant vers FAKE_PROJECT
  echo "FAKE-PROJ=${FAKE_PROJECT}" > "$FAKE_HUB/projects/paths.local.md"
  touch "$FAKE_HUB/projects/api-keys.local.md"

  # Créer le répertoire .opencode/agents dans le projet
  mkdir -p "$FAKE_PROJECT/.opencode/agents"

  export HUB_DIR="$FAKE_HUB"
  export CANONICAL_AGENTS_DIR="$FAKE_HUB/agents"
  export PROJECTS_FILE="$FAKE_HUB/projects/projects.md"
  export PATHS_FILE="$FAKE_HUB/projects/paths.local.md"
  export API_KEYS_FILE="$FAKE_HUB/projects/api-keys.local.md"
  export AGENT_ALIASES_FILE="$HUB_ROOT/config/agent-aliases.json"
  # LIB_DIR doit pointer vers les vrais scripts (via le symlink)
  export LIB_DIR="$HUB_ROOT/scripts/lib"
  export SCRIPTS_DIR="$HUB_ROOT/scripts"

  # Non-interactif par défaut (CI-safe)
  export OC_NON_INTERACTIVE=1
}

teardown() {
  rm -rf "$FAKE_HUB" "$FAKE_PROJECT"
}

# ── Comportement non-interactif ───────────────────────────────────────────────

@test "_cmd_deploy_discover : ne prompt pas si OC_NON_INTERACTIVE=1" {
  # Créer un agent non-hub dans le projet
  cat > "$FAKE_PROJECT/.opencode/agents/my-planner.md" <<'EOF'
---
id: my-planner
---
# Mon Planner
EOF

  export OC_NON_INTERACTIVE=1
  source "$HUB_ROOT/scripts/common.sh"
  source "$HUB_ROOT/scripts/lib/agent-discovery.sh"
  source "$HUB_ROOT/scripts/cmd-deploy.sh"

  # Doit se terminer sans erreur et sans modifier projects.md
  run _cmd_deploy_discover "FAKE-PROJ" "$FAKE_PROJECT"
  [ "$status" -eq 0 ]
  # projects.md ne doit pas contenir de External agents
  run grep "External agents" "$FAKE_HUB/projects/projects.md"
  [ "$status" -ne 0 ]
}

@test "_cmd_deploy_discover : ne prompt pas si aucun agent non-hub trouvé" {
  # Créer un agent généré par le hub dans le projet (doit être ignoré)
  cat > "$FAKE_PROJECT/.opencode/agents/planner.md" <<'EOF'
<!-- generated by openhub v1.0.0 -->
# Planner Hub
Corps.
EOF

  source "$HUB_ROOT/scripts/common.sh"
  source "$HUB_ROOT/scripts/lib/agent-discovery.sh"
  source "$HUB_ROOT/scripts/cmd-deploy.sh"

  run _cmd_deploy_discover "FAKE-PROJ" "$FAKE_PROJECT"
  [ "$status" -eq 0 ]
  run grep "External agents" "$FAKE_HUB/projects/projects.md"
  [ "$status" -ne 0 ]
}

@test "_cmd_deploy_discover : ne prompt pas si le projet n'a pas de .opencode/agents/" {
  # Supprimer le répertoire agents
  rm -rf "$FAKE_PROJECT/.opencode/agents"

  source "$HUB_ROOT/scripts/common.sh"
  source "$HUB_ROOT/scripts/lib/agent-discovery.sh"
  source "$HUB_ROOT/scripts/cmd-deploy.sh"

  run _cmd_deploy_discover "FAKE-PROJ" "$FAKE_PROJECT"
  [ "$status" -eq 0 ]
}

@test "_cmd_deploy_discover : ignore les agents déjà déclarés dans External agents" {
  cat > "$FAKE_PROJECT/.opencode/agents/my-planner.md" <<'EOF'
---
id: my-planner
---
# Mon Planner
EOF

  # Déclarer déjà l'agent comme configuré
  perl -i -0777pe '
    s{(^## FAKE-PROJ\n.*?)(- Agents : [^\n]+\n)}
     {$1$2- External agents : .opencode/agents/my-planner.md:substitute:planner\n}ms
  ' "$FAKE_HUB/projects/projects.md"

  source "$HUB_ROOT/scripts/common.sh"
  source "$HUB_ROOT/scripts/lib/agent-discovery.sh"
  source "$HUB_ROOT/scripts/cmd-deploy.sh"

  # Doit s'exécuter sans prompt (OC_NON_INTERACTIVE=1) et sans modifier projects.md
  run _cmd_deploy_discover "FAKE-PROJ" "$FAKE_PROJECT"
  [ "$status" -eq 0 ]
}

# ── Persistance (simulée via stdin pipe en mode interactif) ──────────────────

@test "_cmd_deploy_discover : persiste le choix 'ignorer' — projects.md non modifié" {
  cat > "$FAKE_PROJECT/.opencode/agents/my-planner.md" <<'EOF'
---
id: my-planner
---
# Mon Planner
EOF

  # Mode non-interactif → discover skip silencieux
  export OC_NON_INTERACTIVE=1
  source "$HUB_ROOT/scripts/common.sh"
  source "$HUB_ROOT/scripts/lib/agent-discovery.sh"
  source "$HUB_ROOT/scripts/cmd-deploy.sh"

  _cmd_deploy_discover "FAKE-PROJ" "$FAKE_PROJECT"

  # Aucune modification dans projects.md
  run grep "External agents" "$FAKE_HUB/projects/projects.md"
  [ "$status" -ne 0 ]
}
