#!/usr/bin/env bats
# Tests unitaires pour scripts/lib/prompt-builder.sh
# Fonctions testées : get_hub_version, build_generated_header, 
#                     extract_frontmatter_value, extract_frontmatter_list,
#                     read_agent_frontmatter, _get_model_rank, clamp_model,
#                     resolve_agent_model, extract_permission_json

load helpers

setup() {
  common_setup
  
  # Sourcer common.sh pour avoir accès à _api_keys_get
  export SCRIPT_DIR="$BATS_TEST_DIRNAME/../scripts"
  export LIB_DIR="$SCRIPT_DIR/lib"
  source "$SCRIPT_DIR/common.sh"
  
  # Sourcer prompt-builder.sh
  source "$BATS_TEST_DIRNAME/../scripts/lib/prompt-builder.sh"
  
  # Créer un hub.json de test
  make_test_hub_config "claude-sonnet-4-5"
  
  # Créer répertoire pour agents de test
  mkdir -p "$TEST_DIR/agents/planning"
  mkdir -p "$TEST_DIR/agents/dev"
  export CANONICAL_AGENTS_DIR="$TEST_DIR/agents"
}

teardown() {
  common_teardown
}

# ── get_hub_version ────────────────────────────────────────────────────────────

@test "get_hub_version : retourne la version depuis hub.json" {
  run get_hub_version
  [ "$status" -eq 0 ]
  [ "$output" = "test" ]
}

@test "get_hub_version : retourne 'unknown' ou vide si hub.json absent" {
  rm -f "$HUB_CONFIG"
  export HUB_CONFIG="/tmp/nonexistent_hub_$(date +%s).json"
  run get_hub_version
  [ "$status" -eq 0 ]
  # Peut retourner 'unknown' (sans jq) ou vide (avec jq)
  [[ "$output" == "unknown" || -z "$output" ]]
}

@test "get_hub_version : gère hub.json sans version" {
  echo '{}' > "$HUB_CONFIG"
  run get_hub_version
  [ "$status" -eq 0 ]
  [ "$output" = "unknown" ]
}

# ── build_generated_header ─────────────────────────────────────────────────────

@test "build_generated_header : génère header avec version" {
  run build_generated_header
  [ "$status" -eq 0 ]
  [[ "$output" == "<!-- generated by opencode-hub v"* ]]
  [[ "$output" == *"do not edit manually -->" ]]
}

@test "build_generated_header : inclut la version du hub" {
  run build_generated_header
  [ "$status" -eq 0 ]
  [[ "$output" == *"vtest"* ]]
}

# ── extract_frontmatter_value ──────────────────────────────────────────────────

@test "extract_frontmatter_value : extrait id" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run extract_frontmatter_value "$agent_file" "id"
  [ "$status" -eq 0 ]
  [ "$output" = "test-agent-simple" ]
}

@test "extract_frontmatter_value : extrait label" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run extract_frontmatter_value "$agent_file" "label"
  [ "$status" -eq 0 ]
  [ "$output" = "Test Agent Simple" ]
}

@test "extract_frontmatter_value : extrait description" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run extract_frontmatter_value "$agent_file" "description"
  [ "$status" -eq 0 ]
  [ "$output" = "Agent de test minimal" ]
}

@test "extract_frontmatter_value : retourne vide si clé absente" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run extract_frontmatter_value "$agent_file" "nonexistent"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "extract_frontmatter_value : extrait model si présent" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-model.md"
  run extract_frontmatter_value "$agent_file" "model"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-opus-4" ]
}

# ── extract_frontmatter_list ───────────────────────────────────────────────────

@test "extract_frontmatter_list : extrait liste vide" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run extract_frontmatter_list "$agent_file" "skills"
  # La fonction peut retourner 1 si grep ne trouve rien, c'est normal
  [ -z "$output" ]
}

@test "extract_frontmatter_list : extrait liste skills" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-skills.md"
  run extract_frontmatter_list "$agent_file" "skills"
  [ "$status" -eq 0 ]
  # Vérifier que les deux skills sont présentes
  [[ "$output" == *"skill/shared/test-skill-1"* ]]
  [[ "$output" == *"skill/dev/test-skill-2"* ]]
}

# ── read_agent_frontmatter ─────────────────────────────────────────────────────

@test "read_agent_frontmatter : lit frontmatter complet" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  read_agent_frontmatter "$agent_file"
  [ "$_fm_id" = "test-agent-simple" ]
  [ "$_fm_skills" = "[]" ]
  [ -z "$_fm_model" ]
  [ -n "$_fm_raw" ]
}

@test "read_agent_frontmatter : lit model si présent" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-model.md"
  read_agent_frontmatter "$agent_file"
  [ "$_fm_id" = "test-agent-with-model" ]
  [ "$_fm_model" = "claude-opus-4" ]
}

@test "read_agent_frontmatter : parse skills inline" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-skills.md"
  read_agent_frontmatter "$agent_file"
  [ "$_fm_id" = "test-agent-with-skills" ]
  [[ "$_fm_skills" == *"skill/shared/test-skill-1"* ]]
  [[ "$_fm_skills" == *"skill/dev/test-skill-2"* ]]
}

@test "read_agent_frontmatter : capture frontmatter brut" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  read_agent_frontmatter "$agent_file"
  [[ "$_fm_raw" == *"id: test-agent-simple"* ]]
  [[ "$_fm_raw" == *"targets: [opencode]"* ]]
}

# ── _get_model_rank ────────────────────────────────────────────────────────────

@test "_get_model_rank : claude-opus-4 = rang 3" {
  run _get_model_rank "claude-opus-4"
  [ "$status" -eq 0 ]
  [ "$output" = "3" ]
}

@test "_get_model_rank : claude-opus-4-5 = rang 3" {
  run _get_model_rank "claude-opus-4-5"
  [ "$status" -eq 0 ]
  [ "$output" = "3" ]
}

@test "_get_model_rank : claude-sonnet-4-5 = rang 2" {
  run _get_model_rank "claude-sonnet-4-5"
  [ "$status" -eq 0 ]
  [ "$output" = "2" ]
}

@test "_get_model_rank : claude-sonnet-4-6 = rang 0 (non reconnu)" {
  run _get_model_rank "claude-sonnet-4-6"
  [ "$status" -eq 0 ]
  [ "$output" = "0" ]
}

@test "_get_model_rank : claude-haiku-4-5 = rang 1" {
  run _get_model_rank "claude-haiku-4-5"
  [ "$status" -eq 0 ]
  [ "$output" = "1" ]
}

@test "_get_model_rank : modèle inconnu = rang 0" {
  run _get_model_rank "gpt-4"
  [ "$status" -eq 0 ]
  [ "$output" = "0" ]
}

@test "_get_model_rank : gère préfixe provider" {
  run _get_model_rank "anthropic/claude-opus-4"
  [ "$status" -eq 0 ]
  [ "$output" = "3" ]
}

@test "_get_model_rank : gère préfixe bedrock" {
  run _get_model_rank "amazon-bedrock/claude-sonnet-4-5"
  [ "$status" -eq 0 ]
  [ "$output" = "2" ]
}

# ── clamp_model ────────────────────────────────────────────────────────────────

@test "clamp_model : retourne resolved si pas de plancher" {
  run clamp_model "claude-haiku-4-5" "" "test-agent"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-haiku-4-5" ]
}

@test "clamp_model : retourne resolved si >= plancher" {
  run clamp_model "claude-opus-4" "claude-sonnet-4-5" "test-agent"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-opus-4" ]
}

@test "clamp_model : applique plancher si resolved < plancher" {
  mock_log_functions
  run clamp_model "claude-haiku-4-5" "claude-opus-4" "test-agent"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-opus-4" ]
}

@test "clamp_model : sonnet respecte plancher haiku" {
  run clamp_model "claude-sonnet-4-5" "claude-haiku-4-5" "test-agent"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-sonnet-4-5" ]
}

@test "clamp_model : haiku ne respecte pas plancher opus" {
  mock_log_functions
  run clamp_model "claude-haiku-4-5" "claude-opus-4" "test-agent"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-opus-4" ]
}

@test "clamp_model : modèle inconnu respecte pas plancher claude" {
  mock_log_functions
  run clamp_model "gpt-4" "claude-haiku-4-5" "test-agent"
  [ "$status" -eq 0 ]
  [ "$output" = "claude-haiku-4-5" ]
}

# ── _get_agent_family ──────────────────────────────────────────────────────────

@test "_get_agent_family : retourne planning" {
  run _get_agent_family "$TEST_DIR/agents/planning/test-agent.md"
  [ "$status" -eq 0 ]
  [ "$output" = "planning" ]
}

@test "_get_agent_family : retourne dev" {
  run _get_agent_family "$TEST_DIR/agents/dev/developer.md"
  [ "$status" -eq 0 ]
  [ "$output" = "dev" ]
}

@test "_get_agent_family : gère chemin absolu" {
  run _get_agent_family "/absolute/path/agents/ops/devops.md"
  [ "$status" -eq 0 ]
  [ "$output" = "ops" ]
}

# ── resolve_agent_model ────────────────────────────────────────────────────────

@test "resolve_agent_model : utilise hub.model si aucune config" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run resolve_agent_model "$agent_file"
  [ "$status" -eq 0 ]
  # Format de retour : modèle|source
  [[ "$output" == *"claude-sonnet-4-5"* ]]
}

@test "resolve_agent_model : applique plancher depuis frontmatter" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-model.md"
  mock_log_functions
  run resolve_agent_model "$agent_file"
  [ "$status" -eq 0 ]
  # Le modèle hub est sonnet, mais le plancher est opus
  # Format : modèle|source
  [[ "$output" == *"claude-opus-4"* ]]
}

@test "resolve_agent_model : gère agent_models.agents via hub.json" {
  # Créer hub.json avec agent_models.agents
  cat > "$HUB_CONFIG" <<'EOF'
{
  "version": "test",
  "agent_models": {
    "agents": {
      "test-agent-simple": "claude-opus-4"
    }
  },
  "opencode": {
    "model": "claude-sonnet-4-5"
  }
}
EOF
  
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run resolve_agent_model "$agent_file"
  [ "$status" -eq 0 ]
  # Format : modèle|source
  [[ "$output" == *"claude-opus-4"* ]]
  [[ "$output" == *"hub_agent"* ]]
}

@test "resolve_agent_model : gère agent_models.families via hub.json" {
  # Créer un agent dans une famille
  mkdir -p "$TEST_DIR/agents/planning"
  cp "$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md" \
     "$TEST_DIR/agents/planning/test-agent-simple.md"
  
  # Créer hub.json avec agent_models.families
  cat > "$HUB_CONFIG" <<'EOF'
{
  "version": "test",
  "agent_models": {
    "families": {
      "planning": "claude-opus-4"
    }
  },
  "opencode": {
    "model": "claude-sonnet-4-5"
  }
}
EOF
  
  run resolve_agent_model "$TEST_DIR/agents/planning/test-agent-simple.md"
  [ "$status" -eq 0 ]
  # Format : modèle|source
  [[ "$output" == *"claude-opus-4"* ]]
  [[ "$output" == *"hub_family"* ]]
}

@test "resolve_agent_model : projet.model prioritaire sur hub.model" {
  # Créer api-keys.local.md avec modèle projet
  cat > "$API_KEYS_FILE" <<'EOF'
[TEST-PROJ]
model=claude-opus-4
EOF
  
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run resolve_agent_model "$agent_file" "TEST-PROJ"
  [ "$status" -eq 0 ]
  # Format : modèle|source
  [[ "$output" == *"claude-opus-4"* ]]
  [[ "$output" == *"project_global"* ]]
}

@test "resolve_agent_model : projet.agent_models.agents prioritaire" {
  # Créer api-keys.local.md avec agent_models
  cat > "$API_KEYS_FILE" <<'EOF'
[TEST-PROJ]
model=claude-haiku-4-5
agent_models.agents.test-agent-simple=claude-opus-4
EOF
  
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run resolve_agent_model "$agent_file" "TEST-PROJ"
  [ "$status" -eq 0 ]
  # Format : modèle|source
  [[ "$output" == *"claude-opus-4"* ]]
  [[ "$output" == *"project_agent"* ]]
}

# ── extract_permission_json ────────────────────────────────────────────────────

@test "extract_permission_json : retourne vide si pas de permissions" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run extract_permission_json "$agent_file"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "extract_permission_json : extrait permissions présentes" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-permissions.md"
  run extract_permission_json "$agent_file"
  [ "$status" -eq 0 ]
  [[ "$output" == *"websearch"* ]]
  [[ "$output" == *"allow"* ]]
  [[ "$output" == *"webfetch"* ]]
  [[ "$output" == *"deny"* ]]
}

@test "extract_permission_json : génère JSON valide" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-permissions.md"
  result=$(extract_permission_json "$agent_file")
  # Ajouter les accolades pour valider JSON complet
  if command -v jq &>/dev/null && [ -n "$result" ]; then
    run jq empty <<< "{$result}"
    [ "$status" -eq 0 ]
  fi
}

# ── strip_frontmatter ──────────────────────────────────────────────────────────

@test "strip_frontmatter : supprime frontmatter YAML" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  result=$(strip_frontmatter "$agent_file")
  # Ne doit pas contenir les lignes frontmatter
  [[ ! "$result" == *"---"* ]]
  [[ ! "$result" == *"id:"* ]]
  # Doit contenir le corps
  [[ "$result" == *"Test Agent Simple"* ]]
}

@test "strip_frontmatter : préserve contenu après frontmatter" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-skills.md"
  result=$(strip_frontmatter "$agent_file")
  [[ "$result" == *"Test Agent With Skills"* ]]
  [[ "$result" == *"avec des skills injectées"* ]]
}

@test "strip_frontmatter : gère fichier sans frontmatter" {
  # Créer un fichier sans frontmatter
  echo "# Simple file" > "$TEST_DIR/no-frontmatter.md"
  echo "Content here" >> "$TEST_DIR/no-frontmatter.md"
  result=$(strip_frontmatter "$TEST_DIR/no-frontmatter.md")
  [[ "$result" == *"Simple file"* ]]
  [[ "$result" == *"Content here"* ]]
}

# ── get_agent_mode ─────────────────────────────────────────────────────────────

@test "get_agent_mode : retourne primary par défaut" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run get_agent_mode "$agent_file"
  [ "$status" -eq 0 ]
  [ "$output" = "primary" ]
}

@test "get_agent_mode : extrait mode depuis frontmatter" {
  # Créer un agent avec mode subagent
  cat > "$TEST_DIR/agent-subagent.md" <<'AGENT'
---
id: test-subagent
mode: subagent
---
# Test Subagent
AGENT
  run get_agent_mode "$TEST_DIR/agent-subagent.md"
  [ "$status" -eq 0 ]
  [ "$output" = "subagent" ]
}

@test "get_agent_mode : gère mode all" {
  cat > "$TEST_DIR/agent-all.md" <<'AGENT'
---
id: test-all
mode: all
---
# Test All Mode
AGENT
  run get_agent_mode "$TEST_DIR/agent-all.md"
  [ "$status" -eq 0 ]
  [ "$output" = "all" ]
}

# ── get_agent_id ───────────────────────────────────────────────────────────────

@test "get_agent_id : extrait id depuis frontmatter" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  run get_agent_id "$agent_file"
  [ "$status" -eq 0 ]
  [ "$output" = "test-agent-simple" ]
}

@test "get_agent_id : utilise nom fichier si pas d'id" {
  # Créer un agent sans id dans frontmatter
  cat > "$TEST_DIR/my-agent.md" <<'AGENT'
---
label: My Agent
---
# My Agent
AGENT
  run get_agent_id "$TEST_DIR/my-agent.md"
  [ "$status" -eq 0 ]
  [ "$output" = "my-agent" ]
}

@test "get_agent_id : gère fichiers avec chemin complet" {
  mkdir -p "$TEST_DIR/agents/planning"
  cp "$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md" \
     "$TEST_DIR/agents/planning/orchestrator.md"
  # Modifier l'id dans le fichier copié
  sed -i.bak 's/id: test-agent-simple/id: orchestrator/' \
     "$TEST_DIR/agents/planning/orchestrator.md"
  run get_agent_id "$TEST_DIR/agents/planning/orchestrator.md"
  [ "$status" -eq 0 ]
  [ "$output" = "orchestrator" ]
}

# ── build_agent_content ────────────────────────────────────────────────────────

@test "build_agent_content : génère contenu agent simple" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  result=$(build_agent_content "$agent_file")
  # Doit contenir le header généré
  [[ "$result" == *"generated by opencode-hub"* ]]
  # Doit contenir le contenu du corps
  [[ "$result" == *"Test Agent Simple"* ]]
  # Ne doit pas contenir le frontmatter
  [[ ! "$result" == *"id: test-agent-simple"* ]]
}

@test "build_agent_content : injecte langue de travail" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  result=$(build_agent_content "$agent_file" "français")
  [[ "$result" == *"Langue de travail : français"* ]]
}

@test "build_agent_content : injecte skills déclarés" {
  # Créer les skills de test
  mkdir -p "$TEST_DIR/skills/skill/shared"
  mkdir -p "$TEST_DIR/skills/skill/dev"
  cat > "$TEST_DIR/skills/skill/shared/test-skill-1.md" <<'SKILL'
---
id: test-skill-1
---
# Test Skill 1
This is a test skill.
SKILL

  cat > "$TEST_DIR/skills/skill/dev/test-skill-2.md" <<'SKILL'
---
id: test-skill-2
---
# Test Skill 2
This is another test skill.
SKILL

  export SKILLS_DIR="$TEST_DIR/skills"
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-with-skills.md"
  result=$(build_agent_content "$agent_file")
  # Devrait contenir le contenu des skills
  [[ "$result" == *"Test Skill 1"* ]]
  [[ "$result" == *"This is a test skill"* ]]
}

@test "build_agent_content : gère agent sans skills" {
  local agent_file="$BATS_TEST_DIRNAME/fixtures/prompts/agent-simple.md"
  result=$(build_agent_content "$agent_file")
  [ "$?" -eq 0 ]
  [[ "$result" == *"Test Agent Simple"* ]]
}

@test "build_agent_content : échoue si fichier inexistant" {
  mock_log_functions
  run build_agent_content "$TEST_DIR/nonexistent-agent.md"
  [ "$status" -ne 0 ]
}

# ── detect_stack ───────────────────────────────────────────────────────────────

@test "detect_stack [SKIP] : détecte TypeScript avec package.json" {
  mkdir -p "$TEST_DIR/project-ts"
  cat > "$TEST_DIR/project-ts/package.json" <<'PKG'
{
  "dependencies": {
    "typescript": "^5.0.0",
    "react": "^18.0.0"
  }
}
PKG
  result=$(detect_stack "$TEST_DIR/project-ts")
  [[ "$result" == *"typescript"* ]]
}

@test "detect_stack [SKIP] : détecte Python avec requirements.txt" {
  mkdir -p "$TEST_DIR/project-py"
  cat > "$TEST_DIR/project-py/requirements.txt" <<'REQ'
django>=4.0
pandas>=2.0
REQ
  result=$(detect_stack "$TEST_DIR/project-py")
  # Note : detect_stack détecte les frameworks, pas juste les packages
  # Vérifions au moins qu'il ne crash pas
  [ "$?" -eq 0 ]
}

@test "detect_stack [SKIP] : retourne vide si pas de fichiers de dépendances" {
  mkdir -p "$TEST_DIR/project-empty"
  result=$(detect_stack "$TEST_DIR/project-empty")
  # Devrait retourner vide ou avec code 0
  [ "$?" -eq 0 ]
}

@test "detect_stack [SKIP] : gère répertoire inexistant" {
  run detect_stack "$TEST_DIR/nonexistent-project"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# ── build_dev_bootstrap_prompt ─────────────────────────────────────────────────

@test "build_dev_bootstrap [SKIP]_prompt : génère prompt sans tickets" {
  mkdir -p "$TEST_DIR/project-beads"
  # Mock bd pour retourner []
  mock_bd "[]"
  result=$(build_dev_bootstrap_prompt "$TEST_DIR/project-beads")
  [[ "$result" == *"Aucun ticket"* ]]
  [[ "$result" == *"ai-delegated"* ]]
}

@test "build_dev_bootstrap [SKIP]_prompt : génère prompt avec tickets" {
  mkdir -p "$TEST_DIR/project-beads"
  # Mock bd pour retourner des tickets
  mock_bd '[{"id":"BD-1","title":"Fix bug"}]'
  result=$(build_dev_bootstrap_prompt "$TEST_DIR/project-beads")
  [[ "$result" == *"BD-1"* ]]
  [[ "$result" == *"Fix bug"* ]]
  [[ "$result" == *"Workflow obligatoire"* ]]
}

@test "build_dev_bootstrap [SKIP]_prompt : gère label custom" {
  mkdir -p "$TEST_DIR/project-beads"
  mock_bd "[]"
  result=$(build_dev_bootstrap_prompt "$TEST_DIR/project-beads" "custom-label")
  [[ "$result" == *"custom-label"* ]]
}

@test "build_dev_bootstrap [SKIP]_prompt : gère assignee" {
  mkdir -p "$TEST_DIR/project-beads"
  mock_bd "[]"
  result=$(build_dev_bootstrap_prompt "$TEST_DIR/project-beads" "ai-delegated" "john@example.com")
  [[ "$result" == *"john@example.com"* ]]
}
