#!/usr/bin/env bats
# Tests unitaires pour scripts/lib/agent-discovery.sh
# Fonctions testées : is_hub_generated_agent, discover_project_agents,
#                     resolve_agent_similarity, get_discovery_agent_id

load helpers

setup() {
  common_setup

  source "$BATS_TEST_DIRNAME/../scripts/common.sh"
  PROJECTS_FILE="$TEST_DIR/projects.md"
  API_KEYS_FILE="$TEST_DIR/api-keys.local.md"
  PATHS_FILE="$TEST_DIR/paths.local.md"

  export HUB_DIR="$BATS_TEST_DIRNAME/.."
  export AGENT_ALIASES_FILE="$HUB_DIR/config/agent-aliases.json"

  source "$HUB_DIR/scripts/lib/agent-discovery.sh"

  # Créer un répertoire .opencode/agents de test
  mkdir -p "$TEST_DIR/project/.opencode/agents"
}

teardown() {
  common_teardown
}

# ── is_hub_generated_agent ────────────────────────────────────────────────────

@test "is_hub_generated_agent : détecte le marker hub dans le fichier" {
  cat > "$TEST_DIR/project/.opencode/agents/generated.md" <<'EOF'
<!-- generated by openhub v1.0.0 -->
# Agent généré
Corps de l'agent.
EOF
  run is_hub_generated_agent "$TEST_DIR/project/.opencode/agents/generated.md"
  [ "$status" -eq 0 ]
}

@test "is_hub_generated_agent : retourne faux si marker absent" {
  cat > "$TEST_DIR/project/.opencode/agents/manual.md" <<'EOF'
---
id: my-planner
label: MyPlanner
---
# Mon Planner
Corps de l'agent manuel.
EOF
  run is_hub_generated_agent "$TEST_DIR/project/.opencode/agents/manual.md"
  [ "$status" -ne 0 ]
}

@test "is_hub_generated_agent : retourne faux si fichier absent" {
  run is_hub_generated_agent "/chemin/inexistant/agent.md"
  [ "$status" -ne 0 ]
}

@test "is_hub_generated_agent : ne détecte pas un marker en milieu de fichier" {
  cat > "$TEST_DIR/project/.opencode/agents/mid-marker.md" <<'EOF'
---
id: mid-marker
---
# Agent

Quelques lignes de contenu.
Plus de contenu.
<!-- generated by openhub v1.0.0 -->
Encore du contenu.
EOF
  # Le marker est à la ligne 8, pas dans les 5 premières → doit retourner faux
  run is_hub_generated_agent "$TEST_DIR/project/.opencode/agents/mid-marker.md"
  [ "$status" -ne 0 ]
}

# ── discover_project_agents ───────────────────────────────────────────────────

@test "discover_project_agents : retourne vide si .opencode/agents/ absent" {
  run discover_project_agents "$TEST_DIR/project-sans-agents"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "discover_project_agents : retourne vide si tous les agents sont générés par le hub" {
  cat > "$TEST_DIR/project/.opencode/agents/hub-agent.md" <<'EOF'
<!-- generated by openhub v1.0.0 -->
# Agent hub
Corps.
EOF
  run discover_project_agents "$TEST_DIR/project"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "discover_project_agents : retourne les agents non générés par le hub" {
  cat > "$TEST_DIR/project/.opencode/agents/manual-planner.md" <<'EOF'
---
id: planner
label: MyPlanner
---
# Mon Planner
EOF
  run discover_project_agents "$TEST_DIR/project"
  [ "$status" -eq 0 ]
  [[ "$output" == *"manual-planner.md"* ]]
}

@test "discover_project_agents : ignore les agents hub et retourne uniquement les manuels" {
  # Agent généré par le hub
  cat > "$TEST_DIR/project/.opencode/agents/hub-planner.md" <<'EOF'
<!-- generated by openhub v1.0.0 -->
# Planner hub
EOF
  # Agent manuel
  cat > "$TEST_DIR/project/.opencode/agents/my-dev.md" <<'EOF'
---
id: my-dev
---
# Mon Dev
EOF
  run discover_project_agents "$TEST_DIR/project"
  [ "$status" -eq 0 ]
  [[ "$output" == *"my-dev.md"* ]]
  [[ "$output" != *"hub-planner.md"* ]]
}

@test "discover_project_agents : fonctionne avec plusieurs agents manuels" {
  for name in alpha beta gamma; do
    cat > "$TEST_DIR/project/.opencode/agents/${name}.md" <<EOF
---
id: $name
---
# Agent $name
EOF
  done
  run discover_project_agents "$TEST_DIR/project"
  [ "$status" -eq 0 ]
  [ "$(echo "$output" | wc -l | tr -d ' ')" -eq 3 ]
}

# ── resolve_agent_similarity ─────────────────────────────────────────────────

@test "resolve_agent_similarity : match exact de l'ID hub (planner)" {
  run resolve_agent_similarity "planner"
  [ "$status" -eq 0 ]
  [ "$output" = "planner" ]
}

@test "resolve_agent_similarity : match exact de l'ID hub (reviewer)" {
  run resolve_agent_similarity "reviewer"
  [ "$status" -eq 0 ]
  [ "$output" = "reviewer" ]
}

@test "resolve_agent_similarity : match exact de l'ID hub (orchestrator)" {
  run resolve_agent_similarity "orchestrator"
  [ "$status" -eq 0 ]
  [ "$output" = "orchestrator" ]
}

@test "resolve_agent_similarity : match via alias (plan → planner)" {
  run resolve_agent_similarity "plan"
  [ "$status" -eq 0 ]
  [ "$output" = "planner" ]
}

@test "resolve_agent_similarity : match via alias (frontend → developer-frontend)" {
  run resolve_agent_similarity "frontend"
  [ "$status" -eq 0 ]
  [ "$output" = "developer-frontend" ]
}

@test "resolve_agent_similarity : match via alias (qa → qa-engineer)" {
  run resolve_agent_similarity "qa"
  [ "$status" -eq 0 ]
  [ "$output" = "qa-engineer" ]
}

@test "resolve_agent_similarity : match via alias (docs → documentarian)" {
  run resolve_agent_similarity "docs"
  [ "$status" -eq 0 ]
  [ "$output" = "documentarian" ]
}

@test "resolve_agent_similarity : normalisation majuscules (PLANNER → planner)" {
  run resolve_agent_similarity "PLANNER"
  [ "$status" -eq 0 ]
  [ "$output" = "planner" ]
}

@test "resolve_agent_similarity : normalisation underscore (my_planner → planner via alias)" {
  # "my_planner" → normalise en "my-planner" → strip "my-" → "planner" → match
  run resolve_agent_similarity "my_planner"
  [ "$status" -eq 0 ]
  [ "$output" = "planner" ]
}

@test "resolve_agent_similarity : retourne vide si aucun match" {
  run resolve_agent_similarity "agent-xyz-inconnu-12345"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : retourne vide pour ID vide" {
  run resolve_agent_similarity ""
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : match via alias (explorer → pathfinder)" {
  run resolve_agent_similarity "explorer"
  [ "$status" -eq 0 ]
  [ "$output" = "pathfinder" ]
}

@test "resolve_agent_similarity : match via alias (coordinator → orchestrator)" {
  run resolve_agent_similarity "coordinator"
  [ "$status" -eq 0 ]
  [ "$output" = "orchestrator" ]
}

@test "resolve_agent_similarity : match exact de l'ID hub (auditor)" {
  run resolve_agent_similarity "auditor"
  [ "$status" -eq 0 ]
  [ "$output" = "auditor" ]
}

@test "resolve_agent_similarity : match exact de l'ID hub (auditor-subagent)" {
  run resolve_agent_similarity "auditor-subagent"
  [ "$status" -eq 0 ]
  [ "$output" = "auditor-subagent" ]
}

@test "resolve_agent_similarity : auditor-security ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-security"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : auditor-architecture ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-architecture"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : auditor-performance ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-performance"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : auditor-accessibility ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-accessibility"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : auditor-privacy ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-privacy"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : auditor-ecodesign ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-ecodesign"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_agent_similarity : auditor-observability ne matche plus (agent supprimé — ADR-017)" {
  run resolve_agent_similarity "auditor-observability"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# ── get_discovery_agent_id ────────────────────────────────────────────────────

@test "get_discovery_agent_id : lit le champ id: du frontmatter" {
  cat > "$TEST_DIR/project/.opencode/agents/my-agent.md" <<'EOF'
---
id: my-planner
label: MyPlanner
---
# Mon Planner
EOF
  run get_discovery_agent_id "$TEST_DIR/project/.opencode/agents/my-agent.md"
  [ "$status" -eq 0 ]
  [ "$output" = "my-planner" ]
}

@test "get_discovery_agent_id : fallback sur le basename si id: absent" {
  cat > "$TEST_DIR/project/.opencode/agents/custom-reviewer.md" <<'EOF'
# Revieweur custom
Corps.
EOF
  run get_discovery_agent_id "$TEST_DIR/project/.opencode/agents/custom-reviewer.md"
  [ "$status" -eq 0 ]
  [ "$output" = "custom-reviewer" ]
}

@test "get_discovery_agent_id : normalise les majuscules" {
  cat > "$TEST_DIR/project/.opencode/agents/agent-up.md" <<'EOF'
---
id: MyCustomAgent
---
# Agent
EOF
  run get_discovery_agent_id "$TEST_DIR/project/.opencode/agents/agent-up.md"
  [ "$status" -eq 0 ]
  [ "$output" = "mycustomagent" ]
}
