#!/usr/bin/env bats
# Tests unitaires pour scripts/lib/prompt-builder.sh
# Fonctions testées : extract_frontmatter_value, extract_frontmatter_list,
#                     strip_frontmatter, agent_supports_target, get_agent_id,
#                     build_agent_content, detect_stack, resolve_stack_skills

setup() {
  TEST_DIR="$(mktemp -d)"

  # Sourcer dans l'ordre — common.sh recalcule HUB_DIR depuis BASH_SOURCE
  source "$BATS_TEST_DIRNAME/../scripts/common.sh"
  source "$BATS_TEST_DIRNAME/../scripts/lib/prompt-builder.sh"

  # Surcharger les variables après le source
  SKILLS_DIR="$TEST_DIR/skills"
  CANONICAL_AGENTS_DIR="$TEST_DIR/agents"

  # Mocker get_hub_version — pas de config/hub.json nécessaire
  get_hub_version() { echo "test"; }

  # Créer un agent minimal utilisé par les tests build_agent_content
  mkdir -p "$TEST_DIR/agents"
  mkdir -p "$TEST_DIR/skills/developer"

  cat > "$TEST_DIR/agents/test-agent.md" <<'AGENTEOF'
---
id: test-agent
label: TestAgent
description: Agent de test minimal
targets: [opencode, claude-code]
skills: [developer/test-skill]
---

# TestAgent

Corps de l'agent de test.
AGENTEOF

  cat > "$TEST_DIR/skills/developer/test-skill.md" <<'SKILLEOF'
---
name: test-skill
description: Skill de test minimal
---

# Skill de test

Contenu du skill de test.
SKILLEOF
}

teardown() {
  rm -rf "$TEST_DIR"
}

# ── extract_frontmatter_value ─────────────────────────────────────────────────

@test "extract_frontmatter_value : lit correctement le champ id" {
  run extract_frontmatter_value "$TEST_DIR/agents/test-agent.md" "id"
  [ "$status" -eq 0 ]
  [ "$output" = "test-agent" ]
}

@test "extract_frontmatter_value : lit correctement le champ label" {
  run extract_frontmatter_value "$TEST_DIR/agents/test-agent.md" "label"
  [ "$status" -eq 0 ]
  [ "$output" = "TestAgent" ]
}

# ── extract_frontmatter_list ──────────────────────────────────────────────────

@test "extract_frontmatter_list : parse une liste inline [a, b, c] en 3 lignes" {
  local tmp_file="$TEST_DIR/list-agent.md"
  cat > "$tmp_file" <<'EOF'
---
id: list-agent
skills: [developer/skill-a, developer/skill-b, developer/skill-c]
targets: [opencode]
---
EOF
  run extract_frontmatter_list "$tmp_file" "skills"
  [ "$status" -eq 0 ]
  [ "$(echo "$output" | wc -l | tr -d ' ')" -eq 3 ]
  echo "$output" | grep -q "developer/skill-a"
  echo "$output" | grep -q "developer/skill-b"
  echo "$output" | grep -q "developer/skill-c"
}

# ── strip_frontmatter ─────────────────────────────────────────────────────────

@test "strip_frontmatter : supprime le bloc frontmatter et retourne le corps" {
  run strip_frontmatter "$TEST_DIR/agents/test-agent.md"
  [ "$status" -eq 0 ]
  # Le corps doit être présent
  echo "$output" | grep -q "# TestAgent"
  # Le frontmatter ne doit pas être présent
  ! echo "$output" | grep -q "^id:"
  ! echo "$output" | grep -q "^---"
}

# ── agent_supports_target ─────────────────────────────────────────────────────

@test "agent_supports_target : retourne 0 pour une cible supportée (opencode)" {
  run agent_supports_target "$TEST_DIR/agents/test-agent.md" "opencode"
  [ "$status" -eq 0 ]
}

# ── get_agent_id ──────────────────────────────────────────────────────────────

@test "get_agent_id : retourne la valeur du champ id du frontmatter" {
  run get_agent_id "$TEST_DIR/agents/test-agent.md"
  [ "$status" -eq 0 ]
  [ "$output" = "test-agent" ]
}

# ── build_agent_content ───────────────────────────────────────────────────────

@test "build_agent_content : sans langue — pas d'instruction de langue dans l'output" {
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode"
  [ "$status" -eq 0 ]
  ! echo "$output" | grep -q "Langue de travail"
}

@test "build_agent_content : avec lang=english — instruction de langue présente" {
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode" "english"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Langue de travail : english"
}

@test "build_agent_content : le header généré est présent" {
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "<!-- generated by opencode-hub vtest"
}

@test "build_agent_content : agent inexistant — retourne exit non-zero" {
  run build_agent_content "$TEST_DIR/agents/inexistant.md" "opencode"
  [ "$status" -ne 0 ]
}

# ── build_dev_bootstrap_prompt ────────────────────────────────────────────────

@test "build_dev_bootstrap_prompt : JSON array valide — prompt avec tickets" {
  # Mocker bd pour retourner un JSON array valide
  bd() { echo '[{"id":"T-1","title":"Fix bug","status":"ready"}]'; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "tickets délégués"
  echo "$output" | grep -q "T-1"
}

@test "build_dev_bootstrap_prompt : sortie non-JSON — fallback prompt sans tickets" {
  # Mocker bd pour retourner du texte d'erreur (pas un JSON array)
  bd() { echo "Error: database not found"; return 1; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Aucun ticket"
}

@test "build_dev_bootstrap_prompt : sortie vide — fallback prompt sans tickets" {
  # Mocker bd pour retourner une chaîne vide
  bd() { echo ""; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Aucun ticket"
}

# ── Intégrité skills ↔ agents ─────────────────────────────────────────────────

@test "intégrité : chaque skill référencé dans un agent existe sur le disque" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local real_skills_dir="$hub_dir/skills"
  local real_agents_dir="$hub_dir/agents"
  local missing=""

  for agent_file in "$real_agents_dir"/*/*.md; do
    local agent_id
    agent_id=$(basename "$agent_file" .md)

    # Extraire la liste de skills du frontmatter
    local skills_line
    skills_line=$(awk '/^---$/{n++; next} n==1 && /^skills:/' "$agent_file")
    [ -z "$skills_line" ] && continue

    # Parser la liste [a, b, c]
    local skills_csv
    skills_csv=$(echo "$skills_line" | sed 's/^skills: *\[//;s/\] *$//')
    local IFS=','
    for skill in $skills_csv; do
      skill=$(echo "$skill" | sed 's/^ *//;s/ *$//')
      local skill_file="$real_skills_dir/${skill}.md"
      if [ ! -f "$skill_file" ]; then
        missing="${missing}  ${agent_id} → ${skill}\n"
      fi
    done
  done

  if [ -n "$missing" ]; then
    echo -e "Skills manquants :\n${missing}"
    return 1
  fi
}

# ── Cohérence data model dans les skills ──────────────────────────────────────

@test "data model : aucun skill n'utilise --priority high/medium/low (forme invalide)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for skill_file in "$hub_dir"/skills/*/*.md; do
    if grep -n -- '--priority \(high\|medium\|low\)' "$skill_file" 2>/dev/null; then
      violations="${violations}  $(basename "$skill_file")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Skills utilisant --priority string (invalide) :\n${violations}"
    return 1
  fi
}

@test "data model : aucun skill n'utilise -t decision (type supprimé)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for skill_file in "$hub_dir"/skills/*/*.md; do
    if grep -n -- '-t decision' "$skill_file" 2>/dev/null; then
      violations="${violations}  $(basename "$skill_file")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Skills utilisant -t decision (type supprimé) :\n${violations}"
    return 1
  fi
}

@test "data model : aucun skill, script ou agent n'utilise bd list --ready (utiliser bd ready)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for f in "$hub_dir"/skills/*/*.md "$hub_dir"/scripts/*.sh "$hub_dir"/scripts/lib/*.sh "$hub_dir"/agents/*/*.md; do
    [ -f "$f" ] || continue
    if grep -n 'bd list --ready' "$f" 2>/dev/null; then
      violations="${violations}  $(basename "$f")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Fichiers utilisant bd list --ready (utiliser bd ready) :\n${violations}"
    return 1
  fi
}

@test "data model : aucun skill n'utilise -p 4 (priorité P4 supprimée)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for skill_file in "$hub_dir"/skills/*/*.md; do
    if grep -n -- '-p 4' "$skill_file" 2>/dev/null; then
      violations="${violations}  $(basename "$skill_file")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Skills utilisant -p 4 (P4 supprimée) :\n${violations}"
    return 1
  fi
}

@test "data model : build_dev_bootstrap_prompt inclut l'étape review dans le workflow" {
  bd() { echo '[{"id":"T-1","title":"Test ticket","status":"ready"}]'; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "review"
}

# ── build_review_bootstrap_prompt ─────────────────────────────────────────────

@test "build_review_bootstrap_prompt : contient la branche reviewée" {
  # Mocker git pour retourner un diff minimal
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ une ligne ajoutée"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "feature/my-branch"
}

@test "build_review_bootstrap_prompt : contient le diff injecté" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ ligne ajoutée dans le diff"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "ligne ajoutée dans le diff"
}

@test "build_review_bootstrap_prompt : contient les instructions de workflow" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Workflow"
}

@test "build_review_bootstrap_prompt : contient le projet et le chemin" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "TEST-PROJ"
}

@test "build_review_bootstrap_prompt : mentionne CONVENTIONS.md si le fichier existe" {
  touch "$TEST_DIR/CONVENTIONS.md"
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "CONVENTIONS.md"
  rm -f "$TEST_DIR/CONVENTIONS.md"
}

@test "build_review_bootstrap_prompt : ne mentionne pas l'hint CONVENTIONS.md si absent" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  # L'hint contextuel "→ Lire CONVENTIONS.md" ne doit pas apparaître si le fichier est absent
  ! echo "$output" | grep -q "→ Lire CONVENTIONS.md"
}

@test "build_review_bootstrap_prompt : diff vide → message explicite" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo ""
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "aucune différence"
}

# ── Intégrité des règles orchestrateur ────────────────────────────────────────

@test "orchestrator : bash, edit et write sont bien à deny dans le frontmatter" {
  local agent_file="$BATS_TEST_DIRNAME/../agents/planning/orchestrator.md"
  grep -q 'bash: deny' "$agent_file"
  grep -q 'edit: deny' "$agent_file"
  grep -q 'write: deny' "$agent_file"
}

@test "orchestrator : task deny par défaut avec allowlist explicite" {
  local agent_file="$BATS_TEST_DIRNAME/../agents/planning/orchestrator.md"
  grep -q '"*": deny' "$agent_file"
  grep -q '"planner": allow' "$agent_file"
  grep -q '"orchestrator-dev": allow' "$agent_file"
  grep -q '"debugger": allow' "$agent_file"
}

@test "orchestrator protocol : section 'Agent requis non disponible' présente" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'Agent requis non disponible' "$skill_file"
}

@test "orchestrator protocol : table de substitution complète (7 auditor-*)" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'auditor-security' "$skill_file"
  grep -q 'auditor-accessibility' "$skill_file"
  grep -q 'auditor-architecture' "$skill_file"
  grep -q 'auditor-performance' "$skill_file"
  grep -q 'auditor-privacy' "$skill_file"
  grep -q 'auditor-ecodesign' "$skill_file"
  grep -q 'auditor-observability' "$skill_file"
}

@test "orchestrator protocol : instruction de déploiement sans quitter OpenCode présente" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'oc deploy opencode' "$skill_file"
}

@test "orchestrator protocol : Mode C conditionné à l'absence des fichiers de contexte" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'ONBOARDING.md' "$skill_file"
  grep -q 'CONVENTIONS.md' "$skill_file"
}

@test "tool-question skill : règle de contexte pour les sous-agents présente" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/posture/tool-question.md"
  grep -q 'sous-agent' "$skill_file"
  grep -q 'bloc de contexte' "$skill_file"
}

@test "orchestrator protocol : CP-0 sépare l'affichage du tableau et l'outil question" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'Afficher dans le texte de la discussion' "$skill_file"
  grep -q 'Demander le mode via l.*outil.*question' "$skill_file"
}

# ── Intégrité release.sh ──────────────────────────────────────────────────────

@test "release.sh : met à jour CHANGELOG.md lors d'une release" {
  local release_script="$BATS_TEST_DIRNAME/../scripts/release.sh"
  grep -q 'CHANGELOG' "$release_script"
  grep -q 'Unreleased' "$release_script"
  grep -q 'perl' "$release_script"
}

@test "release.sh : ajoute CHANGELOG.md au commit de release" {
  local release_script="$BATS_TEST_DIRNAME/../scripts/release.sh"
  grep -q 'git.*add.*CHANGELOG' "$release_script"
}

@test "CHANGELOG : contient les versions 1.1.0, 1.2.0 et 1.3.0 versionnées" {
  local changelog="$BATS_TEST_DIRNAME/../CHANGELOG.md"
  grep -q '## \[1\.1\.0\]' "$changelog"
  grep -q '## \[1\.2\.0\]' "$changelog"
  grep -q '## \[1\.3\.0\]' "$changelog"
}

@test "CHANGELOG : section [Unreleased] présente et en tête de fichier" {
  local changelog="$BATS_TEST_DIRNAME/../CHANGELOG.md"
  grep -q '## \[Unreleased\]' "$changelog"
  # [Unreleased] doit apparaître avant [1.3.0]
  local line_unreleased line_v13
  line_unreleased=$(grep -n '## \[Unreleased\]' "$changelog" | head -1 | cut -d: -f1)
  line_v13=$(grep -n '## \[1\.3\.0\]' "$changelog" | head -1 | cut -d: -f1)
  [ "$line_unreleased" -lt "$line_v13" ]
}

# ── detect_stack ──────────────────────────────────────────────────────────────

@test "detect_stack : retourne vide si le répertoire n'existe pas" {
  run detect_stack "/chemin/qui/nexiste/pas"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "detect_stack : retourne vide si project_path est vide" {
  run detect_stack ""
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "detect_stack : détecte typescript depuis package.json dependencies" {
  local proj="$TEST_DIR/proj-ts"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "typescript": "^5.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "typescript"
}

@test "detect_stack : détecte typescript depuis package.json devDependencies" {
  local proj="$TEST_DIR/proj-ts-dev"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "devDependencies": { "typescript": "^5.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "typescript"
}

@test "detect_stack : détecte vue sans nuxt" {
  local proj="$TEST_DIR/proj-vue"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "vue": "^3.4.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "^vue$"
  ! echo "$output" | grep -q "^nuxt$"
}

@test "detect_stack : détecte nuxt ET vue quand nuxt est présent" {
  local proj="$TEST_DIR/proj-nuxt"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "nuxt": "^3.10.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "nuxt"
  echo "$output" | grep -q "vue"
}

@test "detect_stack : détecte react sans next" {
  local proj="$TEST_DIR/proj-react"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "react": "^18.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "^react$"
  ! echo "$output" | grep -q "^next$"
}

@test "detect_stack : détecte next ET react quand next est présent" {
  local proj="$TEST_DIR/proj-next"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "next": "^14.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "next"
  echo "$output" | grep -q "react"
}

@test "detect_stack : détecte nestjs depuis @nestjs/core" {
  local proj="$TEST_DIR/proj-nest"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "@nestjs/core": "^10.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "nestjs"
}

@test "detect_stack : détecte prisma depuis @prisma/client" {
  local proj="$TEST_DIR/proj-prisma"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "@prisma/client": "^5.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "prisma"
}

@test "detect_stack : détecte vitest depuis devDependencies" {
  local proj="$TEST_DIR/proj-vitest"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "devDependencies": { "vitest": "^1.0.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "vitest"
}

@test "detect_stack : détecte playwright depuis @playwright/test" {
  local proj="$TEST_DIR/proj-playwright"
  mkdir -p "$proj"
  cat > "$proj/package.json" <<'EOF'
{ "devDependencies": { "@playwright/test": "^1.40.0" } }
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "playwright"
}

@test "detect_stack : détecte python depuis pyproject.toml" {
  local proj="$TEST_DIR/proj-py"
  mkdir -p "$proj"
  echo '[tool.poetry]' > "$proj/pyproject.toml"
  run detect_stack "$proj"
  echo "$output" | grep -q "python"
}

@test "detect_stack : détecte django depuis requirements.txt" {
  local proj="$TEST_DIR/proj-django"
  mkdir -p "$proj"
  echo 'Django==4.2.0' > "$proj/requirements.txt"
  run detect_stack "$proj"
  echo "$output" | grep -q "python"
  echo "$output" | grep -q "django"
}

@test "detect_stack : détecte fastapi depuis requirements.txt" {
  local proj="$TEST_DIR/proj-fastapi"
  mkdir -p "$proj"
  echo 'fastapi==0.110.0' > "$proj/requirements.txt"
  run detect_stack "$proj"
  echo "$output" | grep -q "fastapi"
}

@test "detect_stack : détecte docker depuis Dockerfile" {
  local proj="$TEST_DIR/proj-docker"
  mkdir -p "$proj"
  touch "$proj/Dockerfile"
  run detect_stack "$proj"
  echo "$output" | grep -q "docker"
}

@test "detect_stack : détecte github-actions depuis .github/workflows/" {
  local proj="$TEST_DIR/proj-gha"
  mkdir -p "$proj/.github/workflows"
  touch "$proj/.github/workflows/ci.yml"
  run detect_stack "$proj"
  echo "$output" | grep -q "github-actions"
}

@test "detect_stack : détecte terraform depuis fichiers *.tf" {
  local proj="$TEST_DIR/proj-tf"
  mkdir -p "$proj/infra"
  touch "$proj/infra/main.tf"
  run detect_stack "$proj"
  echo "$output" | grep -q "terraform"
}

@test "detect_stack : ne produit pas de doublons (docker via package.json et Dockerfile)" {
  local proj="$TEST_DIR/proj-nodup"
  mkdir -p "$proj"
  touch "$proj/Dockerfile"
  cat > "$proj/package.json" <<'EOF'
{ "dependencies": { "react": "^18.0.0" } }
EOF
  run detect_stack "$proj"
  local docker_count
  docker_count=$(echo "$output" | grep -c "^docker$" || true)
  [ "$docker_count" -le 1 ]
}

@test "detect_stack : détecte plusieurs stacks sur un projet complet" {
  local proj="$TEST_DIR/proj-full"
  mkdir -p "$proj/.github/workflows"
  touch "$proj/Dockerfile"
  touch "$proj/.github/workflows/ci.yml"
  cat > "$proj/package.json" <<'EOF'
{
  "dependencies": { "next": "^14.0.0", "@prisma/client": "^5.0.0" },
  "devDependencies": { "typescript": "^5.0.0", "vitest": "^1.0.0" }
}
EOF
  run detect_stack "$proj"
  echo "$output" | grep -q "typescript"
  echo "$output" | grep -q "next"
  echo "$output" | grep -q "react"
  echo "$output" | grep -q "prisma"
  echo "$output" | grep -q "vitest"
  echo "$output" | grep -q "docker"
  echo "$output" | grep -q "github-actions"
}

# ── resolve_stack_skills ──────────────────────────────────────────────────────

_make_stack_config() {
  local config_file="$1"
  cat > "$config_file" <<'EOF'
{
  "language": {
    "typescript": ["developer/stacks/dev-standards-typescript"]
  },
  "frontend": {
    "vue":   ["developer/stacks/dev-standards-vuejs"],
    "react": ["developer/stacks/dev-standards-react"],
    "next":  ["developer/stacks/dev-standards-react", "developer/stacks/dev-standards-nextjs"]
  },
  "backend": {
    "nestjs": ["developer/stacks/dev-standards-nestjs"]
  },
  "test": {
    "vitest": ["developer/stacks/dev-standards-vitest"]
  },
  "_agent_scope": {
    "developer-frontend": ["language", "frontend", "test"],
    "developer-backend":  ["language", "backend", "test"],
    "developer-fullstack": ["language", "frontend", "backend", "test"]
  }
}
EOF
}

@test "resolve_stack_skills : retourne vide si stacks_list est vide" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-frontend" "" "$cfg"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_stack_skills : retourne vide si le fichier config n'existe pas" {
  run resolve_stack_skills "developer-frontend" "typescript" "/chemin/inexistant.json"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_stack_skills : retourne vide si agent_id absent de _agent_scope" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "agent-inconnu" "typescript" "$cfg"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "resolve_stack_skills : injecte typescript pour developer-frontend" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-frontend" "typescript" "$cfg"
  echo "$output" | grep -q "dev-standards-typescript"
}

@test "resolve_stack_skills : injecte react pour developer-frontend" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-frontend" "react" "$cfg"
  echo "$output" | grep -q "dev-standards-react"
}

@test "resolve_stack_skills : n'injecte pas nestjs pour developer-frontend (hors scope)" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-frontend" "nestjs" "$cfg"
  ! echo "$output" | grep -q "dev-standards-nestjs"
}

@test "resolve_stack_skills : injecte nestjs pour developer-backend" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-backend" "nestjs" "$cfg"
  echo "$output" | grep -q "dev-standards-nestjs"
}

@test "resolve_stack_skills : n'injecte pas vue pour developer-backend (hors scope)" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-backend" "vue" "$cfg"
  ! echo "$output" | grep -q "dev-standards-vuejs"
}

@test "resolve_stack_skills : injecte react ET nextjs pour la stack next" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-frontend" "next" "$cfg"
  echo "$output" | grep -q "dev-standards-react"
  echo "$output" | grep -q "dev-standards-nextjs"
}

@test "resolve_stack_skills : déduplique les skills sur stacks multiples" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  # next inclut react, react tout seul aussi → dev-standards-react ne doit apparaître qu'une fois
  run resolve_stack_skills "developer-frontend" "$(printf 'next\nreact')" "$cfg"
  local react_count
  react_count=$(echo "$output" | grep -c "dev-standards-react" || true)
  [ "$react_count" -eq 1 ]
}

@test "resolve_stack_skills : developer-fullstack reçoit frontend ET backend" {
  local cfg="$TEST_DIR/stack-skills.json"
  _make_stack_config "$cfg"
  run resolve_stack_skills "developer-fullstack" "$(printf 'react\nnestjs')" "$cfg"
  echo "$output" | grep -q "dev-standards-react"
  echo "$output" | grep -q "dev-standards-nestjs"
}

# ── build_agent_content avec project_path ─────────────────────────────────────

@test "build_agent_content : n'injecte pas les stack skills quand project_path est vide" {
  # Créer un skill stack pour s'assurer qu'il n'est PAS injecté sans project_path
  mkdir -p "$TEST_DIR/skills/developer/stacks"
  cat > "$TEST_DIR/skills/developer/stacks/dev-standards-typescript.md" <<'EOF'
---
name: dev-standards-typescript
description: TypeScript skill
---

# TypeScript stack skill
EOF
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode" ""
  [ "$status" -eq 0 ]
  # Le skill stack ne doit pas apparaître (project_path vide → pas de détection)
  ! echo "$output" | grep -q "TypeScript stack skill"
}

@test "build_agent_content : injecte les stack skills quand project_path est fourni avec la bonne stack" {
  # Créer le skill stack dans le SKILLS_DIR de test
  mkdir -p "$TEST_DIR/skills/developer/stacks"
  cat > "$TEST_DIR/skills/developer/stacks/dev-standards-typescript.md" <<'EOF'
---
name: dev-standards-typescript
description: TypeScript skill
---

# TypeScript stack skill content
EOF

  # Créer un projet TypeScript ISOLÉ (pas de sous-dossiers qui déclencheraient terraform/k8s detect)
  local proj
  proj=$(mktemp -d)
  cat > "$proj/package.json" <<'EOF'
{ "devDependencies": { "typescript": "^5.0.0" } }
EOF

  # Créer un agent developer-frontend (dans le scope pour typescript)
  cat > "$TEST_DIR/agents/developer-frontend.md" <<'EOF'
---
id: developer-frontend
label: DeveloperFrontend
description: Agent frontend
targets: [opencode]
skills: [developer/test-skill]
---

# DeveloperFrontend
EOF

  # Créer un stack-skills.json minimal dans HUB_DIR de test
  mkdir -p "$TEST_DIR/config"
  cat > "$TEST_DIR/config/stack-skills.json" <<'EOF'
{
  "language": { "typescript": ["developer/stacks/dev-standards-typescript"] },
  "_agent_scope": { "developer-frontend": ["language"] }
}
EOF

  # Surcharger HUB_DIR pour pointer vers TEST_DIR
  HUB_DIR="$TEST_DIR"

  run build_agent_content "$TEST_DIR/agents/developer-frontend.md" "opencode" "" "$proj"
  rm -rf "$proj"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "TypeScript stack skill content"
}

@test "build_agent_content : ne duplique pas un skill déjà dans le frontmatter" {
  # Créer un skill stack identique à un skill déclaré en frontmatter
  mkdir -p "$TEST_DIR/skills/developer/stacks"
  cat > "$TEST_DIR/skills/developer/stacks/dev-standards-typescript.md" <<'EOF'
---
name: dev-standards-typescript
description: TypeScript skill
---

# TypeScript unique
EOF

  local proj
  proj=$(mktemp -d)
  cat > "$proj/package.json" <<'EOF'
{ "devDependencies": { "typescript": "^5.0.0" } }
EOF

  # Agent qui déclare DÉJÀ developer/stacks/dev-standards-typescript dans son frontmatter
  cat > "$TEST_DIR/agents/agent-with-ts.md" <<'EOF'
---
id: agent-with-ts
label: AgentWithTs
description: Agent qui déclare déjà typescript
targets: [opencode]
skills: [developer/stacks/dev-standards-typescript]
---

# AgentWithTs
EOF

  mkdir -p "$TEST_DIR/config"
  cat > "$TEST_DIR/config/stack-skills.json" <<'EOF'
{
  "language": { "typescript": ["developer/stacks/dev-standards-typescript"] },
  "_agent_scope": { "agent-with-ts": ["language"] }
}
EOF

  HUB_DIR="$TEST_DIR"

  run build_agent_content "$TEST_DIR/agents/agent-with-ts.md" "opencode" "" "$proj"
  rm -rf "$proj"
  [ "$status" -eq 0 ]
  # "TypeScript unique" ne doit apparaître qu'une seule fois
  local count
  count=$(echo "$output" | grep -c "TypeScript unique" || true)
  [ "$count" -eq 1 ]
}
