#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# agent-discovery.sh — Détection et résolution de similarité des agents projet
#
# Responsabilités :
#   - Détecter les agents existants dans un projet qui ne sont pas générés par le hub
#   - Résoudre la correspondance sémantique entre un ID d'agent externe et les IDs hub
#   - Tester si un fichier agent a été généré par le hub (présence du marker)
#
# Usage : sourcé par cmd-deploy.sh et cmd-agent.sh
# ─────────────────────────────────────────────────────────────────────────────
[ -n "${_AGENT_DISCOVERY_LOADED:-}" ] && return 0
_AGENT_DISCOVERY_LOADED=1

# Marker injecté dans chaque agent déployé par le hub (voir prompt-builder.sh)
_HUB_GENERATED_MARKER="generated by openhub"

# Chemin vers la table d'aliases (défaut relatif au HUB_DIR)
AGENT_ALIASES_FILE="${AGENT_ALIASES_FILE:-${HUB_DIR:-}/config/agent-aliases.json}"

# ── is_hub_generated_agent ────────────────────────────────────────────────────

##
# Teste si un fichier agent a été généré par le hub openhub.
# Recherche le marker "generated by openhub" dans les 5 premières lignes.
# @param {string} $1 — chemin absolu vers le fichier agent .md
# @returns 0 si généré par le hub, 1 sinon
##
is_hub_generated_agent() {
  local agent_file="${1:-}"
  [ -f "$agent_file" ] || return 1
  head -5 "$agent_file" | grep -qF "$_HUB_GENERATED_MARKER"
}

# ── discover_project_agents ───────────────────────────────────────────────────

##
# Découvre les agents existants dans un projet qui ne sont PAS générés par le hub.
# Scanne <project_path>/.opencode/agents/*.md et filtre ceux sans le marker hub.
# Imprime un chemin de fichier par ligne sur stdout.
# @param {string} $1 — chemin absolu vers le répertoire racine du projet
# @returns 0 toujours (erreur non fatale si .opencode/agents/ absent)
##
discover_project_agents() {
  local project_path="${1:-}"
  local agents_dir="${project_path}/.opencode/agents"

  [ -d "$agents_dir" ] || return 0

  while IFS= read -r agent_file; do
    [ -f "$agent_file" ] || continue
    # Ignorer les agents générés par le hub
    is_hub_generated_agent "$agent_file" && continue
    echo "$agent_file"
  done < <(find "$agents_dir" -maxdepth 1 -name "*.md" | sort)
}

# ── _normalize_agent_id ───────────────────────────────────────────────────────

##
# Normalise un identifiant d'agent pour la comparaison :
#   - Minuscules
#   - Remplacement des underscores par des tirets
#   - Suppression du suffixe .md si présent
# @param {string} $1 — identifiant à normaliser
# @returns la chaîne normalisée sur stdout
##
_normalize_agent_id() {
  local id="${1:-}"
  id="${id%.md}"
  id=$(echo "$id" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
  echo "$id"
}

# ── _read_agent_id_from_file ─────────────────────────────────────────────────

##
# Lit le champ id: du frontmatter YAML d'un fichier agent.
# Fallback sur le basename sans .md si le champ est absent.
# @param {string} $1 — chemin vers le fichier agent .md
# @returns l'identifiant sur stdout
##
_read_agent_id_from_file() {
  local agent_file="${1:-}"
  [ -f "$agent_file" ] || { basename "$agent_file" .md; return 0; }
  local id
  id=$(grep '^id:' "$agent_file" 2>/dev/null | head -1 | sed 's/^id:[[:space:]]*//')
  echo "${id:-$(basename "$agent_file" .md)}"
}

# ── resolve_agent_similarity ─────────────────────────────────────────────────

##
# Résout la correspondance sémantique entre un ID d'agent externe et les IDs hub.
# Stratégie en 3 niveaux :
#   1. Match exact de l'ID normalisé dans les IDs hub canoniques
#   2. Lookup dans config/agent-aliases.json (clé normalisée → tableau d'IDs hub)
#   3. Normalisation avancée : strip des préfixes/suffixes communs
#
# Imprime les IDs hub correspondants séparés par des virgules sur stdout.
# Imprime rien si aucun match.
#
# @param {string} $1 — identifiant de l'agent externe (ex: "planner", "dev-frontend")
# @returns 0 toujours
##
resolve_agent_similarity() {
  local external_id="${1:-}"
  [ -z "$external_id" ] && return 0

  local normalized
  normalized=$(_normalize_agent_id "$external_id")

  # ── Niveau 1 : match exact avec un ID hub canonique ─────────────────────
  local hub_ids=(
    "orchestrator" "orchestrator-dev" "planner" "pathfinder" "onboarder"
    "developer-frontend" "developer-backend" "developer-api" "developer-fullstack"
    "developer-devops" "developer-platform" "developer-mobile" "developer-data"
    "developer-security" "developer-refactor" "developer-migrator"
    "reviewer" "qa-engineer" "debugger"
    "documentarian"
    "ux-designer" "ui-designer"
    "auditor" "auditor-subagent"
  )
  for hub_id in "${hub_ids[@]}"; do
    if [ "$normalized" = "$hub_id" ]; then
      echo "$hub_id"
      return 0
    fi
  done

  # ── Niveau 2 : lookup dans agent-aliases.json ───────────────────────────
  if [ -f "$AGENT_ALIASES_FILE" ] && command -v jq &>/dev/null; then
    local matched
    # Chercher dans toutes les catégories de l'alias file
    matched=$(jq -r --arg key "$normalized" '
      to_entries[]
      | select(.key != "_comment" and .key != "_comment2")
      | .value
      | to_entries[]
      | select(.key == $key)
      | .value[]
    ' "$AGENT_ALIASES_FILE" 2>/dev/null | sort -u | tr '\n' ',' | sed 's/,$//')
    if [ -n "$matched" ]; then
      echo "$matched"
      return 0
    fi
  fi

  # ── Niveau 3 : normalisation avancée (strip préfixes/suffixes communs) ──
  # Essayer sans le préfixe "developer-", "dev-", "agent-"
  local stripped="$normalized"
  for prefix in "developer-" "dev-" "agent-" "my-" "custom-"; do
    if [[ "$normalized" == "${prefix}"* ]]; then
      stripped="${normalized#"$prefix"}"
      break
    fi
  done

  if [ "$stripped" != "$normalized" ] && [ -f "$AGENT_ALIASES_FILE" ] && command -v jq &>/dev/null; then
    local matched2
    matched2=$(jq -r --arg key "$stripped" '
      to_entries[]
      | select(.key != "_comment" and .key != "_comment2")
      | .value
      | to_entries[]
      | select(.key == $key)
      | .value[]
    ' "$AGENT_ALIASES_FILE" 2>/dev/null | sort -u | tr '\n' ',' | sed 's/,$//')
    if [ -n "$matched2" ]; then
      echo "$matched2"
      return 0
    fi
  fi

  # Aucun match
  return 0
}

# ── get_discovery_agent_id ────────────────────────────────────────────────────

##
# Retourne l'identifiant d'un agent découvert dans le projet.
# Lit le frontmatter id:, normalise, et fallback sur le basename.
# @param {string} $1 — chemin absolu vers le fichier agent .md
##
get_discovery_agent_id() {
  local agent_file="${1:-}"
  local raw_id
  raw_id=$(_read_agent_id_from_file "$agent_file")
  _normalize_agent_id "$raw_id"
}
