#!/bin/bash
# Assemble le contenu d'un agent canonique (agents/) avec ses skills injectés.
# Usage : source ce fichier, puis appeler build_agent_content <agent_file> [target]

# Guard contre le double sourcing
[[ -n "${_PROMPT_BUILDER_LOADED:-}" ]] && return 0
_PROMPT_BUILDER_LOADED=1

# Retourne la version du hub depuis config/hub.json
get_hub_version() {
  if command -v jq &>/dev/null && [ -f "$HUB_CONFIG" ]; then
    jq -r '.version // "unknown"' "$HUB_CONFIG" 2>/dev/null
  else
    grep '"version"' "$HUB_CONFIG" 2>/dev/null | head -1 \
      | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
      || echo "unknown"
  fi
}

# Retourne le commentaire d'en-tête à insérer dans chaque fichier généré
build_generated_header() {
  local version; version=$(get_hub_version)
  echo "<!-- generated by opencode-hub v${version} — do not edit manually -->"
}

# Extrait la valeur d'une clé scalaire dans le frontmatter YAML
extract_frontmatter_value() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 \
    | sed "s/^${key}:[[:space:]]*//"
}

# Extrait une liste inline [a, b, c] depuis le frontmatter
extract_frontmatter_list() {
  local file="$1" key="$2"
  extract_frontmatter_value "$file" "$key" \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$'
}

# Lit le frontmatter d'un agent en une seule passe et expose les variables :
#   _fm_id      : valeur du champ id
#   _fm_targets : valeur brute du champ targets (ex: "[opencode, claude-code]")
#   _fm_skills  : valeur brute du champ skills  (ex: "[skill/a, skill/b]")
# Utilise uniquement des builtins bash (read, while) — pas de subprocess.
# @param $1 — chemin absolu du fichier agent
read_agent_frontmatter() {
  local file="$1"
  _fm_id="" _fm_targets="" _fm_skills="" _fm_model=""
  local in_fm=0 fm_done=0
  while IFS= read -r line; do
    if [ "$in_fm" -eq 0 ] && [ "$line" = "---" ]; then
      in_fm=1
      continue
    fi
    if [ "$in_fm" -eq 1 ] && [ "$line" = "---" ]; then
      fm_done=1
      break
    fi
    if [ "$in_fm" -eq 1 ]; then
      # ⚠ Contrainte d'ordre : model: est optionnel et non inclus dans le early exit
      # (ligne ci-dessous). Il DOIT apparaître avant skills: dans le frontmatter
      # pour être lu avant la sortie anticipée.
      case "$line" in
        id:*)      _fm_id="${line#id:}";      _fm_id="${_fm_id# }"      ;;
        targets:*) _fm_targets="${line#targets:}"; _fm_targets="${_fm_targets# }" ;;
        skills:*)  _fm_skills="${line#skills:}";  _fm_skills="${_fm_skills# }"  ;;
        model:*)   _fm_model="${line#model:}";   _fm_model="${_fm_model# }"   ;;
      esac
    fi
    # Arrêter dès qu'on a tout (optimisation : les champs utiles sont dans les 10 premières lignes)
    # _fm_model est optionnel — pas inclus dans la condition de sortie anticipée
    [ -n "$_fm_id" ] && [ -n "$_fm_targets" ] && [ -n "$_fm_skills" ] && break
  done < "$file"
}

# Retourne les items d'une liste frontmatter déjà lue en mémoire (valeur brute)
# Usage : _fm_list_items "[a, b, c]" → affiche a / b / c une par ligne
# Utilise tr + bash — pas de sed subprocess supplémentaire
_fm_list_items() {
  local raw="$1"
  # Supprimer [ et ], remplacer virgules par newlines, strip espaces
  printf '%s' "$raw" | tr -d '[]' | tr ',' '\n' | \
    while IFS= read -r item; do
      item="${item# }"; item="${item% }"
      [ -n "$item" ] && printf '%s\n' "$item"
    done
}

# Retourne un rang numérique pour la hiérarchie des modèles (fonction interne)
# Hiérarchie : claude-opus-4(3) > claude-sonnet-4-5(2) > claude-haiku-4-5(1)
# Modèles inconnus = rang 0 — volontairement inférieur à haiku pour que le clamp
# force systématiquement le plancher quand un modèle non reconnu est résolu.
# Cela évite qu'un modèle inconnu contourne silencieusement un plancher opus/sonnet.
_get_model_rank() {
  local model="$1"
  # Extraire le nom de base (sans préfixe provider comme "anthropic/")
  local base="${model##*/}"
  case "$base" in
    claude-opus-4*)     echo 3 ;;
    claude-sonnet-4-5*) echo 2 ;;
    claude-haiku-4-5*)  echo 1 ;;
    *)                  echo 0 ;;
  esac
}

# Applique le clamp (plancher) du frontmatter
# Si resolved_model < floor_model en rang → retourne floor_model + warning
# $1 = resolved_model (depuis la cascade), $2 = floor_model (depuis le frontmatter), $3 = agent_id (pour le log)
clamp_model() {
  local resolved="$1" floor="$2" agent_id="${3:-}"
  [ -z "$floor" ] && echo "$resolved" && return 0
  local rank_resolved rank_floor
  rank_resolved=$(_get_model_rank "$resolved")
  rank_floor=$(_get_model_rank "$floor")
  if [ "$rank_resolved" -lt "$rank_floor" ]; then
    log_warn "Modèle résolu '$resolved' inférieur au plancher '$floor' pour l'agent '$agent_id' — plancher appliqué"
    echo "$floor"
  else
    echo "$resolved"
  fi
}

# Retourne la famille d'un agent (nom du dossier parent dans agents/)
# Ex: agents/planning/orchestrator.md → "planning"
_get_agent_family() {
  local agent_file="$1"
  local dir
  dir=$(dirname "$agent_file")
  basename "$dir"
}

# Résout le modèle à utiliser pour un agent via une cascade à 7 niveaux + clamp.
# $1 = agent_file (chemin du fichier .md)
# $2 = project_id (optionnel)
# Affiche le modèle résolu sur stdout.
resolve_agent_model() {
  local agent_file="$1"
  local project_id="${2:-}"

  # Lire le frontmatter pour obtenir id et model (plancher)
  read_agent_frontmatter "$agent_file"
  local agent_id="${_fm_id:-$(basename "$agent_file" .md)}"
  local floor_model="${_fm_model:-}"
  local family
  family=$(_get_agent_family "$agent_file")

  local resolved=""

  # Niveaux 1-3 : projet (seulement si project_id non vide)
  if [ -n "$project_id" ]; then
    # 1. P.agents.X
    [ -z "$resolved" ] && resolved=$(_api_keys_get "$project_id" "agent_models.agents.${agent_id}")
    # 2. P.families.F
    [ -z "$resolved" ] && resolved=$(_api_keys_get "$project_id" "agent_models.families.${family}")
    # 3. P.model
    [ -z "$resolved" ] && resolved=$(_api_keys_get "$project_id" "model")
  fi

  # Niveaux 4-6 : hub.json
  if [ -z "$resolved" ] && [ -f "$HUB_CONFIG" ]; then
    if command -v jq &>/dev/null; then
      # 4. hub.agents.X
      [ -z "$resolved" ] && resolved=$(jq -r ".agent_models.agents.\"${agent_id}\" // empty" "$HUB_CONFIG" 2>/dev/null)
      # 5. hub.families.F
      [ -z "$resolved" ] && resolved=$(jq -r ".agent_models.families.\"${family}\" // empty" "$HUB_CONFIG" 2>/dev/null)
      # 6. hub.model
      [ -z "$resolved" ] && resolved=$(jq -r '.opencode.model // empty' "$HUB_CONFIG" 2>/dev/null)
    else
      # Fallback sans jq : sed pour extraire les sections puis grep la clé
      # 4. hub.agents.X — chercher agent_id dans la section "agents" de "agent_models"
      [ -z "$resolved" ] && resolved=$(sed -n '/"agent_models"/,/^[[:space:]]*}/p' "$HUB_CONFIG" 2>/dev/null \
        | sed -n '/"agents"/,/}/p' \
        | grep "\"${agent_id}\"" | head -1 \
        | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/' | grep -v '{' || true)
      # 5. hub.families.F — chercher family dans la section "families" de "agent_models"
      [ -z "$resolved" ] && resolved=$(sed -n '/"agent_models"/,/^[[:space:]]*}/p' "$HUB_CONFIG" 2>/dev/null \
        | sed -n '/"families"/,/}/p' \
        | grep "\"${family}\"" | head -1 \
        | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/' | grep -v '{' || true)
      # 6. hub.model — chercher "model" dans la section opencode
      [ -z "$resolved" ] && resolved=$(sed -n '/"opencode"/,/}/p' "$HUB_CONFIG" 2>/dev/null | grep '"model"' | head -1 | sed 's/.*"model"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' || true)
    fi
  fi

  # 7. Fallback hardcodé
  [ -z "$resolved" ] && resolved="claude-sonnet-4-5"

  # Clamp
  clamp_model "$resolved" "$floor_model" "$agent_id"
}

# Extrait le bloc permission du frontmatter et le convertit en JSON inline
# Supporte : permission.question (scalaire) et permission.task (map multi-ligne)
# Retourne une chaîne JSON partielle, ex: "\"permission\": { \"question\": \"allow\" }"
# ou vide si aucune permission n'est déclarée
extract_permission_json() {
  local file="$1"
  # Extraire uniquement le bloc frontmatter
  local frontmatter
  frontmatter=$(sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d')
  [ -z "$frontmatter" ] && return 0

  # Détecter si un bloc permission: existe
  echo "$frontmatter" | grep -q '^permission:' || return 0

  # Extraire tous les scalaires directs sous permission: (indentation 2 espaces)
  # et le sous-bloc task: (indentation 4 espaces)
  # Scalaires supportés : question, bash, edit, write, et tout futur scalaire
  local in_permission=0 in_task=0
  local scalar_fields="" task_entries=""

  while IFS= read -r line; do
    if echo "$line" | grep -q '^permission:'; then
      in_permission=1; in_task=0; continue
    fi
    if [ "$in_permission" = "1" ]; then
      # Quitter le bloc permission si on revient à l'indentation racine
      if echo "$line" | grep -qE '^[^ ]'; then
        in_permission=0; in_task=0; continue
      fi

      if echo "$line" | grep -q '^  task:'; then
        in_task=1; continue
      fi

      if [ "$in_task" = "1" ]; then
        # Ligne d'entrée task : "    \"*\": \"deny\"" ou "    \"developer-*\": \"allow\""
        if echo "$line" | grep -qE '^    '; then
          # Extraire clé et valeur (format YAML : "clé": valeur ou clé: valeur)
          # shellcheck disable=SC2001
          local kv; kv=$(echo "$line" | sed 's/^[[:space:]]*//')
          # Clé : peut être quotée ("*") ou non (reviewer) — on strip les guillemets
          local k; k=$(echo "$kv" | cut -d: -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/^"//;s/"$//')
          local v; v=$(echo "$kv" | cut -d: -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          if [ -n "$k" ] && [ -n "$v" ]; then
            [ -n "$task_entries" ] && task_entries="${task_entries}, "
            task_entries="${task_entries}\"${k}\": \"${v}\""
          fi
        else
          # Fin du bloc task
          in_task=0
        fi
      fi

      # Scalaire direct sous permission: (2 espaces, pas task:, pas sous-bloc)
      if [ "$in_task" = "0" ] && echo "$line" | grep -qE '^  [a-zA-Z][a-zA-Z0-9_-]*: '; then
        local sk; sk=$(echo "$line" | sed 's/^  //;s/:.*//' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        local sv; sv=$(echo "$line" | cut -d: -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        if [ -n "$sk" ] && [ -n "$sv" ]; then
          [ -n "$scalar_fields" ] && scalar_fields="${scalar_fields}, "
          scalar_fields="${scalar_fields}\"${sk}\": \"${sv}\""
        fi
      fi
    fi
  done <<< "$frontmatter"

  # Construire le JSON de permission
  local perm_fields="${scalar_fields}"
  if [ -n "$task_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"task\": { ${task_entries} }"
  fi

  if [ -n "$perm_fields" ]; then
    echo "\"permission\": { ${perm_fields} }"
  fi
}

# Retourne le contenu d'un fichier Markdown en ignorant le bloc frontmatter YAML
strip_frontmatter() {
  local file="$1"
  if head -1 "$file" | grep -q '^---$'; then
    awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file"
  else
    cat "$file"
  fi
}

# Vérifie si un agent supporte une cible donnée (via frontmatter targets)
agent_supports_target() {
  extract_frontmatter_list "$1" "targets" | grep -q "^${2}$"
}

# Retourne le mode de déploiement d'un agent (frontmatter mode:)
# Valeurs possibles : "primary" | "subagent" | "all"
# Fallback : "primary" si le champ est absent
get_agent_mode() {
  local mode
  mode=$(extract_frontmatter_value "$1" "mode")
  echo "${mode:-primary}"
}

# Retourne l'identifiant d'un agent (frontmatter id, ou nom de fichier sans extension)
get_agent_id() {
  local id
  id=$(extract_frontmatter_value "$1" "id")
  if [ -z "$id" ]; then
    basename "$1" .md
  else
    echo "$id"
  fi
}

# Détecte la stack d'un projet à partir de ses fichiers de dépendances.
# @param $1 — project_path (chemin racine du projet)
# Affiche sur stdout une liste de clés de stack, une par ligne.
# Clés possibles : typescript, python, vue, react, next, nuxt, angular,
#   nestjs, express, fastify, django, fastapi, laravel, rails, spring,
#   prisma, typeorm, sqlalchemy, mongoose,
#   vitest, jest, playwright, cypress, openapi,
#   react-native, flutter, swift, kotlin,
#   pandas, dbt, airflow, pyspark,
#   docker, github-actions, gitlab-ci,
#   terraform, kubernetes, helm, argocd
detect_stack() {
  local project_path="${1:-}"
  [ -z "$project_path" ] || [ ! -d "$project_path" ] && return 0

  local pkg_json="${project_path}/package.json"
  local pyproject="${project_path}/pyproject.toml"
  local requirements="${project_path}/requirements.txt"
  local gemfile="${project_path}/Gemfile"
  local build_gradle="${project_path}/build.gradle"
  local build_gradle_kts="${project_path}/build.gradle.kts"
  local pom_xml="${project_path}/pom.xml"
  local pubspec="${project_path}/pubspec.yaml"

  # Répertoires à exclure des find (node_modules, dist, build, .git, .nuxt...)
  # shellcheck disable=SC2054
  local _prune_args=( \( -name "node_modules" -o -name ".git" -o -name "dist" -o -name "build"
                         -o -name ".nuxt" -o -name ".output" -o -name ".next" -o -name "__pycache__"
                         -o -name ".venv" -o -name "venv" -o -name "vendor" \) -prune -o )

  # ── JavaScript / TypeScript (package.json) ──────────────────────────────
  if [ -f "$pkg_json" ]; then
    local deps=""
    deps=$(grep -E '"dependencies"|"devDependencies"' -A 9999 "$pkg_json" 2>/dev/null | \
           grep -oE '"[a-zA-Z@][a-zA-Z0-9@/_-]*"[[:space:]]*:' | tr -d '"' | tr -d ':' | tr -d ' ')

    # Langage
    echo "$deps" | grep -q 'typescript' && echo "typescript" || true

    # Frontend frameworks
    { echo "$deps" | grep -qE '^next$'; } && echo "next" && echo "react" || true
    { echo "$deps" | grep -qE '^nuxt$'; } && echo "nuxt" && echo "vue" || true
    { echo "$deps" | grep -qE '^@vue/core$|^vue$' && ! echo "$deps" | grep -q '^nuxt$'; } && echo "vue" || true
    { echo "$deps" | grep -qE '^react$' && ! echo "$deps" | grep -q '^next$'; } && echo "react" || true
    echo "$deps" | grep -qE '^@angular/core$' && echo "angular" || true

    # Backend frameworks
    echo "$deps" | grep -qE '^@nestjs/core$' && echo "nestjs" || true
    echo "$deps" | grep -qE '^express$' && echo "express" || true
    echo "$deps" | grep -qE '^fastify$' && echo "fastify" || true

    # ORMs / BDD
    echo "$deps" | grep -qE '^@prisma/client$|^prisma$' && echo "prisma" || true
    echo "$deps" | grep -qE '^typeorm$' && echo "typeorm" || true
    echo "$deps" | grep -qE '^mongoose$' && echo "mongoose" || true

    # Outils de test
    echo "$deps" | grep -qE '^vitest$' && echo "vitest" || true
    echo "$deps" | grep -qE '^jest$|^@jest/core$' && echo "jest" || true
    echo "$deps" | grep -qE '^@playwright/test$|^playwright$' && echo "playwright" || true
    echo "$deps" | grep -qE '^cypress$' && echo "cypress" || true

    # Spec API
    if [ -f "${project_path}/openapi.yaml" ] || \
       [ -f "${project_path}/openapi.yml" ] || \
       [ -f "${project_path}/swagger.yaml" ] || \
       [ -f "${project_path}/docs/openapi.yaml" ] || \
       [ -f "${project_path}/docs/api/openapi.yaml" ]; then
      echo "openapi"
    fi

    # Mobile
    echo "$deps" | grep -qE '^react-native$' && echo "react-native" || true
  fi

  # ── Python (pyproject.toml / requirements.txt) ──────────────────────────
  if [ -f "$pyproject" ] || [ -f "$requirements" ]; then
    echo "python"

    local py_deps=""
    [ -f "$pyproject" ] && py_deps=$(cat "$pyproject" 2>/dev/null)
    [ -f "$requirements" ] && py_deps="${py_deps}$(cat "$requirements" 2>/dev/null)"

    echo "$py_deps" | grep -qiE 'django' && echo "django" || true
    echo "$py_deps" | grep -qiE 'fastapi' && echo "fastapi" || true
    echo "$py_deps" | grep -qiE 'sqlalchemy' && echo "sqlalchemy" || true
    echo "$py_deps" | grep -qiE '^pandas|pandas==' && echo "pandas" || true
    echo "$py_deps" | grep -qiE '^dbt-|dbt==' && echo "dbt" || true
    echo "$py_deps" | grep -qiE 'apache-airflow|airflow' && echo "airflow" || true
    echo "$py_deps" | grep -qiE 'pyspark' && echo "pyspark" || true
  fi

  # ── Ruby (Gemfile) ───────────────────────────────────────────────────────
  if [ -f "$gemfile" ]; then
    grep -q 'rails' "$gemfile" 2>/dev/null && echo "rails" || true
  fi

  # ── Java / Kotlin (build.gradle / pom.xml) ───────────────────────────────
  if [ -f "$build_gradle" ] || [ -f "$build_gradle_kts" ] || [ -f "$pom_xml" ]; then
    local jvm_deps=""
    [ -f "$build_gradle" ] && jvm_deps=$(cat "$build_gradle" 2>/dev/null)
    [ -f "$build_gradle_kts" ] && jvm_deps="${jvm_deps}$(cat "$build_gradle_kts" 2>/dev/null)"
    [ -f "$pom_xml" ] && jvm_deps="${jvm_deps}$(cat "$pom_xml" 2>/dev/null)"

    echo "$jvm_deps" | grep -qiE 'spring-boot|spring.boot' && echo "spring" || true
    echo "$jvm_deps" | grep -qiE 'jetpack.compose|compose.bom' && echo "kotlin" || true
  fi

  # ── Dart / Flutter (pubspec.yaml) ────────────────────────────────────────
  if [ -f "$pubspec" ]; then
    grep -q 'flutter' "$pubspec" 2>/dev/null && echo "flutter" || true
  fi

  # ── Infrastructure (fichiers de config) ──────────────────────────────────
  { [ -f "${project_path}/Dockerfile" ] || [ -f "${project_path}/docker-compose.yml" ] || \
    [ -f "${project_path}/docker-compose.yaml" ]; } && echo "docker" || true
  { [ -d "${project_path}/.github/workflows" ]; } && echo "github-actions" || true
  { [ -f "${project_path}/.gitlab-ci.yml" ]; } && echo "gitlab-ci" || true

  # Terraform — prune les dossiers lourds
  { find "$project_path" "${_prune_args[@]}" -name "*.tf" -print 2>/dev/null | grep -q .; } && echo "terraform" || true

  # Kubernetes — prune + limiter à maxdepth 4
  { find "$project_path" "${_prune_args[@]}" \( -name "*.yaml" -o -name "*.yml" \) -print 2>/dev/null | \
    xargs grep -l 'kind: Deployment\|kind: Service\|kind: Ingress' 2>/dev/null | grep -q .; } && echo "kubernetes" || true

  # Helm — prune
  { [ -f "${project_path}/Chart.yaml" ] || \
    find "$project_path" "${_prune_args[@]}" -name "Chart.yaml" -print 2>/dev/null | grep -q .; } && echo "helm" || true

  # ArgoCD — prune
  { find "$project_path" "${_prune_args[@]}" \( -name "*.yaml" -o -name "*.yml" \) -print 2>/dev/null | \
    xargs grep -l 'argoproj.io\|kind: Application' 2>/dev/null | grep -q .; } && echo "argocd" || true
}

# Résout la liste des skills stack à injecter pour un agent donné.
# @param $1 — agent_id (ex: developer-frontend)
# @param $2 — stacks_list (liste de clés séparées par des espaces ou newlines)
# @param $3 — stack_skills_config (chemin vers config/stack-skills.json)
# Affiche sur stdout les chemins de skills à injecter, un par ligne, dédupliqués.
resolve_stack_skills() {
  local agent_id="$1"
  local stacks_list="$2"
  local config_file="$3"

  [ -z "$stacks_list" ] && return 0
  [ -f "$config_file" ] || return 0
  command -v jq &>/dev/null || return 0  # jq requis pour parser le JSON

  # Récupérer les catégories autorisées pour cet agent
  local allowed_categories
  allowed_categories=$(jq -r --arg agent "$agent_id" \
    '._agent_scope[$agent] // [] | .[]' "$config_file" 2>/dev/null)

  # Si pas de scope défini pour cet agent, ne rien injecter
  [ -z "$allowed_categories" ] && return 0

  local seen=()
  local stack

  while IFS= read -r stack; do
    [ -z "$stack" ] && continue

    # Pour chaque catégorie autorisée, chercher si la stack y est mappée
    local category
    while IFS= read -r category; do
      [ -z "$category" ] && continue

      # Chercher la stack dans cette catégorie
      local skills
      skills=$(jq -r --arg cat "$category" --arg stack "$stack" \
        '.[$cat][$stack] // [] | .[]' "$config_file" 2>/dev/null)

      [ -z "$skills" ] && continue

      # Ajouter les skills non encore vus
      local skill
      while IFS= read -r skill; do
        [ -z "$skill" ] && continue
        local already_seen=0
        local s
        for s in "${seen[@]:-}"; do
          [ "$s" = "$skill" ] && already_seen=1 && break
        done
        if [ "$already_seen" = "0" ]; then
          seen+=("$skill")
          echo "$skill"
        fi
      done <<< "$skills"
    done <<< "$allowed_categories"
  done <<< "$stacks_list"
}

# Précalcule en une seule passe jq tous les stack skills pour une liste de stacks détectées.
# Retourne une chaîne "agent_id:skill_path\n..." utilisable par _get_precomputed_stack_skills.
# Signature : precompute_stack_skills STACKS_NEWLINE_SEP CONFIG_FILE
# Exemple d'usage :
#   _cached=$(precompute_stack_skills "$detected_stacks" config/stack-skills.json)
#   while IFS= read -r sk; do ...; done < <(_get_precomputed_stack_skills "developer-api" "$_cached")
precompute_stack_skills() {
  local stacks_list="$1"
  local config_file="$2"

  [ -z "$stacks_list" ] && return 0
  [ -f "$config_file" ] || return 0
  command -v jq &>/dev/null || return 0

  # Construire un tableau jq de stacks depuis la liste bash
  local stacks_json
  stacks_json=$(printf '%s\n' "$stacks_list" | jq -R . | jq -s .)

  # En une seule invocation jq : pour chaque agent qui a un _agent_scope,
  # parcourir les catégories autorisées, puis les stacks détectées,
  # et émettre "agent_id:skill_path" pour chaque skill trouvé.
  jq -r --argjson stacks "$stacks_json" '
    . as $conf |
    ($conf._agent_scope // {}) | to_entries[] |
    select(.value | type == "array") |
    .key as $agent |
    .value[] as $cat |
    $stacks[] as $stack |
    ($conf[$cat][$stack] // [])[] |
    "\($agent):\(.)"
  ' "$config_file" 2>/dev/null | sort -u || true
}

# Filtre les lignes "agent_id:skill" précalculées pour un agent donné.
# Signature : _get_precomputed_stack_skills AGENT_ID PRECOMPUTED_STRING
_get_precomputed_stack_skills() {
  local agent_id="$1"
  local precomputed="$2"
  [ -z "$precomputed" ] && return 0
  local prefix="${agent_id}:"
  while IFS= read -r line; do
    [ "${line#"$prefix"}" != "$line" ] && printf '%s\n' "${line#"$prefix"}"
  done <<< "$precomputed"
}

# Construit le contenu final : corps de l'agent + skills injectés → stdout
# $2 (target) est réservé pour un futur filtrage par cible — non utilisé pour l'instant
# $3 (lang) optionnel — si non vide, injecte une instruction de langue en tête de l'agent
# $4 (project_path) optionnel — si non vide, détecte la stack et injecte les skills correspondants
build_agent_content() {
  local agent_file="$1"
  # shellcheck disable=SC2034
  local target="${2:-opencode}"  # réservé : filtrage par cible (futur)
  local lang="${3:-}"
  local project_path="${4:-}"
  [ -f "$agent_file" ] || { log_warn "Agent introuvable : $agent_file" >&2; return 1; }

  build_generated_header
  echo ""
  if [ -n "$lang" ]; then
    echo "> **Langue de travail : ${lang}.** Rédige toutes tes réponses, rapports et commentaires en ${lang}, quelle que soit la langue des instructions ci-dessous."
    echo ""
  fi
  strip_frontmatter "$agent_file"

  # ── Skills déclarés dans le frontmatter ─────────────────────────────────
  local skills=()
  while IFS= read -r skill; do
    skills+=("$skill")
  done < <(extract_frontmatter_list "$agent_file" "skills")

  # ── Skills dynamiques basés sur la stack détectée ────────────────────────
  local stack_skills=()
  if [ -n "$project_path" ] && [ -d "$project_path" ]; then
    local agent_id
    agent_id=$(get_agent_id "$agent_file")

    local stack_skills_config="${HUB_DIR:-}/config/stack-skills.json"

    if [ -f "$stack_skills_config" ]; then
      local detected_stacks
      detected_stacks=$(detect_stack "$project_path" | sort -u || true)

      if [ -n "$detected_stacks" ]; then
        while IFS= read -r stack_skill; do
          [ -z "$stack_skill" ] && continue
          # Vérifier que ce skill n'est pas déjà dans les skills déclarés
          local already_declared=0
          local declared_skill
          for declared_skill in "${skills[@]:-}"; do
            [ "$declared_skill" = "$stack_skill" ] && already_declared=1 && break
          done
          [ "$already_declared" = "0" ] && stack_skills+=("$stack_skill")
        done < <(resolve_stack_skills "$agent_id" "$detected_stacks" "$stack_skills_config")
      fi
    fi
  fi

  # ── Injection des skills (déclarés + stack) ──────────────────────────────
  local all_skills=("${skills[@]:-}" "${stack_skills[@]:-}")

  if [ ${#all_skills[@]} -gt 0 ]; then
    echo ""
    echo "---"
    echo ""
    for skill in "${all_skills[@]}"; do
      [ -z "$skill" ] && continue
      local skill_file="$SKILLS_DIR/${skill}.md"
      if [ -f "$skill_file" ]; then
        strip_frontmatter "$skill_file"
        echo ""
      else
        log_warn "Skill introuvable : ${skill}.md" >&2
      fi
    done
  fi
}

# Construit le prompt de bootstrap pour le mode --dev (oc start --dev)
# Interroge bd ready dans le répertoire du projet
# @param $1 — project_path
# @param $2 — label (optionnel, défaut : "ai-delegated")
# @param $3 — assignee (optionnel, si fourni filtre par assignee au lieu du label)
build_dev_bootstrap_prompt() {
  local project_path="$1"
  local label="${2:-ai-delegated}"
  local assignee="${3:-}"
  local tickets

  if [ -n "$assignee" ]; then
    tickets=$(cd "$project_path" && bd ready --assignee "$assignee" --json 2>/dev/null) || tickets="[]"
  else
    tickets=$(cd "$project_path" && bd ready --label "$label" --json 2>/dev/null) || tickets="[]"
  fi
  # Valider que la sortie est un JSON array — si bd retourne du texte d'erreur, ignorer
  if [ -z "$tickets" ] || [[ "$tickets" != \[* ]]; then
    tickets="[]"
  fi

  local filter_desc
  if [ -n "$assignee" ]; then
    filter_desc="assigné à \"${assignee}\""
  else
    filter_desc="label \"${label}\""
  fi

  if [ "$tickets" = "[]" ] || [ "$tickets" = "null" ]; then
    cat <<EOF
Aucun ticket avec le ${filter_desc} n'est prêt à implémenter.

Pour déléguer un ticket à l'agent :
  bd label add <ID> ${label}

Pour voir tous les tickets ouverts :
  bd list -s open --json
EOF
  else
    cat <<EOF
Voici les tickets délégués à l'agent (${filter_desc}, statut ready) :

${tickets}

Workflow obligatoire :
1. bd show <ID>                  — lire le détail complet avant tout
2. bd update <ID> --claim        — clamer le ticket (atomique)
3. Implémenter + tester
4. bd update <ID> -s review      — passer en review
5. bd close <ID> --suggest-next  — clore après validation et passer au suivant

Commence par le ticket le plus prioritaire.
EOF
  fi
}

# Construit le prompt de bootstrap pour la commande oc audit
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — audit_type (optionnel — vide = audit global)
build_audit_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local audit_type="${3:-}"
  local scope_line=""
  [ -n "$audit_type" ] && scope_line="Périmètre : audit ${audit_type} uniquement."

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  cat <<EOF
Effectue un audit du projet.

${project_info}
${scope_line:+
${scope_line}}
PHASE 1 — Contexte projet (OBLIGATOIRE avant toute délégation aux sous-agents)

Si le fichier ONBOARDING.md existe à la racine du projet :
  → Le lire en priorité — il contient déjà la stack, la structure et les points d'attention
  → Annoncer : "Contexte projet chargé depuis ONBOARDING.md" suivi d'un résumé en 1-2 phrases

Sinon, reconnaissance rapide (3-4 fichiers uniquement) :
  → Lire le fichier de dépendances racine (package.json, composer.json, requirements.txt…)
  → Inspecter la structure des répertoires principaux (src/, app/, etc.)
  → Identifier 1-2 fichiers de config pertinents selon le type d'audit (.env.example, nginx.conf…)
  → Résumer en 5 lignes : stack, répertoires principaux, points d'attention immédiats visibles

PHASE 2 — Délégation aux sous-agents

Déléguer aux sous-agents appropriés en leur passant le résumé du contexte (Phase 1) en préambule.
Chaque sous-agent travaille en lecture seule et produit un rapport structuré.
EOF
}

# Construit le prompt de bootstrap pour le mode --onboard (oc start --onboard)
# Déclenche l'agent onboarder en lecture seule sur le projet
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — hub_dir (optionnel — défaut : $HUB_DIR)
build_onboard_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local hub_dir="${3:-${HUB_DIR:-}}"
  local projects_file="${hub_dir:+${hub_dir}/projects/projects.md}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  local hub_info=""
  if [ -n "$hub_dir" ] && [ -n "$projects_file" ]; then
    hub_info="
Hub : ${hub_dir}
projects.md : ${projects_file}"
  fi

  cat <<EOF
Effectue une exploration complète du projet pour produire un rapport de contexte.

${project_info}${hub_info}

Workflow :
1. Annoncer ce qui va être exploré
2. ÉTAPE 1 — Détecter la stack (racine du projet)
3. ÉTAPE 2 — Explorer adaptativement selon le profil détecté
4. ÉTAPE 3 — Lire les tickets Beads (bd list -s open) + ADRs si disponibles
5. ÉTAPE 4 — Produire le rapport de contexte structuré
6. ÉTAPE 5 — Écrire ONBOARDING.md à la racine du projet
7. ÉTAPE 6 — Détecter les conventions et écrire CONVENTIONS.md à la racine du projet

Règles :
- Lecture seule — tu ne modifies aucun fichier du projet (sauf ONBOARDING.md, CONVENTIONS.md et .git/info/exclude)
- Rapport honnête : signaler les points critiques (🔴), importants (🟠), améliorations (🟡)
- Lister les zones d'ombre non résolues
- Après le rapport complet dans la conversation, écrire ONBOARDING.md à la racine du projet
  (sans les sections Agents recommandés et Commandes utiles)
- Ensuite, détecter et écrire CONVENTIONS.md à la racine du projet
  (linting config, tsconfig, package.json, git log, fichiers représentatifs de la codebase)
- Ajouter ONBOARDING.md et CONVENTIONS.md au .git/info/exclude du projet
  (créer le fichier .git/info/exclude s'il n'existe pas, ainsi que le dossier .git/info/ si nécessaire)
  Ne pas modifier le .gitignore du projet — utiliser uniquement .git/info/exclude (exclusion locale)
- Si le champ Stack est absent ou incomplet dans projects.md, le mettre à jour
  (chemin fourni ci-dessus — demander confirmation explicite avant toute écriture)
EOF
}

# Construit le prompt de bootstrap pour la commande oc review
# Exécute git diff main...<branch> et injecte le résultat dans le prompt
# @param $1 — project_path
# @param $2 — project_id
# @param $3 — branch (branche à reviewer)
build_review_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local branch="${3:-}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  # Générer le diff git main...<branch>
  local diff_content=""
  local diff_cmd="git diff main...${branch}"
  if diff_content=$(git -C "$project_path" diff "main...${branch}" 2>/dev/null); then
    if [ -z "$diff_content" ]; then
      diff_content="(aucune différence détectée entre main et ${branch})"
    fi
  else
    # Fallback : essayer sans les trois points (branche sans ancêtre commun avec main)
    diff_content=$(git -C "$project_path" diff "main..${branch}" 2>/dev/null || echo "(impossible de générer le diff — vérifier que la branche '${branch}' et 'main' existent)")
    diff_cmd="git diff main..${branch}"
  fi

  # Vérifier l'existence de CONVENTIONS.md et ONBOARDING.md
  local conventions_hint=""
  if [ -f "${project_path}/CONVENTIONS.md" ]; then
    conventions_hint="
→ Lire CONVENTIONS.md à la racine du projet avant la review (prime sur les standards génériques)"
  fi

  local onboarding_hint=""
  if [ -f "${project_path}/ONBOARDING.md" ]; then
    onboarding_hint="
→ ONBOARDING.md disponible — consulter pour le contexte du projet si nécessaire"
  fi

  cat <<EOF
Effectue une code review de la branche \`${branch}\`.

${project_info}
Branche reviewée : ${branch}
Commande diff utilisée : ${diff_cmd}
${conventions_hint}${onboarding_hint}

--- DIFF ---

${diff_content}

--- FIN DU DIFF ---

Workflow :
1. Si CONVENTIONS.md existe à la racine → le lire pour appliquer les conventions réelles du projet
2. Analyser le diff ci-dessus selon la checklist systématique du skill review-protocol
3. Produire le rapport structuré par sévérité : Critique → Majeur → Mineur → Suggestion → Points positifs

Rappel :
- Tu fournis un avis de review, tu ne modifies pas de fichiers
- Calibre les commentaires au scope réel du diff (pas de refactoring hors-scope)
EOF
}

# Construit le prompt de bootstrap pour la commande oc conventions
# Déclenche la détection ciblée des conventions du projet → CONVENTIONS.md
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — hub_dir (optionnel)
build_conventions_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local hub_dir="${3:-${HUB_DIR:-}}"
  local projects_file="${hub_dir:+${hub_dir}/projects/projects.md}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  local hub_info=""
  if [ -n "$hub_dir" ] && [ -n "$projects_file" ]; then
    hub_info="
Hub : ${hub_dir}
projects.md : ${projects_file}"
  fi

  cat <<EOF
Détecte et documente les conventions de développement de ce projet dans CONVENTIONS.md.

${project_info}${hub_info}

Workflow :
1. Annoncer ce qui va être lu
2. ÉTAPE 1 — Lire les configs linting/formatting
   (.eslintrc*, eslint.config.*, .prettierrc*, .editorconfig, biome.json, ruff.toml, etc.)
3. ÉTAPE 2 — Lire la config langage et typage
   (tsconfig.json, pyproject.toml, go.mod, etc.)
4. ÉTAPE 3 — Lire les dépendances et libs choisies
   (package.json, pyproject.toml, Gemfile, etc.)
5. ÉTAPE 4 — Lire les conventions Git
   (.commitlintrc*, .husky/, CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md)
   + git log --oneline -20 pour observer les conventions réelles
6. ÉTAPE 5 — Inférer le nommage depuis 5 à 10 fichiers représentatifs de la codebase
   (composants, services, tests, stores — selon le profil du projet)
7. ÉTAPE 6 — Lire les configs de test
   (vitest.config.*, jest.config.*, pytest.ini, playwright.config.*, etc.)
8. ÉTAPE 7 — Écrire CONVENTIONS.md à la racine du projet
   ⚠️ Si CONVENTIONS.md existe déjà → afficher la date du fichier existant et demander confirmation
   avant d'écraser ("Écraser / Conserver l'existant")
    Ajouter CONVENTIONS.md au .git/info/exclude s'il n'y est pas déjà
    (ne pas modifier le .gitignore du projet — exclusion locale uniquement)

Règles :
- Baser chaque convention sur un fichier réellement lu — ne jamais inventer
- Signaler les incohérences détectées (ex: config lint ≠ pratique observée dans le code)
- Section "Zones d'ombre" pour ce qui n'a pas pu être déterminé
- Ne pas modifier d'autres fichiers du projet
EOF
}

# Construit le prompt de bootstrap pour la commande oc debug
# Lance l'agent debugger en mode interactif sur le projet
# @param $1 — project_path
# @param $2 — project_id (optionnel)
build_debug_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  # Vérifier l'existence de ONBOARDING.md
  local onboarding_hint=""
  if [ -f "${project_path}/ONBOARDING.md" ]; then
    onboarding_hint="
→ ONBOARDING.md disponible — consulter pour le contexte du projet"
  fi

  cat <<EOF
Session de debug sur le projet.

${project_info}
${onboarding_hint}

Attends les instructions de l'utilisateur pour commencer le debug.
L'utilisateur décrira le bug ou le comportement inattendu à investiguer.
EOF
}
