#!/bin/bash
# Assemble le contenu d'un agent canonique (agents/) avec ses skills injectés.
# Architecture hybride :
#   - skills (Bucket A, obligatoires) → inlinées dans le body de l'agent
#   - native_skills (Bucket B, optionnelles) → déployées en .opencode/skills/<name>/SKILL.md
#   - stack skills (dynamiques, Bucket B) → déployées en .opencode/skills/ via stack-skills.json
# Usage : source ce fichier, puis appeler build_agent_content <agent_file>

# Guard contre le double sourcing
[[ -n "${_PROMPT_BUILDER_LOADED:-}" ]] && return 0
_PROMPT_BUILDER_LOADED=1

# Retourne la version du hub depuis config/hub.json
get_hub_version() {
  if command -v jq &>/dev/null && [ -f "$HUB_CONFIG" ]; then
    jq -r '.version // "unknown"' "$HUB_CONFIG" 2>/dev/null
  else
    grep '"version"' "$HUB_CONFIG" 2>/dev/null | head -1 \
      | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
      || echo "unknown"
  fi
}

# Retourne le commentaire d'en-tête à insérer dans chaque fichier généré
build_generated_header() {
  local version; version=$(get_hub_version)
  echo "<!-- generated by opencode-hub v${version} — do not edit manually -->"
}

# Extrait la valeur d'une clé scalaire dans le frontmatter YAML
extract_frontmatter_value() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 \
    | sed "s/^${key}:[[:space:]]*//"
}

# Extrait une liste inline [a, b, c] depuis le frontmatter
extract_frontmatter_list() {
  local file="$1" key="$2"
  extract_frontmatter_value "$file" "$key" \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$'
}

# Lit le frontmatter d'un agent en une seule passe et expose les variables :
#   _fm_id           : valeur du champ id
#   _fm_skills       : valeur brute du champ skills        (ex: "[skill/a, skill/b]")
#   _fm_native_skills: valeur brute du champ native_skills (ex: "[skill/c, skill/d]")
#   _fm_model        : valeur du champ model (optionnel)
#   _fm_raw          : le frontmatter complet (toutes les lignes, pour extract_permission_json)
# Utilise uniquement des builtins bash (read, while) — pas de subprocess.
# @param $1 — chemin absolu du fichier agent
read_agent_frontmatter() {
  local file="$1"
  _fm_id="" _fm_skills="" _fm_native_skills="" _fm_model="" _fm_raw=""
  local in_fm=0
  while IFS= read -r line; do
    if [ "$in_fm" -eq 0 ] && [ "$line" = "---" ]; then
      in_fm=1
      continue
    fi
    if [ "$in_fm" -eq 1 ] && [ "$line" = "---" ]; then
      break
    fi
    if [ "$in_fm" -eq 1 ]; then
      # Accumuler le frontmatter brut (pour extract_permission_json)
      _fm_raw="${_fm_raw}${line}"$'\n'
      
      # ⚠ Contrainte d'ordre : model: est optionnel et non inclus dans le early exit
      # (ligne ci-dessous). Il DOIT apparaître avant skills: dans le frontmatter
      # pour être lu avant la sortie anticipée.
      case "$line" in
        id:*)           _fm_id="${line#id:}";            _fm_id="${_fm_id# }"            ;;
        skills:*)       _fm_skills="${line#skills:}";    _fm_skills="${_fm_skills# }"    ;;
        native_skills:*) _fm_native_skills="${line#native_skills:}"; _fm_native_skills="${_fm_native_skills# }" ;;
        model:*)        _fm_model="${line#model:}";      _fm_model="${_fm_model# }"      ;;
      esac
    fi
    # Arrêter dès qu'on a tout (optimisation : les champs utiles sont dans les 10 premières lignes)
    # _fm_model est optionnel — pas inclus dans la condition de sortie anticipée
    # Note : on ne peut pas sortir avant la fin du frontmatter car on a besoin de _fm_raw complet
    # pour extract_permission_json. On optimise donc moins, mais on économise le sed.
  done < "$file"
}

# Retourne les items d'une liste frontmatter déjà lue en mémoire (valeur brute)
# Usage : _fm_list_items "[a, b, c]" → affiche a / b / c une par ligne
# Utilise tr + bash — pas de sed subprocess supplémentaire
_fm_list_items() {
  local raw="$1"
  # Supprimer [ et ], remplacer virgules par newlines, strip espaces
  printf '%s' "$raw" | tr -d '[]' | tr ',' '\n' | \
    while IFS= read -r item; do
      item="${item# }"; item="${item% }"
      [ -n "$item" ] && printf '%s\n' "$item"
    done
}

# Retourne un rang numérique pour la hiérarchie des modèles (fonction interne)
# Hiérarchie : claude-opus-4(3) > claude-sonnet-4-5(2) > claude-haiku-4-5(1)
# Modèles inconnus = rang 0 — volontairement inférieur à haiku pour que le clamp
# force systématiquement le plancher quand un modèle non reconnu est résolu.
# Cela évite qu'un modèle inconnu contourne silencieusement un plancher opus/sonnet.
_get_model_rank() {
  local model="$1"
  # Extraire le nom de base (sans préfixe provider comme "anthropic/")
  local base="${model##*/}"
  case "$base" in
    claude-opus-4*)     echo 3 ;;
    claude-sonnet-4-5*) echo 2 ;;
    claude-haiku-4-5*)  echo 1 ;;
    *)                  echo 0 ;;
  esac
}

# Applique le clamp (plancher) du frontmatter
# Si resolved_model < floor_model en rang → retourne floor_model + warning
# $1 = resolved_model (depuis la cascade), $2 = floor_model (depuis le frontmatter), $3 = agent_id (pour le log)
clamp_model() {
  local resolved="$1" floor="$2" agent_id="${3:-}"
  [ -z "$floor" ] && echo "$resolved" && return 0
  local rank_resolved rank_floor
  rank_resolved=$(_get_model_rank "$resolved")
  rank_floor=$(_get_model_rank "$floor")
  if [ "$rank_resolved" -lt "$rank_floor" ]; then
    # Collecter pour le récapitulatif (affiché en Phase 3 uniquement)
    _CLAMP_APPLIED_AGENTS="${_CLAMP_APPLIED_AGENTS:-}${agent_id}:${resolved}→${floor};"
    echo "$floor"
  else
    echo "$resolved"
  fi
}

# Retourne la famille d'un agent (nom du dossier parent dans agents/)
# Ex: agents/planning/orchestrator.md → "planning"
_get_agent_family() {
  local agent_file="$1"
  local dir="${agent_file%/*}"      # Équivalent dirname (bash pur, 0 subprocess)
  echo "${dir##*/}"                  # Équivalent basename
}

# Résout le modèle à utiliser pour un agent via une cascade à 7 niveaux + clamp.
# $1 = agent_file (chemin du fichier .md)
# $2 = project_id (optionnel)
# $3 = hub_agent_models (optionnel) — JSON object .agent_models.agents précalculé via tojson
#   ex: '{"orchestrator":"claude-opus-4"}' ou '{}' si la section est absente de hub.json.
# $4 = hub_family_models (optionnel) — JSON object .agent_models.families précalculé via tojson
#   ex: '{"planning":"claude-opus-4"}' ou '{}' si la section est absente.
# $5 = hub_global_model (optionnel) — string .opencode.model précalculé
# Si $3/$4/$5 sont fournis, les niveaux 4-6 lisent les valeurs en mémoire (zéro lecture hub.json).
# Si $3/$4/$5 sont vides, comportement actuel inchangé (lecture hub.json directe — rétrocompatibilité).
# Affiche le modèle résolu sur stdout.
resolve_agent_model() {
  local agent_file="$1"
  local project_id="${2:-}"
  local hub_agent_models="${3:-}"
  local hub_family_models="${4:-}"
  local hub_global_model="${5:-}"

  # Lire le frontmatter pour obtenir id et model (plancher)
  read_agent_frontmatter "$agent_file"
  local agent_id="${_fm_id:-$(basename "$agent_file" .md)}"
  local floor_model="${_fm_model:-}"
  local family
  family=$(_get_agent_family "$agent_file")

  local resolved=""
  local source=""

  # Niveaux 1-3 : projet (seulement si project_id non vide)
  if [ -n "$project_id" ]; then
    # 1. P.agents.X
    if [ -z "$resolved" ]; then
      resolved=$(_api_keys_get "$project_id" "agent_models.agents.${agent_id}")
      [ -n "$resolved" ] && source="project_agent"
    fi
    # 2. P.families.F
    if [ -z "$resolved" ]; then
      resolved=$(_api_keys_get "$project_id" "agent_models.families.${family}")
      [ -n "$resolved" ] && source="project_family"
    fi
    # 3. P.model
    if [ -z "$resolved" ]; then
      resolved=$(_api_keys_get "$project_id" "model")
      [ -n "$resolved" ] && source="project_global"
    fi
  fi

  # Niveaux 4-6 : hub.json
  # Si les valeurs précalculées sont fournies ($3/$4/$5), les utiliser directement (zéro lecture hub.json).
  # Sinon, conserver le comportement actuel (lecture hub.json directe — rétrocompatibilité).
  if [ -z "$resolved" ]; then
    if [ -n "$hub_agent_models" ] || [ -n "$hub_family_models" ] || [ -n "$hub_global_model" ]; then
      # Chemin rapide : valeurs précalculées en mémoire.
      # Note : hub_agent_models/hub_family_models peuvent valoir '{}' (objet JSON vide sérialisé)
      # quand la section correspondante est absente de hub.json. Dans ce cas le chemin rapide
      # est quand même activé, mais .[$id] // empty sur '{}' retourne vide → identique au chemin lent.
      # jq est nécessairement présent : le précalcul qui fournit ces paramètres est conditionné par command -v jq.
      if command -v jq &>/dev/null; then
        # 4. hub.agents.X — jq sur chaîne en mémoire (pas de lecture fichier)
        if [ -z "$resolved" ] && [ -n "$hub_agent_models" ]; then
          resolved=$(printf '%s' "$hub_agent_models" | jq -r --arg id "$agent_id" '.[$id] // empty' 2>/dev/null)
          [ -n "$resolved" ] && source="hub_agent"
        fi
        # 5. hub.families.F — jq sur chaîne en mémoire
        if [ -z "$resolved" ] && [ -n "$hub_family_models" ]; then
          resolved=$(printf '%s' "$hub_family_models" | jq -r --arg fam "$family" '.[$fam] // empty' 2>/dev/null)
          [ -n "$resolved" ] && source="hub_family"
        fi
      fi
      # 6. hub.model — valeur scalaire directe (zéro fork)
      if [ -z "$resolved" ]; then
        resolved="$hub_global_model"
        [ -n "$resolved" ] && source="hub_global"
      fi
    elif [ -f "$HUB_CONFIG" ]; then
      if command -v jq &>/dev/null; then
        # 4. hub.agents.X
        if [ -z "$resolved" ]; then
          resolved=$(jq -r ".agent_models.agents.\"${agent_id}\" // empty" "$HUB_CONFIG" 2>/dev/null)
          [ -n "$resolved" ] && source="hub_agent"
        fi
        # 5. hub.families.F
        if [ -z "$resolved" ]; then
          resolved=$(jq -r ".agent_models.families.\"${family}\" // empty" "$HUB_CONFIG" 2>/dev/null)
          [ -n "$resolved" ] && source="hub_family"
        fi
        # 6. hub.model
        if [ -z "$resolved" ]; then
          resolved=$(jq -r '.opencode.model // empty' "$HUB_CONFIG" 2>/dev/null)
          [ -n "$resolved" ] && source="hub_global"
        fi
      else
        # Fallback sans jq : sed pour extraire les sections puis grep la clé
        # 4. hub.agents.X — chercher agent_id dans la section "agents" de "agent_models"
        if [ -z "$resolved" ]; then
          resolved=$(sed -n '/"agent_models"/,/^[[:space:]]*}/p' "$HUB_CONFIG" 2>/dev/null \
            | sed -n '/"agents"/,/}/p' \
            | grep "\"${agent_id}\"" | head -1 \
            | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/' | grep -v '{' || true)
          [ -n "$resolved" ] && source="hub_agent"
        fi
        # 5. hub.families.F — chercher family dans la section "families" de "agent_models"
        if [ -z "$resolved" ]; then
          resolved=$(sed -n '/"agent_models"/,/^[[:space:]]*}/p' "$HUB_CONFIG" 2>/dev/null \
            | sed -n '/"families"/,/}/p' \
            | grep "\"${family}\"" | head -1 \
            | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/' | grep -v '{' || true)
          [ -n "$resolved" ] && source="hub_family"
        fi
        # 6. hub.model — chercher "model" dans la section opencode
        if [ -z "$resolved" ]; then
          resolved=$(sed -n '/"opencode"/,/}/p' "$HUB_CONFIG" 2>/dev/null | grep '"model"' | head -1 | sed 's/.*"model"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' || true)
          [ -n "$resolved" ] && source="hub_global"
        fi
      fi
    fi
  fi

  # 7. Fallback hardcodé
  if [ -z "$resolved" ]; then
    resolved="claude-sonnet-4-5"
    source="fallback"
  fi

  # Clamp
  resolved=$(clamp_model "$resolved" "$floor_model" "$agent_id")
  
  # Retourner modèle|source
  echo "${resolved}|${source}"
}

# Extrait le bloc permission du frontmatter et le convertit en JSON inline
# Supporte : scalaires directs (question: allow) et sous-blocs map (bash: { "*": deny, "cmd": allow })
# Types supportés pour sous-blocs map : bash, read, edit, write, glob, task
# Retourne une chaîne JSON partielle, ex: "\"permission\": { \"question\": \"allow\" }"
# ou vide si aucune permission n'est déclarée
# Zéro fork dans la boucle : tous les tests utilisent case/[[ =~ ]] et les extractions
# de clé/valeur utilisent des expansions de paramètre bash (pas de echo|grep/sed/cut).
# @param $1 — chemin du fichier agent (utilisé si $2 est vide)
# @param $2 — frontmatter pré-lu (optionnel, pour éviter le sed)
extract_permission_json() {
  local file="$1"
  local frontmatter="${2:-}"
  
  # Si le frontmatter n'est pas fourni, l'extraire avec sed (rétrocompatibilité)
  if [ -z "$frontmatter" ]; then
    frontmatter=$(sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d')
  fi
  
  [ -z "$frontmatter" ] && return 0

  # Détecter si un bloc permission: existe — test builtin (zéro fork)
  # Note : cherche 'permission:' en début de ligne (newline Unix). Tab en lieu de newline : edge case non supporté.
  [[ "$frontmatter" == *$'\npermission:'* || "$frontmatter" == 'permission:'* ]] || return 0

  # Extraire tous les scalaires directs sous permission: (indentation 2 espaces)
  # et les sous-blocs map (indentation 4 espaces)
  # Scalaires supportés : question, bash, edit, write, read, glob, task (format clé: valeur)
  # Sous-blocs map supportés : bash, read, edit, write, glob, task (format clé: sans valeur, puis entrées indentées)
  local in_permission=0 current_subblock=""
  local scalar_fields=""
  local bash_entries="" read_entries="" edit_entries="" write_entries="" glob_entries="" task_entries=""

  while IFS= read -r line; do
    case "$line" in
      permission:*)
        in_permission=1; current_subblock=""; continue ;;
    esac

    if [ "$in_permission" = "1" ]; then
      # Quitter le bloc permission si on revient à l'indentation racine (caractère non-espace en tête)
      case "$line" in
        [!\ ]*)  in_permission=0; current_subblock=""; continue ;;  # retour indentation racine (ligne non indentée)
      esac

      # Détecter le début d'un sous-bloc map (2 espaces + nom + : sans valeur après)
      # Pattern : "  bash:" ou "  task:" (pas de valeur après le :)
      case "$line" in
        '  bash:')   current_subblock="bash"; continue ;;
        '  read:')   current_subblock="read"; continue ;;
        '  edit:')   current_subblock="edit"; continue ;;
        '  write:')  current_subblock="write"; continue ;;
        '  glob:')   current_subblock="glob"; continue ;;
        '  task:')   current_subblock="task"; continue ;;
      esac

      if [ -n "$current_subblock" ]; then
        # Ligne d'entrée de sous-bloc : "    \"*\": deny" ou "    \"bd list\": allow"
        # LIMITATION : les clés contenant ':' ne sont pas supportées (ex: "echo: test": allow)
        # car le parsing utilise le premier ':' comme séparateur clé/valeur.
        # En pratique, les clés sont des patterns de commande ou de fichier qui ne contiennent
        # jamais ':' dans les cas d'usage réels des permissions opencode.
        case "$line" in
          '    '*)
            # Extraire clé et valeur — expansions de paramètre bash (zéro fork)
            local kv="${line#"${line%%[! ]*}"}"   # strip leading whitespace
            
            # Ignorer les commentaires YAML (lignes commençant par #)
            # Ces commentaires causent des erreurs de parsing JSON s'ils contiennent ':'
            [[ "$kv" =~ ^# ]] && continue
            
            # Si la clé est entre guillemets, on doit trouver le ':' après le guillemet fermant
            # Format attendu : "clé avec : dedans": valeur
            local k v
            if [[ "$kv" =~ ^\"([^\"]*)\":[[:space:]]*(.*) ]]; then
              # Clé entre guillemets (peut contenir ':')
              k="${BASH_REMATCH[1]}"
              v="${BASH_REMATCH[2]}"
            else
              # Clé sans guillemets (ne peut pas contenir ':')
              k="${kv%%:*}"                    # tout avant le premier ':'
              k="${k#"${k%%[! ]*}"}"           # strip leading whitespace
              k="${k%"${k##*[! ]}"}"           # strip trailing whitespace
              v="${kv#*:}"                     # tout après le premier ':'
            fi
            
            # Nettoyer la valeur
            v="${v#"${v%%[! ]*}"}"             # strip leading whitespace
            v="${v%"${v##*[! ]}"}"             # strip trailing whitespace
            v="${v#\"}"                         # strip guillemet ouvrant si présent
            v="${v%\"}"                         # strip guillemet fermant si présent
            
            if [ -n "$k" ] && [ -n "$v" ]; then
              local entry="\"${k}\": \"${v}\""
              case "$current_subblock" in
                bash)  [ -n "$bash_entries" ] && bash_entries="${bash_entries}, "; bash_entries="${bash_entries}${entry}" ;;
                read)  [ -n "$read_entries" ] && read_entries="${read_entries}, "; read_entries="${read_entries}${entry}" ;;
                edit)  [ -n "$edit_entries" ] && edit_entries="${edit_entries}, "; edit_entries="${edit_entries}${entry}" ;;
                write) [ -n "$write_entries" ] && write_entries="${write_entries}, "; write_entries="${write_entries}${entry}" ;;
                glob)  [ -n "$glob_entries" ] && glob_entries="${glob_entries}, "; glob_entries="${glob_entries}${entry}" ;;
                task)  [ -n "$task_entries" ] && task_entries="${task_entries}, "; task_entries="${task_entries}${entry}" ;;
              esac
            fi
            ;;
          *)
            # Fin du sous-bloc (ligne non indentée à 4 espaces)
            current_subblock="" ;;
        esac
      fi

      # Scalaire direct sous permission: (2 espaces, pas dans un sous-bloc, format "clé: valeur")
      if [ -z "$current_subblock" ] && [[ "$line" =~ ^[[:space:]][[:space:]][a-zA-Z][a-zA-Z0-9_-]*:[[:space:]] ]]; then
        local sk="${line#  }"     # strip les 2 espaces d'indentation
        sk="${sk%%:*}"             # tout avant le premier ':'
        sk="${sk%"${sk##*[! ]}"}" # strip trailing whitespace
        local sv="${line#*:}"     # tout après le premier ':'
        sv="${sv#"${sv%%[! ]*}"}" # strip leading whitespace
        sv="${sv%%#*}"             # strip commentaire YAML (tout après #)
        sv="${sv%"${sv##*[! ]}"}" # strip trailing whitespace
        if [ -n "$sk" ] && [ -n "$sv" ]; then
          [ -n "$scalar_fields" ] && scalar_fields="${scalar_fields}, "
          scalar_fields="${scalar_fields}\"${sk}\": \"${sv}\""
        fi
      fi
    fi
  done <<< "$frontmatter"

  # Construire le JSON de permission
  local perm_fields="${scalar_fields}"
  
  # Ajouter chaque sous-bloc non vide comme objet JSON
  if [ -n "$bash_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"bash\": { ${bash_entries} }"
  fi
  if [ -n "$read_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"read\": { ${read_entries} }"
  fi
  if [ -n "$edit_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"edit\": { ${edit_entries} }"
  fi
  if [ -n "$write_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"write\": { ${write_entries} }"
  fi
  if [ -n "$glob_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"glob\": { ${glob_entries} }"
  fi
  if [ -n "$task_entries" ]; then
    [ -n "$perm_fields" ] && perm_fields="${perm_fields}, "
    perm_fields="${perm_fields}\"task\": { ${task_entries} }"
  fi

  if [ -n "$perm_fields" ]; then
    echo "\"permission\": { ${perm_fields} }"
  fi
}

# Retourne le contenu d'un fichier Markdown en ignorant le bloc frontmatter YAML
# Utilise le builtin read pour détecter "---" en première ligne (zéro fork).
# Le || true est intentionnel : IFS= read -r retourne exit 1 sur EOF (fichier vide),
# ce qui ferait planter la fonction sous set -euo pipefail sans ce guard.
strip_frontmatter() {
  local file="$1"
  local _first_line
  IFS= read -r _first_line < "$file" || true  # EOF retourne exit 1 — || true : safe avec set -e
  if [[ "$_first_line" = "---" ]]; then
    awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file"
  else
    cat "$file"
  fi
}

# Retourne le mode de déploiement d'un agent (frontmatter mode:)
# Valeurs possibles : "primary" | "subagent" | "all"
# Fallback : "primary" si le champ est absent
get_agent_mode() {
  local mode
  mode=$(extract_frontmatter_value "$1" "mode")
  echo "${mode:-primary}"
}

# Retourne l'identifiant d'un agent (frontmatter id, ou nom de fichier sans extension)
get_agent_id() {
  local id
  id=$(extract_frontmatter_value "$1" "id")
  if [ -z "$id" ]; then
    basename "$1" .md
  else
    echo "$id"
  fi
}

# Détecte la stack d'un projet à partir de ses fichiers de dépendances.
# @param $1 — project_path (chemin racine du projet)
# Affiche sur stdout une liste de clés de stack, une par ligne.
# Clés possibles : typescript, python, vue, react, next, nuxt, angular,
#   nestjs, express, fastify, django, fastapi, laravel, rails, spring,
#   prisma, typeorm, sqlalchemy, mongoose,
#   vitest, jest, playwright, cypress, openapi,
#   react-native, flutter, swift, kotlin,
#   pandas, dbt, airflow, pyspark,
#   docker, github-actions, gitlab-ci,
#   terraform, kubernetes, helm, argocd
detect_stack() {
  local project_path="${1:-}"
  [ -z "$project_path" ] || [ ! -d "$project_path" ] && return 0

  local pkg_json="${project_path}/package.json"
  local pyproject="${project_path}/pyproject.toml"
  local requirements="${project_path}/requirements.txt"
  local gemfile="${project_path}/Gemfile"
  local build_gradle="${project_path}/build.gradle"
  local build_gradle_kts="${project_path}/build.gradle.kts"
  local pom_xml="${project_path}/pom.xml"
  local pubspec="${project_path}/pubspec.yaml"

  # Répertoires à exclure des find (node_modules, dist, build, .git, .nuxt...)
  # shellcheck disable=SC2054
  local _prune_args=( \( -name "node_modules" -o -name ".git" -o -name "dist" -o -name "build"
                         -o -name ".nuxt" -o -name ".output" -o -name ".next" -o -name "__pycache__"
                         -o -name ".venv" -o -name "venv" -o -name "vendor" \) -prune -o )

  # ── JavaScript / TypeScript (package.json) ──────────────────────────────
  if [ -f "$pkg_json" ]; then
    local deps=""
    deps=$(grep -E '"dependencies"|"devDependencies"' -A 9999 "$pkg_json" 2>/dev/null | \
           grep -oE '"[a-zA-Z@][a-zA-Z0-9@/_-]*"[[:space:]]*:' | tr -d '"' | tr -d ':' | tr -d ' ')

    # Langage
    echo "$deps" | grep -q 'typescript' && echo "typescript" || true

    # Frontend frameworks
    { echo "$deps" | grep -qE '^next$'; } && echo "next" && echo "react" || true
    { echo "$deps" | grep -qE '^nuxt$'; } && echo "nuxt" && echo "vue" || true
    { echo "$deps" | grep -qE '^@vue/core$|^vue$' && ! echo "$deps" | grep -q '^nuxt$'; } && echo "vue" || true
    { echo "$deps" | grep -qE '^react$' && ! echo "$deps" | grep -q '^next$'; } && echo "react" || true
    echo "$deps" | grep -qE '^@angular/core$' && echo "angular" || true

    # Backend frameworks
    echo "$deps" | grep -qE '^@nestjs/core$' && echo "nestjs" || true
    echo "$deps" | grep -qE '^express$' && echo "express" || true
    echo "$deps" | grep -qE '^fastify$' && echo "fastify" || true

    # ORMs / BDD
    echo "$deps" | grep -qE '^@prisma/client$|^prisma$' && echo "prisma" || true
    echo "$deps" | grep -qE '^typeorm$' && echo "typeorm" || true
    echo "$deps" | grep -qE '^mongoose$' && echo "mongoose" || true

    # Outils de test
    echo "$deps" | grep -qE '^vitest$' && echo "vitest" || true
    echo "$deps" | grep -qE '^jest$|^@jest/core$' && echo "jest" || true
    echo "$deps" | grep -qE '^@playwright/test$|^playwright$' && echo "playwright" || true
    echo "$deps" | grep -qE '^cypress$' && echo "cypress" || true

    # Spec API
    if [ -f "${project_path}/openapi.yaml" ] || \
       [ -f "${project_path}/openapi.yml" ] || \
       [ -f "${project_path}/swagger.yaml" ] || \
       [ -f "${project_path}/docs/openapi.yaml" ] || \
       [ -f "${project_path}/docs/api/openapi.yaml" ]; then
      echo "openapi"
    fi

    # Mobile
    echo "$deps" | grep -qE '^react-native$' && echo "react-native" || true
  fi

  # ── Python (pyproject.toml / requirements.txt) ──────────────────────────
  if [ -f "$pyproject" ] || [ -f "$requirements" ]; then
    echo "python"

    local py_deps=""
    [ -f "$pyproject" ] && py_deps=$(cat "$pyproject" 2>/dev/null)
    [ -f "$requirements" ] && py_deps="${py_deps}$(cat "$requirements" 2>/dev/null)"

    echo "$py_deps" | grep -qiE 'django' && echo "django" || true
    echo "$py_deps" | grep -qiE 'fastapi' && echo "fastapi" || true
    echo "$py_deps" | grep -qiE 'sqlalchemy' && echo "sqlalchemy" || true
    echo "$py_deps" | grep -qiE '^pandas|pandas==' && echo "pandas" || true
    echo "$py_deps" | grep -qiE '^dbt-|dbt==' && echo "dbt" || true
    echo "$py_deps" | grep -qiE 'apache-airflow|airflow' && echo "airflow" || true
    echo "$py_deps" | grep -qiE 'pyspark' && echo "pyspark" || true
  fi

  # ── Ruby (Gemfile) ───────────────────────────────────────────────────────
  if [ -f "$gemfile" ]; then
    grep -q 'rails' "$gemfile" 2>/dev/null && echo "rails" || true
  fi

  # ── Java / Kotlin (build.gradle / pom.xml) ───────────────────────────────
  if [ -f "$build_gradle" ] || [ -f "$build_gradle_kts" ] || [ -f "$pom_xml" ]; then
    local jvm_deps=""
    [ -f "$build_gradle" ] && jvm_deps=$(cat "$build_gradle" 2>/dev/null)
    [ -f "$build_gradle_kts" ] && jvm_deps="${jvm_deps}$(cat "$build_gradle_kts" 2>/dev/null)"
    [ -f "$pom_xml" ] && jvm_deps="${jvm_deps}$(cat "$pom_xml" 2>/dev/null)"

    echo "$jvm_deps" | grep -qiE 'spring-boot|spring.boot' && echo "spring" || true
    echo "$jvm_deps" | grep -qiE 'jetpack.compose|compose.bom' && echo "kotlin" || true
  fi

  # ── Dart / Flutter (pubspec.yaml) ────────────────────────────────────────
  if [ -f "$pubspec" ]; then
    grep -q 'flutter' "$pubspec" 2>/dev/null && echo "flutter" || true
  fi

  # ── Infrastructure (fichiers de config) ──────────────────────────────────
  { [ -f "${project_path}/Dockerfile" ] || [ -f "${project_path}/docker-compose.yml" ] || \
    [ -f "${project_path}/docker-compose.yaml" ]; } && echo "docker" || true
  { [ -d "${project_path}/.github/workflows" ]; } && echo "github-actions" || true
  { [ -f "${project_path}/.gitlab-ci.yml" ]; } && echo "gitlab-ci" || true

  # Terraform — prune les dossiers lourds
  { find "$project_path" "${_prune_args[@]}" -name "*.tf" -print 2>/dev/null | grep -q .; } && echo "terraform" || true

  # Kubernetes — grep récursif (un seul processus au lieu d'un fork par fichier YAML)
  { grep -rql --include="*.yaml" --include="*.yml" \
      -e 'kind: Deployment' -e 'kind: Service' -e 'kind: Ingress' \
      --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist \
      --exclude-dir=build --exclude-dir=.next --exclude-dir=.nuxt \
      --exclude-dir=.output --exclude-dir=__pycache__ --exclude-dir=.venv \
      --exclude-dir=venv --exclude-dir=vendor \
      "$project_path" 2>/dev/null; } && echo "kubernetes" || true

  # Helm — prune
  { [ -f "${project_path}/Chart.yaml" ] || \
    find "$project_path" "${_prune_args[@]}" -name "Chart.yaml" -print 2>/dev/null | grep -q .; } && echo "helm" || true

  # ArgoCD — grep récursif (un seul processus au lieu d'un fork par fichier YAML)
  { grep -rql --include="*.yaml" --include="*.yml" \
      -e 'argoproj.io' -e 'kind: Application' \
      --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist \
      --exclude-dir=build --exclude-dir=.next --exclude-dir=.nuxt \
      --exclude-dir=.output --exclude-dir=__pycache__ --exclude-dir=.venv \
      --exclude-dir=venv --exclude-dir=vendor \
      "$project_path" 2>/dev/null; } && echo "argocd" || true
}

# Résout la liste des skills stack à injecter pour un agent donné.
# @param $1 — agent_id (ex: developer-frontend)
# @param $2 — stacks_list (liste de clés séparées par des espaces ou newlines)
# @param $3 — stack_skills_config (chemin vers config/stack-skills.json)
# Affiche sur stdout les chemins de skills à injecter, un par ligne, dédupliqués.
resolve_stack_skills() {
  local agent_id="$1"
  local stacks_list="$2"
  local config_file="$3"

  [ -z "$stacks_list" ] && return 0
  [ -f "$config_file" ] || return 0
  command -v jq &>/dev/null || return 0  # jq requis pour parser le JSON

  # Récupérer les catégories autorisées pour cet agent
  local allowed_categories
  allowed_categories=$(jq -r --arg agent "$agent_id" \
    '._agent_scope[$agent] // [] | .[]' "$config_file" 2>/dev/null)

  # Si pas de scope défini pour cet agent, ne rien injecter
  [ -z "$allowed_categories" ] && return 0

  local seen=()
  local stack

  while IFS= read -r stack; do
    [ -z "$stack" ] && continue

    # Pour chaque catégorie autorisée, chercher si la stack y est mappée
    local category
    while IFS= read -r category; do
      [ -z "$category" ] && continue

      # Chercher la stack dans cette catégorie
      local skills
      skills=$(jq -r --arg cat "$category" --arg stack "$stack" \
        '.[$cat][$stack] // [] | .[]' "$config_file" 2>/dev/null)

      [ -z "$skills" ] && continue

      # Ajouter les skills non encore vus
      local skill
      while IFS= read -r skill; do
        [ -z "$skill" ] && continue
        local already_seen=0
        local s
        for s in "${seen[@]:-}"; do
          [ "$s" = "$skill" ] && already_seen=1 && break
        done
        if [ "$already_seen" = "0" ]; then
          seen+=("$skill")
          echo "$skill"
        fi
      done <<< "$skills"
    done <<< "$allowed_categories"
  done <<< "$stacks_list"
}

# Précalcule en une seule passe jq tous les stack skills pour une liste de stacks détectées.
# Retourne une chaîne "agent_id:skill_path\n..." utilisable par _get_precomputed_stack_skills.
# Signature : precompute_stack_skills STACKS_NEWLINE_SEP CONFIG_FILE
# Exemple d'usage :
#   _cached=$(precompute_stack_skills "$detected_stacks" config/stack-skills.json)
#   while IFS= read -r sk; do ...; done < <(_get_precomputed_stack_skills "developer-api" "$_cached")
precompute_stack_skills() {
  local stacks_list="$1"
  local config_file="$2"

  [ -z "$stacks_list" ] && return 0
  [ -f "$config_file" ] || return 0
  command -v jq &>/dev/null || return 0

  # Construire un tableau jq de stacks depuis la liste bash (une seule invocation jq — zéro fork supplémentaire)
  local stacks_json
  stacks_json=$(printf '%s\n' "$stacks_list" | jq -Rs '[split("\n")[] | select(. != "")]')

  # En une seule invocation jq : pour chaque agent qui a un _agent_scope,
  # parcourir les catégories autorisées, puis les stacks détectées,
  # et émettre "agent_id:skill_path" pour chaque skill trouvé.
  jq -r --argjson stacks "$stacks_json" '
    . as $conf |
    ($conf._agent_scope // {}) | to_entries[] |
    select(.value | type == "array") |
    .key as $agent |
    .value[] as $cat |
    $stacks[] as $stack |
    ($conf[$cat][$stack] // [])[] |
    "\($agent):\(.)"
  ' "$config_file" 2>/dev/null | sort -u || true
}

# Filtre les lignes "agent_id:skill" précalculées pour un agent donné.
# Signature : _get_precomputed_stack_skills AGENT_ID PRECOMPUTED_STRING
_get_precomputed_stack_skills() {
  local agent_id="$1"
  local precomputed="$2"
  [ -z "$precomputed" ] && return 0
  local prefix="${agent_id}:"
  while IFS= read -r line; do
    [ "${line#"$prefix"}" != "$line" ] && printf '%s\n' "${line#"$prefix"}"
  done <<< "$precomputed"
}

# Retourne le nom d'une skill au format opencode (kebab-case, basename sans .md)
# Conforme à la contrainte de nommage opencode : ^[a-z0-9]+(-[a-z0-9]+)*$
# Ex: developer/stacks/dev-standards-vuejs → dev-standards-vuejs
# Ex: auditor/audit-security               → audit-security
to_skill_name() {
  local skill_path="$1"
  basename "$skill_path" .md
}

# Génère la section "## Skills disponibles" dans le body de l'agent.
# Liste les skills natives chargeable à la demande via l'outil skill d'opencode.
# @param $@ — liste de chemins de skills relatifs à SKILLS_DIR
#             (ex: "developer/dev-standards-frontend" "developer/stacks/dev-standards-vuejs")
_build_native_skills_guide() {
  [ $# -eq 0 ] && return 0
  local _native_list=("$@")

  echo ""
  echo "---"
  echo ""
  echo "## Skills disponibles"
  echo ""
  echo "Charge les skills pertinentes **avant de commencer** via l'outil \`skill\`."
  echo "Sélectionne uniquement celles qui correspondent au contexte de la tâche en cours."
  echo ""
  echo "| Skill | Description |"
  echo "|-------|-------------|"

  local skill skill_name skill_file desc
  for skill in "${_native_list[@]}"; do
    [ -z "$skill" ] && continue
    skill_name=$(to_skill_name "$skill")
    skill_file="$SKILLS_DIR/${skill}.md"
    if [ -f "$skill_file" ]; then
      desc=$(extract_frontmatter_value "$skill_file" "description")
    else
      desc=""
    fi
    [ -z "$desc" ] && desc="—"
    echo "| \`${skill_name}\` | ${desc} |"
  done
}

# Construit le contenu final : corps de l'agent + skills injectés → stdout
# $2 (lang) optionnel — si non vide, injecte une instruction de langue en tête de l'agent
# $3 (project_path) optionnel — si non vide, détecte la stack et prépare les skills stack
# $4 (precomputed_stacks) optionnel — si non vide, utilise les stack skills précalculés (chemin rapide)
#   fourni par adapter_deploy_files via precompute_stack_skills ; zéro fork supplémentaire.
#   Si vide, fallback sur detect_stack + resolve_stack_skills (rétrocompatibilité).
#   Note : ignoré silencieusement si $3 (project_path) est vide ou inexistant.
#
# Architecture hybride :
#   - skills:        → inlinées dans le body (Bucket A, obligatoires, toujours actives)
#   - native_skills: → listées dans le guide "Skills disponibles" (Bucket B, chargement à la demande)
#   - stack skills   → listées dans le guide "Skills disponibles" (Bucket B, dynamiques)
build_agent_content() {
  local agent_file="$1"
  local lang="${2:-}"
  local project_path="${3:-}"
  local precomputed_stacks="${4:-}"
  [ -f "$agent_file" ] || { log_warn "Agent introuvable : $agent_file" >&2; return 1; }

  build_generated_header
  echo ""
  if [ -n "$lang" ]; then
    echo "> **Langue de travail : ${lang}.** Rédige toutes tes réponses, rapports et commentaires en ${lang}, quelle que soit la langue des instructions ci-dessous."
    echo ""
  fi
  strip_frontmatter "$agent_file"

  # ── Skills INLINE : déclarés dans le frontmatter (Bucket A — obligatoires) ──
  # Ces skills sont injectées directement dans le system prompt de l'agent.
  # Le LLM les reçoit TOUJOURS — protocoles, workflows, handoffs, chaînes de délégation.
  local skills=()
  while IFS= read -r skill; do
    skills+=("$skill")
  done < <(extract_frontmatter_list "$agent_file" "skills")

  # ── Skills NATIVES : déclarées dans le frontmatter (Bucket B — optionnelles) ──
  # Ces skills sont déployées dans .opencode/skills/<name>/SKILL.md et chargées à la demande.
  # Elles n'apparaissent PAS dans le system prompt — seulement dans le guide ci-dessous.
  local native_skills_from_fm=()
  while IFS= read -r ns; do
    native_skills_from_fm+=("$ns")
  done < <(extract_frontmatter_list "$agent_file" "native_skills")

  # ── Stack skills : résolues dynamiquement (Bucket B — optionnelles) ──────────
  # Déployées en .opencode/skills/ selon la stack détectée dans le projet cible.
  # Ne sont plus inlinées depuis la migration vers l'architecture hybride.
  local stack_skills=()
  if [ -n "$project_path" ] && [ -d "$project_path" ]; then
    local agent_id
    agent_id=$(get_agent_id "$agent_file")
    local stack_skills_config="${HUB_DIR:-}/config/stack-skills.json"
    if [ -f "$stack_skills_config" ]; then
      if [ -n "$precomputed_stacks" ]; then
        # Chemin rapide : utiliser les stack skills précalculés
        while IFS= read -r stack_skill; do
          [ -z "$stack_skill" ] && continue
          # Dédupliquer contre les skills déjà déclarées (inline ou native)
          local already_declared=0
          local declared_skill
          for declared_skill in "${skills[@]:-}" "${native_skills_from_fm[@]:-}"; do
            [ "$declared_skill" = "$stack_skill" ] && already_declared=1 && break
          done
          [ "$already_declared" = "0" ] && stack_skills+=("$stack_skill")
        done < <(_get_precomputed_stack_skills "$agent_id" "$precomputed_stacks")
      else
        # Chemin lent (rétrocompatibilité) : détecter la stack à la volée
        local detected_stacks
        detected_stacks=$(detect_stack "$project_path" | sort -u || true)
        if [ -n "$detected_stacks" ]; then
          while IFS= read -r stack_skill; do
            [ -z "$stack_skill" ] && continue
            local already_declared=0
            local declared_skill
            for declared_skill in "${skills[@]:-}" "${native_skills_from_fm[@]:-}"; do
              [ "$declared_skill" = "$stack_skill" ] && already_declared=1 && break
            done
            [ "$already_declared" = "0" ] && stack_skills+=("$stack_skill")
          done < <(resolve_stack_skills "$agent_id" "$detected_stacks" "$stack_skills_config")
        fi
      fi
    fi
  fi

  # ── Injection des skills INLINE (obligatoires) ───────────────────────────────
  if [ ${#skills[@]} -gt 0 ]; then
    echo ""
    echo "---"
    echo ""
    for skill in "${skills[@]}"; do
      [ -z "$skill" ] && continue
      local skill_file="$SKILLS_DIR/${skill}.md"
      if [ -f "$skill_file" ]; then
        strip_frontmatter "$skill_file"
        echo ""
      else
        log_warn "Skill introuvable : ${skill}.md" >&2
      fi
    done
  fi

  # ── Guide des skills natives (Bucket B — chargement à la demande) ────────────
  # Injecte un tableau listant les skills natives + stack skills disponibles.
  # Le LLM voit la liste mais charge uniquement les skills utiles via l'outil `skill`.
  local all_native=("${native_skills_from_fm[@]:-}" "${stack_skills[@]:-}")
  if [ ${#all_native[@]} -gt 0 ]; then
    _build_native_skills_guide "${all_native[@]}"
  fi
}

# Construit le prompt de bootstrap pour le mode --dev (oc start --dev)
# Interroge bd ready dans le répertoire du projet
# @param $1 — project_path
# @param $2 — label (optionnel, défaut : "ai-delegated")
# @param $3 — assignee (optionnel, si fourni filtre par assignee au lieu du label)
build_dev_bootstrap_prompt() {
  local project_path="$1"
  local label="${2:-ai-delegated}"
  local assignee="${3:-}"
  local tickets

  if [ -n "$assignee" ]; then
    tickets=$(cd "$project_path" && bd ready --assignee "$assignee" --json 2>/dev/null) || tickets="[]"
  else
    tickets=$(cd "$project_path" && bd ready --label "$label" --json 2>/dev/null) || tickets="[]"
  fi
  # Valider que la sortie est un JSON array — si bd retourne du texte d'erreur, ignorer
  if [ -z "$tickets" ] || [[ "$tickets" != \[* ]]; then
    tickets="[]"
  fi

  local filter_desc
  if [ -n "$assignee" ]; then
    filter_desc="assigné à \"${assignee}\""
  else
    filter_desc="label \"${label}\""
  fi

  if [ "$tickets" = "[]" ] || [ "$tickets" = "null" ]; then
    cat <<EOF
Aucun ticket avec le ${filter_desc} n'est prêt à implémenter.

Pour déléguer un ticket à l'agent :
  bd label add <ID> ${label}

Pour voir tous les tickets ouverts :
  bd list -s open --json
EOF
  else
    cat <<EOF
Voici les tickets délégués à l'agent (${filter_desc}, statut ready) :

${tickets}

Workflow obligatoire :
1. bd show <ID>                  — lire le détail complet avant tout
2. bd update <ID> --claim        — clamer le ticket (atomique)
3. Implémenter + tester
4. bd update <ID> -s review      — passer en review
5. bd close <ID> --suggest-next  — clore après validation et passer au suivant

Commence par le ticket le plus prioritaire.
EOF
  fi
}

# Construit le prompt de bootstrap pour la commande oc audit
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — audit_type (optionnel — vide = audit global)
build_audit_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local audit_type="${3:-}"
  local scope_line=""
  [ -n "$audit_type" ] && scope_line="Périmètre : audit ${audit_type} uniquement."

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  cat <<EOF
Effectue un audit du projet.

${project_info}
${scope_line:+
${scope_line}}
PHASE 1 — Contexte projet (OBLIGATOIRE avant toute délégation aux sous-agents)

Si le fichier ONBOARDING.md existe à la racine du projet :
  → Le lire en priorité — il contient déjà la stack, la structure et les points d'attention
  → Annoncer : "Contexte projet chargé depuis ONBOARDING.md" suivi d'un résumé en 1-2 phrases

Sinon, reconnaissance rapide (3-4 fichiers uniquement) :
  → Lire le fichier de dépendances racine (package.json, composer.json, requirements.txt…)
  → Inspecter la structure des répertoires principaux (src/, app/, etc.)
  → Identifier 1-2 fichiers de config pertinents selon le type d'audit (.env.example, nginx.conf…)
  → Résumer en 5 lignes : stack, répertoires principaux, points d'attention immédiats visibles

PHASE 2 — Délégation aux sous-agents

Déléguer aux sous-agents appropriés en leur passant le résumé du contexte (Phase 1) en préambule.
Chaque sous-agent travaille en lecture seule et produit un rapport structuré.
EOF
}

# Construit le prompt de bootstrap pour le mode --onboard (oc start --onboard)
# Déclenche l'agent onboarder en lecture seule sur le projet
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — hub_dir (optionnel — défaut : $HUB_DIR)
build_onboard_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local hub_dir="${3:-${HUB_DIR:-}}"
  local projects_file="${hub_dir:+${hub_dir}/projects/projects.md}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  local hub_info=""
  if [ -n "$hub_dir" ] && [ -n "$projects_file" ]; then
    hub_info="
Hub : ${hub_dir}
projects.md : ${projects_file}"
  fi

  cat <<EOF
Effectue une exploration complète du projet pour produire un rapport de contexte enrichi.

${project_info}${hub_info}

Workflow (6 phases) :
1. PHASE 0 — Vérifier les prérequis (projet accessible, fichiers structurants)
2. PHASE 1 — Explorer le projet de manière adaptative :
   - ÉTAPE 1.1 : Détecter la stack (langages, frameworks, bases de données, infra)
   - ÉTAPE 1.2 : Explorer selon le profil détecté (frontend/backend/fullstack/data/mobile/devops)
   - ÉTAPE 1.3 : Lire les tickets Beads (bd list -s open) + ADRs si disponibles
   - ÉTAPE 1.4 : Analyser le contexte métier (domaine, utilisateurs, concepts clés, glossaire)
   - ÉTAPE 1.5 : Explorer Figma si frontend (maquettes, design system, design tokens)
   - ÉTAPE 1.6 : Analyser la stratégie de test (frameworks, couverture, philosophie TDD/BDD)
3. PHASE 2 — Poser les questions de clarification (stratégie projet, conventions ambiguës, zones d'ombre, métier, tests, Figma)
4. PHASE 3 — Produire le rapport de contexte structuré (stack, architecture, contexte métier, design, tests, points d'attention, zones d'ombre, agents recommandés)
5. PHASE 4 — Détecter les cas particuliers (incohérences, CVE, dette masquée, architecture hybride)
6. PHASE 5 — Produire les livrables :
   - Écrire ONBOARDING.md à la racine du projet (7 sections : Stack, Architecture, Contexte métier, Design et maquettes, Stratégie de test, Points critiques/importants/améliorations, Zones d'ombre)
   - Écrire CONVENTIONS.md à la racine du projet (y compris section Design tokens si extraits depuis Figma)
   - Ajouter ces fichiers au .git/info/exclude (exclusion locale uniquement)
   - Si le champ Stack est absent/incomplet dans projects.md, proposer la mise à jour (confirmation explicite requise)

Règles strictes :
- Lecture seule — tu ne modifies aucun fichier du projet (sauf ONBOARDING.md, CONVENTIONS.md et .git/info/exclude en Phase 5)
- Rapport honnête : signaler les points critiques (🔴), importants (🟠), améliorations (🟡) avec observations concrètes
- Zones d'ombre explicites : ce qui n'a pas pu être déterminé
- Conventions basées sur fichiers réellement lus — ne jamais inventer
- Phase 1.5 (Figma) : optionnelle, déclenchée uniquement si frontend détecté
- Ne jamais modifier .gitignore — utiliser uniquement .git/info/exclude
- Produire le rapport complet dans la conversation AVANT d'écrire les fichiers
EOF
}

# Construit le prompt de bootstrap pour la commande oc review
# Exécute git diff main...<branch> et injecte le résultat dans le prompt
# @param $1 — project_path
# @param $2 — project_id
# @param $3 — branch (branche à reviewer)
build_review_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local branch="${3:-}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  # Générer le diff git main...<branch>
  local diff_content=""
  local diff_cmd="git diff main...${branch}"
  if diff_content=$(git -C "$project_path" diff "main...${branch}" 2>/dev/null); then
    if [ -z "$diff_content" ]; then
      diff_content="(aucune différence détectée entre main et ${branch})"
    fi
  else
    # Fallback : essayer sans les trois points (branche sans ancêtre commun avec main)
    diff_content=$(git -C "$project_path" diff "main..${branch}" 2>/dev/null || echo "(impossible de générer le diff — vérifier que la branche '${branch}' et 'main' existent)")
    diff_cmd="git diff main..${branch}"
  fi

  # Vérifier l'existence de CONVENTIONS.md et ONBOARDING.md
  local conventions_hint=""
  if [ -f "${project_path}/CONVENTIONS.md" ]; then
    conventions_hint="
→ Lire CONVENTIONS.md à la racine du projet avant la review (prime sur les standards génériques)"
  fi

  local onboarding_hint=""
  if [ -f "${project_path}/ONBOARDING.md" ]; then
    onboarding_hint="
→ ONBOARDING.md disponible — consulter pour le contexte du projet si nécessaire"
  fi

  cat <<EOF
Effectue une code review de la branche \`${branch}\`.

${project_info}
Branche reviewée : ${branch}
Commande diff utilisée : ${diff_cmd}
${conventions_hint}${onboarding_hint}

--- DIFF ---

${diff_content}

--- FIN DU DIFF ---

Workflow :
1. Si CONVENTIONS.md existe à la racine → le lire pour appliquer les conventions réelles du projet
2. Analyser le diff ci-dessus selon la checklist systématique du skill review-protocol
3. Produire le rapport structuré par sévérité : Critique → Majeur → Mineur → Suggestion → Points positifs

Rappel :
- Tu fournis un avis de review, tu ne modifies pas de fichiers
- Calibre les commentaires au scope réel du diff (pas de refactoring hors-scope)
EOF
}

# Construit le prompt de bootstrap pour la commande oc conventions
# Déclenche la détection ciblée des conventions du projet → CONVENTIONS.md
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — hub_dir (optionnel)
build_conventions_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local hub_dir="${3:-${HUB_DIR:-}}"
  local projects_file="${hub_dir:+${hub_dir}/projects/projects.md}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  local hub_info=""
  if [ -n "$hub_dir" ] && [ -n "$projects_file" ]; then
    hub_info="
Hub : ${hub_dir}
projects.md : ${projects_file}"
  fi

  cat <<EOF
Détecte et documente les conventions de développement de ce projet dans CONVENTIONS.md.

${project_info}${hub_info}

Workflow :
1. Annoncer ce qui va être lu
2. ÉTAPE 1 — Lire les configs linting/formatting
   (.eslintrc*, eslint.config.*, .prettierrc*, .editorconfig, biome.json, ruff.toml, etc.)
3. ÉTAPE 2 — Lire la config langage et typage
   (tsconfig.json, pyproject.toml, go.mod, etc.)
4. ÉTAPE 3 — Lire les dépendances et libs choisies
   (package.json, pyproject.toml, Gemfile, etc.)
5. ÉTAPE 4 — Lire les conventions Git
   (.commitlintrc*, .husky/, CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md)
   + git log --oneline -20 pour observer les conventions réelles
6. ÉTAPE 5 — Inférer le nommage depuis 5 à 10 fichiers représentatifs de la codebase
   (composants, services, tests, stores — selon le profil du projet)
7. ÉTAPE 6 — Lire les configs de test
   (vitest.config.*, jest.config.*, pytest.ini, playwright.config.*, etc.)
8. ÉTAPE 7 — Écrire CONVENTIONS.md à la racine du projet
   ⚠️ Si CONVENTIONS.md existe déjà → afficher la date du fichier existant et demander confirmation
   avant d'écraser ("Écraser / Conserver l'existant")
    Ajouter CONVENTIONS.md au .git/info/exclude s'il n'y est pas déjà
    (ne pas modifier le .gitignore du projet — exclusion locale uniquement)

Règles :
- Baser chaque convention sur un fichier réellement lu — ne jamais inventer
- Signaler les incohérences détectées (ex: config lint ≠ pratique observée dans le code)
- Section "Zones d'ombre" pour ce qui n'a pas pu être déterminé
- Ne pas modifier d'autres fichiers du projet
EOF
}

# Construit le prompt de bootstrap pour la commande oc debug
# Lance l'agent debugger en mode interactif sur le projet
# @param $1 — project_path
# @param $2 — project_id (optionnel)
build_debug_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  # Vérifier l'existence de CONVENTIONS.md
  local conventions_hint=""
  if [ -f "${project_path}/CONVENTIONS.md" ]; then
    conventions_hint="
→ CONVENTIONS.md disponible — consulter pour les conventions du projet"
  fi

  cat <<EOF
Session de debug sur le projet.

${project_info}
${conventions_hint}

Attends les instructions de l'utilisateur pour commencer le debug.
L'utilisateur décrira le bug ou le comportement inattendu à investiguer.
EOF
}
