package cmd

import (
	"fmt"
	"os"

	"path/filepath"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"

	"github.com/datichb/openhub/cli/internal/config"
	"github.com/datichb/openhub/cli/internal/hubcontent"
	"github.com/datichb/openhub/cli/internal/i18n"
	"github.com/datichb/openhub/cli/internal/tui/common"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialise oh pour la première fois",
	Long: `Lance un wizard de configuration pour initialiser le hub et enregistrer le premier projet.

Le wizard configure :
  - La langue de l'interface
  - La vérification/installation d'opencode
  - Le projet complet (nom, chemin, langage, provider, agents, MCP)
  - Le déploiement automatique`,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()

	fmt.Fprintln(os.Stdout)
	fmt.Fprintln(os.Stdout, common.Title.Render(i18n.T("cmd.init.welcome")))
	fmt.Fprintln(os.Stdout)

	// ── Step 1: Language + Opencode version ──
	var (
		language    string
		opencodeVer string
	)

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				Title(i18n.T("cmd.init.language_select")).
				Options(
					huh.NewOption("Français", "fr"),
					huh.NewOption("English", "en"),
				).
				Value(&language),

			huh.NewInput().
				Title(i18n.T("cmd.init.opencode_version")).
				Description(i18n.T("cmd.init.opencode_version_desc")).
				Placeholder("latest").
				Value(&opencodeVer),
		).Title(i18n.T("cmd.init.global_config")),
	)
	if err := form.Run(); err != nil {
		return err
	}

	if opencodeVer == "" {
		opencodeVer = "latest"
	}

	// ── Write hub.toml ──
	cfgDir := config.HubDir()
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}

	tomlContent := buildInitConfig(language, opencodeVer, nil)
	cfgPath := config.ConfigPath()
	if err := os.WriteFile(cfgPath, []byte(tomlContent), 0o600); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Fprintf(os.Stdout, "%s %s\n",
		common.SuccessStyle.Render(common.IconSuccess), i18n.Tf("cmd.init.config_written", cfgPath))

	// ── Step 2: Ensure opencode ──
	config.Reset()
	if err := initApp(); err != nil {
		return err
	}

	a := MustApp()
	if err := ensureOpencode(a); err != nil {
		return err
	}

	// ── Step 3: Extract hub content ──
	hubContentDir := hubcontent.HubContentDir()
	if err := hubcontent.Extract(hubContentDir); err != nil {
		return fmt.Errorf("extracting hub content: %w", err)
	}
	fmt.Fprintf(os.Stdout, "%s %s\n",
		common.SuccessStyle.Render(common.IconSuccess),
		i18n.Tf("cmd.init.hub_extracted", hubContentDir))

	// ── Step 4 (optional): Configure first project ──
	fmt.Fprintln(os.Stdout)

	var addProject bool
	if err := huh.NewConfirm().
		Title(i18n.T("cmd.init.add_project_prompt")).
		Value(&addProject).
		Run(); err != nil {
		return err
	}

	if addProject {
		fmt.Fprintf(os.Stdout, "\n%s %s\n\n",
			common.SuccessStyle.Render(common.IconArrow), i18n.T("cmd.init.first_project"))
		return runProjectAddInteractive(ctx, a)
	}

	fmt.Fprintf(os.Stdout, "\n%s %s\n",
		common.SuccessStyle.Render(common.IconSuccess),
		i18n.T("cmd.init.done_no_project"))
	return nil
}

// buildInitConfig generates the hub.toml content.
func buildInitConfig(language, opencodeVer string, mcpServices []string) string {
	var sb strings.Builder
	sb.WriteString(`# oh — OpenHub CLI configuration
# Generated by oh init

[cli]
`)
	fmt.Fprintf(&sb, "language = %q\n", language)
	sb.WriteString(`
[opencode]
`)
	fmt.Fprintf(&sb, "version = %q\n", opencodeVer)
	sb.WriteString(`channel = "stable"
auto_update = false
install_dir = "~/.oh/bin"

[worktree]
auto_cleanup = true
base_branch = ""
`)

	mcpSet := make(map[string]bool)
	for _, s := range mcpServices {
		mcpSet[s] = true
	}

	sb.WriteString(`
[mcp.figma]
`)
	fmt.Fprintf(&sb, "enabled = %v\n", mcpSet["figma"])
	sb.WriteString(`token_key = "figma-token"
`)

	sb.WriteString(`
[mcp.gitlab]
`)
	fmt.Fprintf(&sb, "enabled = %v\n", mcpSet["gitlab"])
	sb.WriteString(`token_key = "gitlab-token"
`)

	sb.WriteString(`
[mcp.gslides]
`)
	fmt.Fprintf(&sb, "enabled = %v\n", mcpSet["gslides"])
	sb.WriteString(`token_key = "gslides-token"
`)

	return sb.String()
}

// addGitExcludes adds opencode and oh artifacts to .git/info/exclude.
func addGitExcludes(projectPath string) {
	excludeFile := filepath.Join(projectPath, ".git", "info", "exclude")

	if _, err := os.Stat(filepath.Join(projectPath, ".git")); err != nil {
		return
	}

	existing, _ := os.ReadFile(excludeFile)
	content := string(existing)

	patterns := []string{".opencode/", "opencode.json"}

	var toAdd []string
	for _, p := range patterns {
		if !strings.Contains(content, p) {
			toAdd = append(toAdd, p)
		}
	}

	if len(toAdd) == 0 {
		return
	}

	_ = os.MkdirAll(filepath.Dir(excludeFile), 0o755)

	f, err := os.OpenFile(excludeFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()

	if len(existing) > 0 && !strings.HasSuffix(content, "\n") {
		_, _ = f.WriteString("\n")
	}
	_, _ = f.WriteString("\n# oh — OpenHub CLI artifacts\n")
	for _, p := range toAdd {
		_, _ = f.WriteString(p + "\n")
	}
}
