package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"

	"github.com/datichb/openhub/cli/internal/config"
	"github.com/datichb/openhub/cli/internal/tui/common"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialise oh pour la première fois",
	Long:  "Lance un wizard de configuration pour initialiser le hub et enregistrer le premier projet.",
	RunE:  runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	fmt.Fprintln(os.Stdout)
	fmt.Fprintln(os.Stdout, common.Title.Render("  Bienvenue dans oh — OpenHub CLI  "))
	fmt.Fprintln(os.Stdout)

	var (
		language     string
		projectName  string
		projectPath  string
		projectLang  string
		tracker      string
		opencodeVer  string
	)

	cwd, _ := os.Getwd()

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("Langue de l'interface").
				Options(
					huh.NewOption("Français", "fr"),
					huh.NewOption("English", "en"),
				).
				Value(&language),
		).Title("Configuration globale"),

		huh.NewGroup(
			huh.NewInput().
				Title("Version d'opencode à utiliser").
				Description("La version sera téléchargée automatiquement").
				Placeholder("latest").
				Value(&opencodeVer),
		).Title("Dépendance opencode"),

		huh.NewGroup(
			huh.NewInput().
				Title("Nom du projet").
				Description("Le projet à enregistrer dans le hub").
				Value(&projectName).
				Validate(func(s string) error {
					if strings.TrimSpace(s) == "" {
						return fmt.Errorf("le nom est requis")
					}
					return nil
				}),

			huh.NewInput().
				Title("Chemin du projet").
				Placeholder(cwd).
				Value(&projectPath),

			huh.NewSelect[string]().
				Title("Langage principal").
				Options(
					huh.NewOption("Go", "go"),
					huh.NewOption("TypeScript", "typescript"),
					huh.NewOption("Python", "python"),
					huh.NewOption("Rust", "rust"),
					huh.NewOption("Java", "java"),
					huh.NewOption("Autre", "other"),
				).
				Value(&projectLang),

			huh.NewSelect[string]().
				Title("Issue tracker").
				Options(
					huh.NewOption("Aucun", ""),
					huh.NewOption("GitHub Issues", "github"),
					huh.NewOption("GitLab Issues", "gitlab"),
					huh.NewOption("Jira", "jira"),
					huh.NewOption("Linear", "linear"),
				).
				Value(&tracker),
		).Title("Premier projet"),
	)

	if err := form.Run(); err != nil {
		return err
	}

	// --- Write config ---
	cfgDir := config.HubDir()
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}

	if opencodeVer == "" {
		opencodeVer = "latest"
	}

	tomlContent := fmt.Sprintf(`# oh — OpenHub CLI configuration
# Generated by oh init

[cli]
language = %q

[opencode]
version = %q
channel = "stable"
auto_update = false
install_dir = "~/.oh/bin"
`, language, opencodeVer)

	cfgPath := config.ConfigPath()
	if err := os.WriteFile(cfgPath, []byte(tomlContent), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Fprintf(os.Stdout, "%s Configuration écrite: %s\n",
		common.SuccessStyle.Render(common.IconSuccess), cfgPath)

	// --- Register project ---
	if projectPath == "" {
		projectPath = cwd
	}
	absPath, err := filepath.Abs(projectPath)
	if err != nil {
		return fmt.Errorf("resolving path: %w", err)
	}

	// Reset config cache so initApp picks up new config
	config.Reset()

	// Init app to get store access
	if err := initApp(); err != nil {
		return err
	}

	a := GetApp()
	if err := doCreateProject(a, projectName, absPath, projectLang, tracker); err != nil {
		return err
	}

	fmt.Fprintln(os.Stdout)
	fmt.Fprintf(os.Stdout, "%s\n", common.SuccessStyle.Render("Initialisation terminée !"))
	fmt.Fprintf(os.Stdout, "  Lancez %s pour démarrer une session.\n", common.Bold.Render("oh start"))

	return nil
}
