package cmd

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"sort"
	"syscall"
	"time"

	"github.com/spf13/cobra"

	"github.com/datichb/openhub/cli/internal/adapters"
	"github.com/datichb/openhub/cli/internal/adapters/opencodev2"
	"github.com/datichb/openhub/cli/internal/app"
	"github.com/datichb/openhub/cli/internal/buildinfo"
	"github.com/datichb/openhub/cli/internal/config"
	"github.com/datichb/openhub/cli/internal/daemon"
	"github.com/datichb/openhub/cli/internal/domain"
	"github.com/datichb/openhub/cli/internal/gateway"
	"github.com/datichb/openhub/cli/internal/gateway/beadswire"
	"github.com/datichb/openhub/cli/internal/i18n"
	"github.com/datichb/openhub/cli/internal/provider"
	"github.com/datichb/openhub/cli/internal/remote"
	"github.com/datichb/openhub/cli/internal/runsvc"
	ohruntime "github.com/datichb/openhub/cli/internal/runtime"
	"github.com/datichb/openhub/cli/internal/services/remote/runner"
	sessionsvc "github.com/datichb/openhub/cli/internal/services/session"
	"github.com/datichb/openhub/cli/internal/sessionspec"
	"github.com/datichb/openhub/cli/internal/storage/sqlite"
)

// `oh runner` is the CI side of the remote runtime (lot 5.B): it only runs
// in the jobs of the oh-runner pipeline generated by `oh remote setup`.

var runnerCmd = &cobra.Command{
	Use:    "runner",
	Short:  i18n.T("cmd.runner.short"),
	Hidden: true,
}

func init() {
	install := &cobra.Command{
		Use:   "install",
		Short: i18n.T("cmd.runner.install.short"),
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runner.Install(cmd.Context(), runner.InstallOptions{ToolVersion: os.Getenv(remote.VarToolVersion), Out: cmd.OutOrStdout()})
		},
	}
	run := &cobra.Command{
		Use:   "run",
		Short: i18n.T("cmd.runner.run.short"),
		Args:  cobra.NoArgs,
		RunE:  runRunnerJob,
	}
	run.Flags().String("out", remote.OutDir, i18n.T("cmd.runner.run.flags.out"))
	runnerCmd.AddCommand(install, run)
	rootCmd.AddCommand(runnerCmd)
}

// isRunnerInstall reports `oh runner install` (image build: no oh home).
func isRunnerInstall(cmd *cobra.Command) bool {
	return cmd.Name() == "install" && cmd.Parent() != nil && cmd.Parent().Name() == "runner"
}

func runRunnerJob(cmd *cobra.Command, _ []string) error {
	out := cmd.OutOrStdout()
	job, err := runner.ReadJob(os.Getenv)
	if err != nil {
		return err
	}
	// Nothing started from here on (daemon, bd, MCP servers, tool server)
	// inherits a secret of the job.
	runner.ScrubEnv()
	ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	a := MustApp()
	outDir, _ := cmd.Flags().GetString("out")
	if outDir, err = filepath.Abs(outDir); err != nil {
		return err
	}
	home := config.HubDir()
	private := filepath.Join(home, "private")
	if err := os.MkdirAll(private, 0o700); err != nil {
		return err
	}
	_ = os.Chmod(home, 0o711)
	for _, f := range []string{"oh.db", "oh.db-wal", "oh.db-shm"} {
		_ = os.Chmod(filepath.Join(home, f), 0o600)
	}

	fmt.Fprintln(out, i18n.Tf("cmd.runner.run.fetching", job.SessionID))
	f, err := runner.Fetch(ctx, job, ohBundlesDir())
	if err != nil {
		return err
	}
	m := &f.Manifest
	if m.OhVersion != buildinfo.Version {
		fmt.Fprintln(out, i18n.Tf("cmd.runner.run.version_differs", m.OhVersion, buildinfo.Version))
	}
	if err := a.Projects.Create(ctx, &domain.Project{ID: m.Project.OhID, Name: m.Project.Name, Path: m.WorkDir, Provider: job.Provider}); err != nil &&
		!errors.Is(err, domain.ErrAlreadyExists) {
		return fmt.Errorf("recording the project: %w", err)
	}

	// Beads: the gateway of the job daemon runs the fake bd in journal mode.
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	snapPath := filepath.Join(private, remote.SnapshotFile)
	if err := writeRunnerJSON(snapPath, f.Snapshot); err != nil {
		return err
	}
	for k, v := range map[string]string{beadswire.EnvMode: beadswire.ModeJournal, beadswire.EnvSnapshot: snapPath,
		beadswire.EnvJournal: runner.JournalPath(outDir)} {
		_ = os.Setenv(k, v)
	}
	bd, err := exec.LookPath("bd")
	if err != nil {
		return errors.New(i18n.T("cmd.runner.run.no_bd"))
	}

	ad, err := detectV2Adapter(ctx)
	if err != nil {
		return fmt.Errorf("opencode: %w", err)
	}
	secrets := runner.CISecrets{LLMKey: job.Secrets.LLMKey}
	paths := daemon.Paths{Dir: ohRunDir()}
	dctx, stopDaemon := context.WithCancel(context.WithoutCancel(ctx))
	daemonDone := make(chan error, 1)
	go func() {
		daemonDone <- daemon.Run(dctx, daemon.Options{
			Paths: paths, Version: buildinfo.Version,
			Grants: sqlite.NewGrantStore(store), Servers: sqlite.NewServerStore(store),
			GatewayView: func(context.Context, string) (gateway.View, error) {
				return gateway.View{Locations: []string{m.WorkDir}}, nil
			},
			BeadsBinary: bd, MCPCommand: gatewayMCPCommand(ohBundlesDir()),
			Sessions: a.Sessions, Decisions: sqlite.NewDecisionStore(store),
			SessionsDir: ohSessionsDir(), ServersDir: ohServersDir(),
			Checkpoints: newCheckpointService(a), Secrets: secrets,
			IdleAfter: 24 * time.Hour, IdleSleep: 24 * time.Hour,
			Adapter: func(name string) adapters.ToolAdapter {
				if name == opencodev2.Name {
					return ad
				}
				return nil
			},
		})
	}()
	defer func() {
		stopDaemon()
		select {
		case <-daemonDone:
		case <-time.After(10 * time.Second):
		}
	}()
	dc := daemon.NewClient(paths)
	if err := waitDaemon(ctx, dc, daemonDone); err != nil {
		return err
	}

	user := runner.LookupServerUser()
	if user == nil && os.Geteuid() == 0 {
		fmt.Fprintln(out, i18n.T("cmd.runner.run.no_server_user"))
	}
	serverHome := filepath.Join(home, "server-home")
	if user != nil && user.Home != "" {
		serverHome = user.Home
	}
	rs := &runsvc.Service{
		Adapter: ad, AdapterVer: ad.Ver, Servers: sqlite.NewServerStore(store), Sessions: a.Sessions, Secrets: secrets,
		ServersDir: ohServersDir(), BundlesDir: ohBundlesDir(), SessionsDir: ohSessionsDir(),
		Decisions: sqlite.NewDecisionStore(store),
		Runtimes: map[sessionspec.RuntimeKind]ohruntime.Runtime{
			sessionspec.RuntimeRemote: &runner.JobRuntime{User: user, Home: serverHome, Root: home},
		},
		SessionEnv: runnerSessionEnv(dc),
		Daemon:     func(context.Context) (runsvc.DaemonClient, error) { return dc, nil },
	}
	ss := &sessionsvc.Service{Sessions: a.Sessions, Projects: a.Projects, Decisions: sqlite.NewDecisionStore(store),
		Servers: sqlite.NewServerStore(store), BundlesDir: ohBundlesDir(), SessionsDir: ohSessionsDir(), Adapter: ad,
		Alive: func(int) bool { return true }}
	ss.UseCheckpoints(newCheckpointService(a), dc.WorkflowRefresh)

	in := runner.Input{
		Job: job, Fetched: f, OutDir: outDir,
		Git:       runner.Git{Token: job.Secrets.ProjectToken, Secrets: job.Secrets},
		Session:   &jobSession{a: a, rs: rs, ss: ss, ad: ad, region: job.Region},
		Responder: runner.NewResponder(sqlite.NewDecisionStore(store), ss.Decide, m),
	}
	if m.Team != nil {
		if repo, err := runner.OpenTeamState(ctx, m.Team, job.Secrets.TeamStateToken, filepath.Join(private, "team-state"), job.Secrets); err == nil {
			in.Progress = &runner.TeamProgress{Repo: repo, Project: m.Project.OhID, Tickets: m.Tickets, Session: m.SessionID,
				Target: m.Target, Pipeline: job.PipelineID, PipelineURL: job.PipelineURL}
		} else {
			fmt.Fprintln(out, i18n.Tf("cmd.runner.run.no_claims", err))
		}
	}
	fmt.Fprintln(out, i18n.Tf("cmd.runner.run.starting", m.Workflow.ID, m.Project.Path, m.Branch))
	sum, err := runner.Run(ctx, in)
	if sum != nil {
		fmt.Fprintln(out, i18n.Tf("cmd.runner.run.done", sum.Outcome, sum.Cost, sum.JournalEntries, firstNonEmpty(sum.MRURL, "-")))
	}
	return err
}

func waitDaemon(ctx context.Context, dc *daemon.Client, done <-chan error) error {
	deadline := time.Now().Add(20 * time.Second)
	for time.Now().Before(deadline) {
		if _, err := dc.Health(ctx); err == nil {
			return nil
		}
		select {
		case err := <-done:
			return fmt.Errorf("oh daemon: %w", err)
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(200 * time.Millisecond):
		}
	}
	return errors.New("oh daemon did not start")
}

// runnerSessionEnv gives the sessions of the job their Beads gateway token
// (same daemon API as the container runtime).
func runnerSessionEnv(dc gatewayGranter) runsvc.SessionEnvFunc {
	return func(ctx context.Context, r runsvc.SessionEnvRequest) (map[string]string, error) {
		if r.Runtime != sessionspec.RuntimeRemote {
			return nil, nil
		}
		if r.GatewayURL == "" {
			return nil, errors.New("beads gateway: the server group has no gateway address")
		}
		g, err := dc.IssueGatewayGrant(ctx, daemon.GatewayGrantRequest{
			SessionID: r.SessionID, GroupKey: r.GroupKey, ProjectID: r.ProjectID, WorkflowID: r.WorkflowID,
			Location: r.Location, BeadsAllow: r.BeadsAllow, GatewayURL: r.GatewayURL,
		})
		if err != nil {
			return nil, fmt.Errorf("beads gateway: %w", err)
		}
		return map[string]string{beadswire.EnvURL: r.GatewayURL, beadswire.EnvToken: g.Token}, nil
	}
}

func writeRunnerJSON(path string, v any) error {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}

// jobSession implements runner.Session on the services of the job.
type jobSession struct {
	a      *app.App
	rs     *runsvc.Service
	ss     *sessionsvc.Service
	ad     *opencodev2.Adapter
	region string
}

func (j *jobSession) Start(ctx context.Context, req runsvc.StartRequest) (string, error) {
	req.ProviderCfg = provider.Config{AWSRegion: j.region}
	res, err := j.rs.StartSession(ctx, req)
	if err != nil {
		return "", err
	}
	return res.SessionID, nil
}

func (j *jobSession) AwaitTurn(ctx context.Context, sid string) (*runsvc.HeadlessResult, error) {
	return j.rs.AwaitTurn(ctx, sid)
}

func (j *jobSession) Interrupt(ctx context.Context, sid string) error {
	return j.ss.Interrupt(ctx, sid)
}

func (j *jobSession) Stop(ctx context.Context, sid string) error { return j.rs.StopSession(ctx, sid) }

func (j *jobSession) handle(ctx context.Context, sid string) (adapters.ServerHandle, error) {
	sess, err := j.a.Sessions.Get(ctx, sid)
	if err != nil {
		return adapters.ServerHandle{}, err
	}
	srv, err := j.rs.Servers.Get(ctx, sess.GroupKey)
	if err != nil {
		return adapters.ServerHandle{}, err
	}
	return adapters.ServerHandle{URL: srv.URL, Password: srv.Password, PID: srv.PID}, nil
}

func (j *jobSession) Results(ctx context.Context, sid string) (adapters.SessionResult, error) {
	h, err := j.handle(ctx, sid)
	if err != nil {
		return adapters.SessionResult{}, err
	}
	return j.ad.Results(ctx, h, sid)
}

// Export returns the session and its sub-agent sessions, parents first.
func (j *jobSession) Export(ctx context.Context, sid string) ([]json.RawMessage, []string, error) {
	h, err := j.handle(ctx, sid)
	if err != nil {
		return nil, nil, err
	}
	ids := []string{sid}
	if children, err := j.ad.Children(ctx, h); err == nil {
		ids = append(ids, descendants(sid, children)...)
	}
	var out []json.RawMessage
	for _, id := range ids {
		data, err := j.ad.ExportSession(ctx, h, id)
		if err != nil {
			return nil, nil, fmt.Errorf("exporting %s: %w", id, err)
		}
		out = append(out, data)
	}
	return out, ids, nil
}

// descendants lists the sessions under root, each after its parent.
func descendants(root string, parentOf map[string]string) []string {
	kids := map[string][]string{}
	for c, p := range parentOf {
		kids[p] = append(kids[p], c)
	}
	var out []string
	queue := []string{root}
	for len(queue) > 0 {
		p := queue[0]
		queue = queue[1:]
		ks := kids[p]
		sort.Strings(ks)
		out = append(out, ks...)
		queue = append(queue, ks...)
	}
	return out
}

func (j *jobSession) Failed(ctx context.Context, sid string) bool {
	h, err := j.handle(ctx, sid)
	if err != nil {
		return false
	}
	s, err := opencodev2.NewClient(h.URL, h.Password).GetSession(ctx, sid)
	return err == nil && s.Outcome == "failed"
}

func (j *jobSession) Outputs(ctx context.Context, sid string) map[string]any {
	if sess, err := j.a.Sessions.Get(ctx, sid); err == nil && len(sess.Outputs) > 0 {
		return sess.Outputs
	}
	return nil
}
