// Package remote is the service of the remote runtime (v5 phase 5): set up
// and check the oh-runner project of a GitLab group (lot 5.0).
package remote

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"slices"
	"strings"

	"github.com/datichb/openhub/cli/internal/config"
	"github.com/datichb/openhub/cli/internal/domain"
	"github.com/datichb/openhub/cli/internal/remote"
	"github.com/datichb/openhub/cli/internal/remote/ciconfig"
	"github.com/datichb/openhub/cli/internal/remote/gitlab"
)

// CIFile is the pipeline file of the oh-runner project.
const CIFile = ".gitlab-ci.yml"

// Errors of the setup.
var (
	ErrNoToken              = errors.New("no GitLab API token for this target")
	ErrRunnerProjectMissing = errors.New("oh-runner project not found")
	ErrForeignPipeline      = errors.New("the oh-runner project has a pipeline file not generated by oh")
	ErrWeakSecret           = errors.New("secret too short or multi-line: GitLab cannot mask it (8 characters minimum, one line)")
)

// Service sets up and checks remote targets.
type Service struct {
	// Secrets is the machine secret store (API token, trigger token).
	Secrets domain.SecretStore
	// SaveTarget persists a target in hub.toml.
	SaveTarget func(config.RemoteTarget) error
	// NewClient builds the GitLab client (default gitlab.New).
	NewClient func(baseURL, token string) *gitlab.Client
	// OhVersion is the version of the running oh (buildinfo.Version).
	OhVersion string
}

func (s *Service) client(t config.RemoteTarget, token string) *gitlab.Client {
	if s.NewClient != nil {
		return s.NewClient(t.URL, token)
	}
	return gitlab.New(t.URL, token)
}

// StepStatus is the outcome of a setup or check step.
type StepStatus string

// Step statuses.
const (
	StepOK      StepStatus = "ok"      // present and valid
	StepCreated StepStatus = "created" // created by this call
	StepUpdated StepStatus = "updated" // replaced by this call
	StepWarn    StepStatus = "warn"    // usable, but something to fix
	StepFailed  StepStatus = "failed"  // blocking
	StepSkipped StepStatus = "skipped" // not checked (an earlier step failed)
)

// Step identifiers (stable: i18n keys cmd.remote.step.<id>).
const (
	StepAccess    = "access"
	StepGroup     = "group"
	StepProject   = "project"
	StepFeatures  = "features"
	StepProtected = "protected"
	StepPipeline  = "pipeline"
	StepTrigger   = "trigger"
	StepVariable  = "variable"
	StepRunners   = "runners"
	StepBinary    = "binary"
)

// Step is one line of a report. Args are the values of the message
// (usernames, paths, variable names…), never a secret.
type Step struct {
	ID     string
	Status StepStatus
	Args   []string
	Err    error
}

// Report is the result of Setup or Check.
type Report struct {
	Target config.RemoteTarget
	Steps  []Step
}

// OK reports whether no step failed.
func (r *Report) OK() bool {
	for _, s := range r.Steps {
		if s.Status == StepFailed {
			return false
		}
	}
	return true
}

func (r *Report) add(id string, st StepStatus, err error, args ...string) {
	r.Steps = append(r.Steps, Step{ID: id, Status: st, Args: args, Err: err})
}

// LLMSecret is the provider key of the jobs.
type LLMSecret struct {
	Provider string // oh provider name (bedrock, anthropic, openrouter)
	Region   string // Bedrock region
	Key      string // API key (Bedrock API key, Anthropic key…)
}

// ProjectToken is the access token of one target project.
type ProjectToken struct {
	Path  string // full path of the project (resolved to its ID)
	Token string
}

// SetupRequest describes a setup run. Empty secrets are left untouched.
type SetupRequest struct {
	Target config.RemoteTarget
	// Token is a new API token (stored under Target.TokenKeyOrDefault()).
	Token string
	// Create creates the oh-runner project when it is missing.
	Create bool
	// Force replaces a pipeline file not generated by oh.
	Force          bool
	LLM            *LLMSecret
	Projects       []ProjectToken
	TeamStateToken string
	// OhBinary is a Linux oh binary to upload (development builds).
	OhBinary string
}

func validSecret(v string) bool {
	return len(v) >= 8 && !strings.ContainsAny(v, "\n\r")
}

// Setup creates or validates the oh-runner project of a target, its pipeline,
// trigger and variables, and saves the target. It stops at the first blocking
// step; the report lists what was done.
func (s *Service) Setup(ctx context.Context, req SetupRequest) (*Report, error) {
	t := req.Target
	if err := t.Validate(); err != nil {
		return nil, err
	}
	if err := (ciconfig.Options{Tag: t.Tag, Builder: t.Builder, Arch: t.Arch, Timeout: t.Timeout}).Validate(); err != nil {
		return nil, err
	}
	for _, v := range []string{req.TeamStateToken} {
		if v != "" && !validSecret(v) {
			return nil, ErrWeakSecret
		}
	}
	if req.LLM != nil && !validSecret(req.LLM.Key) {
		return nil, ErrWeakSecret
	}
	for _, p := range req.Projects {
		if !validSecret(p.Token) {
			return nil, fmt.Errorf("%s: %w", p.Path, ErrWeakSecret)
		}
	}
	if s.Secrets == nil {
		return nil, errors.New("no secret store available")
	}
	if req.Token != "" {
		if err := s.Secrets.Set(ctx, t.TokenKeyOrDefault(), req.Token); err != nil {
			return nil, fmt.Errorf("storing the GitLab token: %w", err)
		}
	}
	token, _ := s.Secrets.Get(ctx, t.TokenKeyOrDefault())
	if token == "" {
		return nil, ErrNoToken
	}
	c := s.client(t, token)
	rep := &Report{Target: t}

	if _, err := s.access(ctx, c, rep); err != nil {
		return rep, err
	}
	g, err := c.Group(ctx, t.Group)
	if err != nil {
		rep.add(StepGroup, StepFailed, err, t.Group)
		return rep, err
	}
	rep.add(StepGroup, StepOK, nil, g.FullPath)

	path := t.RunnerProjectPath()
	p, err := c.Project(ctx, path)
	switch {
	case gitlab.IsNotFound(err) && req.Create:
		if !strings.HasPrefix(path, strings.Trim(t.Group, "/")+"/") || strings.Count(strings.TrimPrefix(path, strings.Trim(t.Group, "/")+"/"), "/") > 0 {
			err = fmt.Errorf("cannot create %s: it must be a direct child of the group %s", path, t.Group)
			rep.add(StepProject, StepFailed, err, path)
			return rep, err
		}
		name := path[strings.LastIndexByte(path, '/')+1:]
		p, err = c.CreateProject(ctx, gitlab.CreateProjectRequest{Name: name, Path: name, NamespaceID: g.ID,
			Description: "oh remote sessions (pipeline generated by oh remote setup)"})
		if err != nil {
			rep.add(StepProject, StepFailed, err, path)
			return rep, err
		}
		rep.add(StepProject, StepCreated, nil, p.PathWithNamespace)
	case gitlab.IsNotFound(err):
		rep.add(StepProject, StepFailed, ErrRunnerProjectMissing, path)
		return rep, ErrRunnerProjectMissing
	case err != nil:
		rep.add(StepProject, StepFailed, err, path)
		return rep, err
	default:
		rep.add(StepProject, StepOK, nil, p.PathWithNamespace)
	}
	t.RunnerProjectID = p.ID
	t.RunnerProject = p.PathWithNamespace
	rep.Target = t
	pid := fmt.Sprint(p.ID)

	if !s.features(rep, p) {
		return rep, errors.New("the oh-runner project lacks the package or container registry")
	}
	branch := p.DefaultBranch
	if branch == "" {
		branch = "main"
	}
	s.protected(ctx, c, rep, pid, branch)

	if err := s.pipeline(ctx, c, rep, pid, branch, t, req.Force); err != nil {
		return rep, err
	}
	if err := s.trigger(ctx, c, rep, pid, t); err != nil {
		return rep, err
	}
	if err := s.variables(ctx, c, rep, pid, req); err != nil {
		return rep, err
	}
	s.runners(ctx, c, rep, pid, t)
	if req.OhBinary != "" {
		pkg, err := s.uploadBinary(ctx, c, pid, req.OhBinary, archOf(t))
		if err != nil {
			rep.add(StepBinary, StepFailed, err, s.OhVersion)
			return rep, err
		}
		if t.Binaries == nil {
			t.Binaries = map[string]string{}
		}
		t.Binaries[BinaryKey(s.OhVersion, archOf(t))] = pkg
		rep.Target = t
		rep.add(StepBinary, StepUpdated, nil, s.OhVersion, pkg[:12])
	} else {
		s.binary(rep, t)
	}

	if s.SaveTarget != nil {
		if err := s.SaveTarget(t); err != nil {
			return rep, fmt.Errorf("saving the remote target: %w", err)
		}
	}
	return rep, nil
}

// Check verifies a configured target without changing anything.
func (s *Service) Check(ctx context.Context, t config.RemoteTarget) *Report {
	rep := &Report{Target: t}
	token := ""
	if s.Secrets != nil {
		token, _ = s.Secrets.Get(ctx, t.TokenKeyOrDefault())
	}
	if token == "" {
		rep.add(StepAccess, StepFailed, ErrNoToken, t.TokenKeyOrDefault())
		return rep
	}
	c := s.client(t, token)
	if _, err := s.access(ctx, c, rep); err != nil {
		return rep
	}
	path := t.RunnerProjectPath()
	if t.RunnerProjectID != 0 {
		path = fmt.Sprint(t.RunnerProjectID)
	}
	p, err := c.Project(ctx, path)
	if err != nil {
		if gitlab.IsNotFound(err) {
			err = ErrRunnerProjectMissing
		}
		rep.add(StepProject, StepFailed, err, t.RunnerProjectPath())
		return rep
	}
	rep.add(StepProject, StepOK, nil, p.PathWithNamespace)
	pid := fmt.Sprint(p.ID)
	if !s.features(rep, p) {
		return rep
	}
	branch := p.DefaultBranch
	if branch == "" {
		branch = "main"
	}
	s.protected(ctx, c, rep, pid, branch)

	want, _ := ciconfig.Generate(ciOptions(t))
	cur, err := c.File(ctx, pid, CIFile, branch)
	switch {
	case gitlab.IsNotFound(err):
		rep.add(StepPipeline, StepFailed, errors.New("missing"), CIFile)
	case err != nil:
		rep.add(StepPipeline, StepFailed, err, CIFile)
	case bytes.Equal(cur, want):
		rep.add(StepPipeline, StepOK, nil, CIFile)
	case bytes.HasPrefix(cur, []byte(ciconfig.Marker)):
		rep.add(StepPipeline, StepWarn, errors.New("outdated: run oh remote setup"), CIFile)
	default:
		rep.add(StepPipeline, StepFailed, ErrForeignPipeline, CIFile)
	}

	trig, _ := s.Secrets.Get(ctx, t.TriggerKeyOrDefault())
	if trig == "" {
		rep.add(StepTrigger, StepFailed, errors.New("no trigger token on this machine"), t.TriggerKeyOrDefault())
	} else {
		rep.add(StepTrigger, StepOK, nil, t.TriggerKeyOrDefault())
	}
	s.reportVariables(ctx, c, rep, pid)
	s.runners(ctx, c, rep, pid, t)
	s.binary(rep, t)
	return rep
}

func (s *Service) access(ctx context.Context, c *gitlab.Client, rep *Report) (*gitlab.User, error) {
	u, err := c.CurrentUser(ctx)
	if err != nil {
		rep.add(StepAccess, StepFailed, err, c.BaseURL())
		return nil, err
	}
	rep.add(StepAccess, StepOK, nil, u.Username, c.BaseURL())
	return u, nil
}

func (s *Service) features(rep *Report, p *gitlab.Project) bool {
	var missing []string
	if !p.PackagesOn() {
		missing = append(missing, "packages")
	}
	if !p.RegistryEnabled() {
		missing = append(missing, "container_registry")
	}
	if len(missing) > 0 {
		rep.add(StepFeatures, StepFailed, errors.New("disabled: "+strings.Join(missing, ", ")), strings.Join(missing, ", "))
		return false
	}
	rep.add(StepFeatures, StepOK, nil)
	return true
}

func (s *Service) protected(ctx context.Context, c *gitlab.Client, rep *Report, pid, branch string) {
	ok, err := c.BranchProtected(ctx, pid, branch)
	switch {
	case err != nil:
		rep.add(StepProtected, StepWarn, err, branch)
	case !ok:
		rep.add(StepProtected, StepFailed, errors.New("not protected: protected CI variables are not exposed"), branch)
	default:
		rep.add(StepProtected, StepOK, nil, branch)
	}
}

func ciOptions(t config.RemoteTarget) ciconfig.Options {
	return ciconfig.Options{Tag: t.Tag, Builder: t.Builder, Arch: t.Arch, Timeout: t.Timeout}
}

func (s *Service) pipeline(ctx context.Context, c *gitlab.Client, rep *Report, pid, branch string, t config.RemoteTarget, force bool) error {
	want, err := ciconfig.Generate(ciOptions(t))
	if err != nil {
		return err
	}
	cur, err := c.File(ctx, pid, CIFile, branch)
	switch {
	case gitlab.IsNotFound(err):
		if err := c.CommitFile(ctx, pid, branch, CIFile, want, "oh: pipeline of remote sessions", true); err != nil {
			rep.add(StepPipeline, StepFailed, err, CIFile)
			return err
		}
		rep.add(StepPipeline, StepCreated, nil, CIFile)
	case err != nil:
		rep.add(StepPipeline, StepFailed, err, CIFile)
		return err
	case bytes.Equal(cur, want):
		rep.add(StepPipeline, StepOK, nil, CIFile)
	case !bytes.HasPrefix(cur, []byte(ciconfig.Marker)) && !force:
		rep.add(StepPipeline, StepFailed, ErrForeignPipeline, CIFile)
		return ErrForeignPipeline
	default:
		if err := c.CommitFile(ctx, pid, branch, CIFile, want, fmt.Sprintf("oh: pipeline of remote sessions (schema %d)", remote.PipelineSchema), false); err != nil {
			rep.add(StepPipeline, StepFailed, err, CIFile)
			return err
		}
		rep.add(StepPipeline, StepUpdated, nil, CIFile)
	}
	return nil
}

func (s *Service) trigger(ctx context.Context, c *gitlab.Client, rep *Report, pid string, t config.RemoteTarget) error {
	key := t.TriggerKeyOrDefault()
	cur, _ := s.Secrets.Get(ctx, key)
	if cur != "" {
		ts, err := c.Triggers(ctx, pid)
		if err == nil && slices.ContainsFunc(ts, func(tr gitlab.Trigger) bool { return tr.Token == cur }) {
			rep.add(StepTrigger, StepOK, nil, key)
			return nil
		}
		// Unknown to GitLab (revoked) or not listable: replaced below.
	}
	tr, err := c.CreateTrigger(ctx, pid, "oh remote sessions")
	if err != nil {
		rep.add(StepTrigger, StepFailed, err, key)
		return err
	}
	if err := s.Secrets.Set(ctx, key, tr.Token); err != nil {
		rep.add(StepTrigger, StepFailed, err, key)
		return err
	}
	rep.add(StepTrigger, StepCreated, nil, key)
	return nil
}

func (s *Service) variables(ctx context.Context, c *gitlab.Client, rep *Report, pid string, req SetupRequest) error {
	set := func(v gitlab.Variable) error {
		if err := c.SetVariable(ctx, pid, v); err != nil {
			rep.add(StepVariable, StepFailed, err, v.Key)
			return err
		}
		rep.add(StepVariable, StepUpdated, nil, v.Key)
		return nil
	}
	secret := func(key, value string) gitlab.Variable {
		return gitlab.Variable{Key: key, Value: value, Masked: true, Protected: true, Raw: true}
	}
	if req.LLM != nil {
		if err := set(gitlab.Variable{Key: remote.VarLLMProvider, Value: req.LLM.Provider, Protected: true, Raw: true}); err != nil {
			return err
		}
		if req.LLM.Region != "" {
			if err := set(gitlab.Variable{Key: remote.VarLLMRegion, Value: req.LLM.Region, Protected: true, Raw: true}); err != nil {
				return err
			}
		}
		if err := set(secret(remote.VarLLMKey, req.LLM.Key)); err != nil {
			return err
		}
	}
	for _, pt := range req.Projects {
		p, err := c.Project(ctx, pt.Path)
		if err != nil {
			rep.add(StepVariable, StepFailed, err, pt.Path)
			return err
		}
		if err := set(secret(remote.ProjectTokenVar(p.ID), pt.Token)); err != nil {
			return err
		}
	}
	if req.TeamStateToken != "" {
		if err := set(secret(remote.VarTeamStateToken, req.TeamStateToken)); err != nil {
			return err
		}
	}
	s.reportVariables(ctx, c, rep, pid)
	return nil
}

// reportVariables lists the required variables that are missing.
func (s *Service) reportVariables(ctx context.Context, c *gitlab.Client, rep *Report, pid string) {
	vs, err := c.Variables(ctx, pid)
	if err != nil {
		rep.add(StepVariable, StepWarn, err, "*")
		return
	}
	have := map[string]gitlab.Variable{}
	projects := 0
	for _, v := range vs {
		have[v.Key] = v
		if _, ok := remote.ProjectTokenID(v.Key); ok {
			projects++
		}
	}
	for _, k := range []string{remote.VarLLMProvider, remote.VarLLMKey} {
		if _, ok := have[k]; !ok {
			rep.add(StepVariable, StepFailed, errors.New("missing"), k)
		}
	}
	if v, ok := have[remote.VarLLMKey]; ok && !v.Masked {
		rep.add(StepVariable, StepFailed, errors.New("not masked"), remote.VarLLMKey)
	}
	if _, ok := have[remote.VarTeamStateToken]; !ok {
		rep.add(StepVariable, StepWarn, errors.New("missing: claims not updated by the runner"), remote.VarTeamStateToken)
	}
	if projects == 0 {
		rep.add(StepVariable, StepWarn, errors.New("no project token"), remote.ProjectTokenVar(0))
	} else {
		rep.add(StepVariable, StepOK, nil, fmt.Sprint(projects))
	}
}

func (s *Service) runners(ctx context.Context, c *gitlab.Client, rep *Report, pid string, t config.RemoteTarget) {
	tag := t.Tag
	if tag == "" {
		tag = ciconfig.DefaultTag
	}
	rs, err := c.OnlineRunners(ctx, pid, tag)
	switch {
	case err != nil:
		rep.add(StepRunners, StepWarn, err, tag)
	case len(rs) == 0:
		rep.add(StepRunners, StepWarn, errors.New("no online runner"), tag)
	default:
		rep.add(StepRunners, StepOK, nil, tag, fmt.Sprint(len(rs)))
	}
}

func archOf(t config.RemoteTarget) string {
	if t.Arch == "" {
		return ciconfig.DefaultArch
	}
	return t.Arch
}

// BinaryKey is the key of Target.Binaries.
func BinaryKey(version, arch string) string { return version + "/" + arch }

var releaseRe = regexp.MustCompile(`^v?\d+\.\d+\.\d+$`)

// IsRelease reports whether version is a published release (downloaded by
// the job) rather than a development build (uploaded by setup).
func IsRelease(version string) bool { return releaseRe.MatchString(version) }

// binary reports how the job gets the oh binary of this version.
func (s *Service) binary(rep *Report, t config.RemoteTarget) {
	switch {
	case IsRelease(s.OhVersion):
		rep.add(StepBinary, StepOK, nil, s.OhVersion, "release")
	case t.Binaries[BinaryKey(s.OhVersion, archOf(t))] != "":
		rep.add(StepBinary, StepOK, nil, s.OhVersion, t.Binaries[BinaryKey(s.OhVersion, archOf(t))][:12])
	default:
		rep.add(StepBinary, StepFailed, errors.New("development build not uploaded: oh remote setup --oh-binary"), s.OhVersion)
	}
}

// elfMagic starts every Linux executable.
var elfMagic = []byte{0x7f, 'E', 'L', 'F'}

// uploadBinary uploads a Linux oh binary as oh-cli/<sha256>/oh-linux-<arch>
// and returns the package version.
func (s *Service) uploadBinary(ctx context.Context, c *gitlab.Client, pid, path, arch string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	st, err := f.Stat()
	if err != nil {
		return "", err
	}
	head := make([]byte, 4)
	if _, err := io.ReadFull(f, head); err != nil || !bytes.Equal(head, elfMagic) {
		return "", fmt.Errorf("%s is not a Linux executable (build it with make build-linux)", path)
	}
	h := sha256.New()
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		return "", err
	}
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	version := hex.EncodeToString(h.Sum(nil))
	exists, err := c.GenericPackageExists(ctx, pid, remote.PackageCLI, version, remote.CLIFile(arch))
	if err != nil {
		return "", err
	}
	if exists {
		return version, nil
	}
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		return "", err
	}
	if _, err := c.UploadGenericPackage(ctx, pid, remote.PackageCLI, version, remote.CLIFile(arch), f, st.Size()); err != nil {
		return "", err
	}
	return version, nil
}
